### ISSUE TITLE
Large objects are not appropriately centered when picked up by Parasaurolophus.

### ISSUE THREAD

**Issue by teatimejess** [BoBAdministration/QA-Bug-Reports#1]
**Describe the Bug**
When a Parasaurolophus character pawn picks up a large object, such as a tree to large seaweed, the object is held so it goes back into the body from the mouth rather than being held to the side.

**To Reproduce**
1. Spawn in as a Para on Rival Shores,
2. Setgrowthlevel 1.5,
3. Find tree node ( TeleportAt 89619 87156 4950 ),
4. Pick up tree.

**Expected behavior**
Parasaur picks up tree and carries it perpendicular to it's body.

**Actual behavior**
Parasaur picks up tree and carries it parallel to it's body, creating an unnatural clipping event.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/77513445/129306532-e9d84210-097c-4d36-b8bb-5aae6fc8dbca.png)

**Branch Version**
Tested on Live

**Character Information**
Parasaurolophus, growth 1.5, no talents.

**Additional Information**
Rival shores, though applies to all  similar objects across maps.

**Comment by Predatoria** [comment]
Fixed next tester patch

**Comment by teatimejess** [comment]
> 1. Spawn in as a Para on Rival Shores,
> 2. Setgrowthlevel 1.5,
> 3. Find tree node ( TeleportAt 89619 87156 4950 ),
> 4. Pick up tree.

Confirmed fixed on tester!
