### ISSUE TITLE
The screen twitches when jumping

### ISSUE THREAD

**Issue by Ghoconley** [BoBAdministration/QA-Bug-Reports#10]
**Describe the Bug**
The screen twitches when jumping

Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. ex. Logged into Dedicated Testing 2
2. ex. Spawned in a Coah at Winter
3. ex. Pumped powerfull legs in 2
4. ex. broken jump 

**Expected behavior**

simpe not twitches screen when i jump
**Actual behavior**
twitches screen

**Screenshots & Video**
https://youtu.be/AaJtXtfZvoI

 **Branch Version**
Tester

**Character Information**
1.2 growth / 2 powerfull legs
**Additional Information**
Map type, weather, or any other context about the problem here.

**Comment by Predatoria** [comment]
Coah can no longer jump next tester patch, so this should be no longer possible.
