### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by Sonatasuarus** [BoBAdministration/QA-Bug-Reports#100]
**Describe the Bug**
Ash decals left by fires show over the top of creatures models.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Fire happened on the server.
2. Walked through the ash decals left behind from the fire.
3. Texture shows over the dinosaur model.

**Expected behavior**
The dinosaur model and texture should have been separate from the ash texture.

**Actual behavior**
The ash texture shows over the dinosaurs model textures.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/96402324/146820575-dc9c97e9-7600-4745-bd37-65ee552db4eb.png)

**Branch Version**
Tester and Public

**Character Information**
Nested Sai, 1.2.

**Additional Information**
Clear weather, Ancestral Plains map, shortly after fire.

**Comment by tinystarpaws** [comment]
+
Meeting Example only; not a true bug report submission. Closing.
