### ISSUE TITLE
Enter a one-line concise summary.

### ISSUE THREAD

**Issue by Silemara** [BoBAdministration/QA-Bug-Reports#101]
**Describe the Bug**

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. ex. Logged into Dedicated Testing 1
2. ex. Spawned in a Megalo at Jungle
3. ex. Drank from big pond
4. ex. "..." happened

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshots & Video**
If applicable, add screenshots to help explain your problem, or attach a video/gif. You can do this by just pasting in your image(s)!

**Branch Version**
Tester or Live.

**Character Information**
Dinosaur growth and type. Include any other relevant character information such as talents, inherits, gender, and stats if necessary.

**Additional Information**
Map type, weather, or any other context about the problem here.

**Comment by tinystarpaws** [comment]
Closing; accidentally made.
