### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by Zer0Health** [BoBAdministration/QA-Bug-Reports#102]
**Describe the Bug**
When a creature walks over ash the ash texture goes over top of the creatures texture.

**To Reproduce**
1: Spawn dino
2: fire has happened and ended.
3: Walk over ash texture

**Expected behavior**
For the ash to not over lay the creatures texture

**Actual behavior**
After a fire and the ash texture is on the ground if a creature walks over it the ash texture overlays the creatures texture

**Screenshots & Video**
https://media.discordapp.net/attachments/922324689177673778/922567776688803950/u6IfomaDTyauK8lhKEmXeg.png

**Branch Version**
Live

**Character Information**
Sai, 1.0, shimmer skin

**Additional Information**
after effects of a fire.

**Comment by tinystarpaws** [comment]
+
Meeting Example only; not a true bug report submission. Closing.
