### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by Arko3** [BoBAdministration/QA-Bug-Reports#103]
**Describe the Bug**
Texture overlay where ist shouldnt overlay.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. ex. Logged into Dedicated Testing 1
2. ex. Spawned in a sai at Forest
3. ex. Ran to a burnt patch
4. ex. texture overlayed the sais skin

**Expected behavior**
Burnt patch stays on the ground like a good boi

**Actual behavior**
Burnt patch moves over the players skin 

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/96443166/146820901-c60da4b3-5428-4d29-81cb-a5c1999e86d6.png)

**Branch Version** 
Live.

**Character Information**
sais growth 1.124

**Additional Information**

RS after a major fire broke out

**Comment by tinystarpaws** [comment]
+
Meeting Example only; not a true bug report submission. Closing.
