### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by WayaShinzui** [BoBAdministration/QA-Bug-Reports#104]
**Describe the Bug**
Ground ash decals from a fire shows on top of dino when walked over.

**To Reproduce**
1- Fire burnt out
2- Walked over to fire area on sai
3- Stepped onto ground ash decals

**Expected behavior**
Decals should stay on the ground and not show up on dino.

**Actual behavior**
When a dino walks over the ground ash decals they show up on the dino as well as the ground and cover the dino's skin.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/96402367/146820858-929dcf90-f938-4bc2-9c21-2d0f34a40683.png)

**Branch Version**
Tester.

**Character Information**
1.0 Saichania

**Additional Information**
Map type, weather, or any other context about the problem here.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
