### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by Ruined-Omega** [BoBAdministration/QA-Bug-Reports#105]
**Describe the Bug**
Ash Decals show on the character model when it should be happening

**To Reproduce**
1. Log in to testing server
2. Start a fire and let an area burn out
3. Take your character to the previously burned area
4. Walk over the ash texture and the bug should replicate

**Expected behavior**
Character model should show your skin regularly with no unusual textures

**Actual behavior**
The texture from the ash reflects over the model obscuring the model

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/96402107/146820821-1e89ef2b-812b-4dbd-ad1b-150b7d72ddda.png)

**Branch Version**
Live

**Character Information**
Sai, unknown size

**Additional Information**
Ancestral Plains, clear weather after a fire

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
