### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by Rendezvousxx** [BoBAdministration/QA-Bug-Reports#106]
**Describe the Bug**
After a fire, the ash decals still show on top of the overlay for the saichania.

**To Reproduce**
1.  Logged into Dedicated Testing 1
2. Walked through the desert area on Rival Shores where a fire spawned
3. Left the area and after the fire ended, the ash decal still remained over the  model
4. Logged off safely and logged back in and still maintained the ash decal overlay

**Expected behavior**
I expected the ash decal to remain while the character remained within the reach of the fire area and then to lose the decal after the character moved out of the area that was experiencing the fire event.

**Actual behavior**
The Saichania continued to have the ash decal over its normal skin even after leaving the area and logging out safely and logging back in

**Screenshots & Video**
Attached below

**Branch Version**
Tester 
![u6IfomaDTyauK8lhKEmXeg](https://user-images.githubusercontent.com/96402225/146820957-16a928ec-62be-4def-8823-3f856f68cdfa.png)

**Character Information**
1.2 growth Saichania female, 3/3 combat full talent

**Additional Information**
Rival Shores (Desert), Fire Weather

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
