### ISSUE TITLE
Meeting example

### ISSUE THREAD

**Issue by AgentHawke** [BoBAdministration/QA-Bug-Reports#107]
**Describe the Bug**
The ash after wildfire is showing on the dinosaur model.

**To Reproduce**
1. Log into Dedicated Testing 1
2. Spawn a Saichania in the Jungle
3. Spawn a wildfire over an area (e.g. Jungle)
4. Go over burnt area (gray ashes on the ground)

**Expected behavior**
No ashes are shown on the dinosaur model when Sai walks over the burned area

**Actual behavior**
Ashes are showing on Sai model when Sai walks over burned area

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/96437591/146821018-8a70a009-5382-4330-ad84-c527c0381870.png)

**Branch Version**
Live

**Character Information**
Saichania 1.2

**Additional Information**
Map: Rival Shores, post-Wildfire

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
