### ISSUE TITLE
meeting example Pyro

### ISSUE THREAD

**Issue by ITechnicPyroI** [BoBAdministration/QA-Bug-Reports#108]
**Describe the Bug**
Dinosaurs who walk into the ash decal get the applied texture over the top of their main skin.

**To Reproduce**
- Log into the example server.
- Wait until a fire has burned through an area.
- Walk into the scorched area that the fire left.
- As soon as you walk in you should see that the texture applies over the dino, only when inside of it.

**Expected behavior**
The texture decal should stay along the surface of the ground and should not apply over the dino.

**Actual behavior**
When inside of the scorched decal the decal prioritizes itself and overshadows any of the dino's textures it's on top of while the dino is inside of the decal.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/48891088/146820940-ad570a26-4e3c-4667-be4b-abcf2eb14561.png)

**Branch Version**
Tester? Wasn't specified in the example prompt.

**Character Information**
Saichania Glimmer Skin, Adult, 1.2

**Additional Information**
Picture looks like AP, only happens while inside of a scorched area

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
