### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by Skyedrago** [BoBAdministration/QA-Bug-Reports#109]
**Describe the Bug**

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Spawn into a map
2. Spawn a fire
3. Allow the fire to burn for a few moments.
4. Put out the fire
5. Spawn in a sai
6. Walk as sai into the ash-covered area and confirm it happens with this creature
7. Raise and lower growth to different variables (.5, 1.0, 1.5, etc) to test if ash affects creatures at different sizes or it is a specific growth
8. Spawn in as a other dinos and test if ash affects them as well.
9. Test different growths and observe if it applies to them too.
10. Test effects of various weather conditions and if this affects whether ash covers the creature.
11. Test whether the same bug affects other maps (if available).

**Expected behavior**
Ash does not cover any dinosaurs, at any growth, and only appears on the ground.

**Actual behavior**
Ash covers sai (and other applicable creatures) under the various conditions tested.

**Screenshots & Video**

**Branch Version**
Live
<img width="571" alt="Screen Shot 2021-12-20 at 2 21 47 PM" src="https://user-images.githubusercontent.com/96404852/146821180-ba5c6888-d366-4a21-8bc0-786a70bc05ce.png">

**Character Information**
Sai, growth unknown. Talents, inherits, gender, and stats unknown. 

**Additional Information**
Rival Shores(?), sunny, small ash zone

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
