### ISSUE TITLE
broke Behavior When I turn the mouse slightly to the right or left

### ISSUE THREAD

**Issue by Ghoconley** [BoBAdministration/QA-Bug-Reports#11]
**Describe the Bug**
a little bit broken Behavior coah  When I turn the mouse slightly to the right or left

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. ex. Logged into Dedicated Testing 2
2. ex. Spawned in a Coah at winter
3. ex. just walk on coah
4. ex. happened broken Behavior coah 

**Expected behavior**
Correct behavior looking at the mouse

**Actual behavior**
broken Behavior coah  When I turn the mouse slightly to the right or left

**Screenshots & Video**
https://youtu.be/M9FdcdtfUnM

**Branch Version**
Tester 

**Character Information**
1.2 growth

**Additional Information**
---

**Comment by Predatoria** [comment]
This should be reduced next tester patch.  I turned down how fast the coah interps into its left / right banking animations, which is what you're seeing here.

**Comment by teatimejess** [comment]
Seems to be fixed! No issues when following steps.
