### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by Slicer1** [BoBAdministration/QA-Bug-Reports#110]
**Describe the Bug**
Ash decals left by fire show over top of a creature's model This is not supposed to happen!
**To Reproduce**
1. Log into Dedicated Testing 1
2. Spawn fire near rock at ml
3. Put out fire with rain
4. spawn Saichania on rock and walk around
5. Ash decals left on rock is covering Sais creature model

**Expected behavior**
Ash decal should be visible on rock and not on creature model

**Actual behavior**
Ash decals show on creature model 

**Screenshots & Video**
![billede](https://user-images.githubusercontent.com/96415370/146820974-ca8a7ec2-40c9-49ec-8dbd-d41ef9075bdf.png)

**Branch Version**
Testerbranch

**Character Information**
Saichania 1.2 default skin
**Additional Information**
Ancestral plains clear weather after fire

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
