### ISSUE TITLE
Meeting Example (Shadow Sen)

### ISSUE THREAD

**Issue by shadowsen13232** [BoBAdministration/QA-Bug-Reports#111]
**Describe the Bug**
Ash decals is appearing on top of the creature's model.

**To Reproduce**
1. Wait for a fire/spawn a fire.
2. Wait for the fire to dissipate.
3. In this scenario, it is a sarchania, so take that and walk it over the fallen ash.
4. Would need to try the same steps as above with another creature, to verify if its only the sarcha or other dinosaurs having the same issue.

**Expected behavior**
No fallen ash to be on top of the dinosaur models.

**Actual behavior**
Fallen ash covering the dinosaurs' model.

**Screenshots & Video**
![test image sarcha](https://user-images.githubusercontent.com/96442622/146820933-f36292a0-39ed-445e-bf36-1527b2d30bcc.png)

**Branch Version**
Tester.

**Character Information**
Looks to be about 0.8 or 1.0+ from the image.

**Additional Information**
Fire effects.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
