### ISSUE TITLE
Meeting example

### ISSUE THREAD

**Issue by Akaraasaur** [BoBAdministration/QA-Bug-Reports#112]
**Describe the Bug**
The ashes left by the fire are put on the creature's model.

**To Reproduce**
1. Logged into Dedicated Testing 1
2. Spawned as a shimmer saichania
3. Fire happened on the map
4. Walked into fire's ashes when fire is done
5. Ashes are visible on the creature's model instead of staying on the ground

**Expected behavior**
The ashes should remain only on the ground and not appear on the creature.

**Actual behavior**
Ashes appear on the creature's model

**Screenshots & Video**
https://media.discordapp.net/attachments/922324689177673778/922567776688803950/u6IfomaDTyauK8lhKEmXeg.png

**Branch Version**
Tester

**Character Information**
Shimmer saichania (spawn), female, 1.2 growth.

**Additional Information**
Dry storm with fire happening.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
