### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by KattofKits** [BoBAdministration/QA-Bug-Reports#113]
**Describe the Bug**
When approaching ash, instead of the ash appearing below the player model, the ash appears on top of the player model, making them appear a matted grey.

**To Reproduce**
1. Walk up to ash pile(s)
2. Walk into/over ash pile(s)
3. Observe if colors disappear and the player model is covered in ash texture.

**Expected behavior**
Player model clear of ash, walking normally over the ash, but not covered in it.

**Actual behavior**
The player model is covered in ash, hiding all of its colors, essentially masking it from its surroundings.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/90863811/146821225-4496ee0a-22a6-4c0a-ab06-ec0a02685ce4.png)

**Branch Version**
Meeting Example

**Character Information**
Saichania, shimmer skin.

**Additional Information**
After a forest fire has taken place, and only ash remains.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
