### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by Vallyhalla** [BoBAdministration/QA-Bug-Reports#114]
**Describe the Bug**
After a fire, there are ashes left on the ground that when you walk through them it blankets your creature.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 1
2. Spawned in a Sai at Jungle
3. Walked through the ash on the ground from a fire.
4. Ash covers the creature as well as the ground.

**Expected behavior**
Walk over the ash texture without it blanketing your creature, it stays glued to the ground texture.

**Actual behavior**
When I walk over/through the ash texture (burnt ground) the texture goes over my creature giving it the effect the ash has on the ground.

**Screenshots & Video**
See attached.

**Branch Version**
First discovered on the Live branch, tested it on the QA Test server.

![u6IfomaDTyauK8lhKEmXeg](https://user-images.githubusercontent.com/96442596/146820771-c64a410a-a7d8-4510-9519-55253170bc19.png)

**Character Information**
Sai, growth set to 1.2.

**Additional Information**
Happened on the grass, unsure if it does it if the ash has covered other textures. (Sand, rock etc...)

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
