### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by DevTamara** [BoBAdministration/QA-Bug-Reports#115]
**Describe the Bug**
It would appear that the decal left by fire are showing over the top of the creature's model, and I cannot see the creature's skin decal.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 1
2. Logged in a Sai
3. Fire happened
4. Walked through burned area
5. Skin was covered by ash decal

**Expected behavior**
I expected to see my Sai's skin

**Actual behavior**
Skin disappears and is hidden by ash decal from fire.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/96442251/146820990-f264e1fe-740d-483b-9ce7-86ece9417c3b.png)

**Branch Version**
Tester Branch

**Character Information**
Nested growth 1.1 Sai

**Additional Information**
Cloudy/clear weather, area was freshly burned by fire, fire still burning nearby

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
