### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by Genshai** [BoBAdministration/QA-Bug-Reports#116]
**Describe the Bug**
Ashes decals goes onto Dino

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Find burned ground with ashes.
2. Walk onto the burned ground with ashes.
3. Ashes gets applied to the Sai's Skin.

**Expected behavior**
Nothing more than running through some ashes without your skin changes.

**Actual behavior**
As you run into the ash the decal/texture of the ashes gets applied on the dino as you walk in the ash.

**Screenshots & Video**
![u6IfomaDTyauK8lhKEmXeg](https://user-images.githubusercontent.com/96436175/146821455-f4cc3386-4be4-4d3a-be54-c352da7d39ec.png)

**Branch Version**
Live.

**Character Information**
1.2 Sai 

**Additional Information**
AP map nearby Great lake.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
