### ISSUE TITLE
meeting example

### ISSUE THREAD

**Issue by Silemara** [BoBAdministration/QA-Bug-Reports#117]
**Describe the Bug**
Ash decal sitting on top of creature when walking through ash area

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
 Logged into Dedicated Testing 1, spawning as .4 sai in forest. Fire has burnt through the area. Walk onto ash decal areas. Creature skin then gets covered by ash

**Expected behavior**
should not be covered in ash

**Actual behavior**
skin with exception of shimmer gets covered in ash effect when walking on ash areas

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/96402288/146821545-8a632a07-0e1d-4326-b654-a168f12286c9.png)

**Branch Version**
Test

**Character Information**
fresh spawn .4 sai female

**Additional Information**
Rival Shore map, active fire as despawned

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
