### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by finchye** [BoBAdministration/QA-Bug-Reports#118]
**Describe the Bug**
When ash decal is left on the ground from a passing fire, dinos that stand on top of the ash will be covered in ash.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 1
2. Spawned in a Sai at River
3. Spawned fire.
4. Waited for the fire to pass to create ash.
5. Stood in the ash as my current dino to be covered in ash.

**Expected behavior**
Dinos are supposed to be able to stand on top of ashes without being covered in ash.

**Actual behavior**
Dinos that walk upon ash become covered in ash, hiding their skin.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/96402401/146821437-695dab13-5f68-466e-83e9-c330d44e486d.png)

**Branch Version**
Live.

**Character Information**
Dino was 1.2 with shimmer skin.

**Additional Information**
AP, Clear before and after spawn fire.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
