### ISSUE TITLE
Aqua Affinity not affecting Dart for Mosa and Elasmo like how it does for other semi-aquatics.

### ISSUE THREAD

**Issue by Radiun** [BoBAdministration/QA-Bug-Reports#12]
The testing was done all with 1.32 dinos with no Inherits. 
Test used 3/3 Improved Dart or 3/3 Swift Flippered at all times.

![](https://cdn.discordapp.com/attachments/790891651631022100/877856228536098856/unknown.png)

![](https://cdn.discordapp.com/attachments/790891651631022100/877856454315474994/unknown.png)

**Comment by BoBAdministration** [comment]
Bug does not follow format. Closing this so it can be resubmitted with proper format.
