### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by puppyponn** [BoBAdministration/QA-Bug-Reports#120]
**Describe the Bug**
Ash decals left by fire cover a creatures model.

**To Reproduce**

1. Fire is needed.
2. Spawn in as Saichainia.
3. Fire has gone out.
4. Walk where the fire has occured in 
5. Ash covers creature's model.

**Expected behavior**
A model should be able to walk inside the ash without model being covered. 

**Actual behavior**
While walking in the ash the creature model is covered in ash decals. 

**Screenshots & Video**
![u6IfomaDTyauK8lhKEmXeg](https://user-images.githubusercontent.com/96402215/146821131-211680ca-d585-4c07-bc44-8210162b9628.png)

**Branch Version**
Tester 

**Character Information**
1.2 Saichania, Pure speed

**Additional Information**
Ancestral Plains, after fire.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
