### ISSUE TITLE
Meeting example 

### ISSUE THREAD

**Issue by Vivirowen** [BoBAdministration/QA-Bug-Reports#121]
**Describe the Bug**
The Sai caught on fire and the ashen texture visibly over the Sais skin.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1.log into dedicated testing 1 
2.Sai must have Shimmer skin
3.Sai must be .8 growth 
4.Lightning strike the Sai
3.Catch sai on fire

The Sai should not have the ashen texture over its skin after the fire goes out.

**Actual behavior**
A clear and concise description of what actually happens.

![u6IfomaDTyauK8lhKEmXeg](https://user-images.githubusercontent.com/96412314/146821732-3767d89d-dce1-4abe-aeaa-50ebb664d5f3.png)

**Branch Version**
Tester 

**Character Information**
Spawned in shimmer sai with red glow, growth .8

**Additional Information**
Ancestral Plains, Storming, Dry lightning.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
