### ISSUE TITLE
Meeting Example!

### ISSUE THREAD

**Issue by EkkoEctasy** [BoBAdministration/QA-Bug-Reports#122]
**Describe the Bug**
Ash decals from in-game wildfires overlapping dinos. (after the fire)

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logging on Dedicated testing 1 server. 
2. Logged in as sai (same creature as shown on the picture)
3. Used an admin spawned storm (wildfire) and let this generate & complete.
4. After the fire has passed [x] location, walked over 'ash decals'
5. Resulted in ash decals moving over the dino, overlapping the skin.

**Expected behavior**
Expected it to be moving underneath the creature, sticking to the ground mesh. 

**Actual behavior**
The ash decals were both on the creature and on the ground mesh. Taking over the dino's skin. 

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/96417223/146821561-d2ca16ec-21af-4773-a1bf-ea018c0be2d9.png)

**Branch Version**
Live version

**Character Information**
/

**Additional Information**
Map: Ancestrial plains
Weather: Natural disaster -> Wildfire (fire)

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
