### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by Rehlik** [BoBAdministration/QA-Bug-Reports#123]
**Describe the Bug**
Ash decals left by fire show up over show up over a creature's model.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 1
2. Spawned in an Ory at Jungle
3. Spawned/found the nearest ash texture and proceeded to walk over the ash texture and immediately noticed the texture was going over my creature's skin.
4. Tried multiple different skins to identify if it was just one skin, or all creature skins. Found it to happen with all skins and color variations.
5. Swapped to all other creature's to ensure it wasn't just one creature having the issue. Found that it is happening to all skins and creatures.
6. Tested different graphics settings (low/medium/high/etc.) and found the bug only happened on low settings.
7. Tested with my laptop with a different graphics card (ati) from my main PC(nvidia)and found the issue existed on all card setups available to me.

**Expected behavior**
Ash should not cover the texture of any creature. 

**Actual behavior**
Upon walking over the texture my creature's texture is immediately covered by the ash texture.

**Screenshots & Video**
![example](https://user-images.githubusercontent.com/96402503/146821704-d48de68f-4614-4f0a-a45f-7a88e67136ff.png)

**Branch Version**
Tester

**Character Information**
All creature's and skins were tested to ensure it wasn't just a particular skin/creature.

**Additional Information**
Checked all weather types, maps, and time of day settings.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
