### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by Martholomeus** [BoBAdministration/QA-Bug-Reports#124]
**Describe the Bug**
Ash decals can cover a players' creature.

**To Reproduce**
Unknown for sure, possibly:
1. Spawning a fire, wait for ash textures to spawn
2. Walk creature over the ash decals.
3. Wait for texture to cover creature.

**Expected behavior**
Ash textures after a fire should only cover the ground.

**Actual behavior**
Ash are appearing over creatures.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/70067153/146821073-26b88854-15df-4446-8980-1a561fe9a197.png)

**Branch Version**
Live.

**Character Information**
Saichania, 1.2 growth

**Additional Information**
Ancestral Plains, clear weather after a fire.

(Grantma#9071)

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
