### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by AbyssakaAngel** [BoBAdministration/QA-Bug-Reports#125]
**Describe the Bug**
Ash texture is showing along the model as it passes through the burnt zones.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.

Log into any server
Spawn in as any sized creature
Start/locate a fire
Walk along the already burnt zones

**Expected behavior**
The ashes texture should stay along the ground in the burnt zones.

**Actual behavior**
The ashes texture transfers onto the creatures model when walking within the burnt zones.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/96443523/146821716-e978a920-f867-4854-99dc-6f693cfa26f6.png)

**Branch Version**
Both

**Character Information**
1.0 shimmer male saichania, full stats, no bias or additional buffs or de-buffs. 

**Additional Information**
AP map clear weather with an active fire, nearby foliage was all burned away.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
