### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by GlossyGamer** [BoBAdministration/QA-Bug-Reports#126]
**Describe the Bug**
After a fire has ended, the ash decals continue to show on top of the overlay of the Saichania.

**To Reproduce**

1. Logged into a public server.
2. Entered River where a fire was raging.
3. Left the area and returned when the fire ended. The ash decal remained to cover the Saichania.
4. Logged out and logged in safely, the ash decal remained.

**Expected behavior**
I expected the ash decal to remain while the character remained within the reach of the fire area and then to lose it when I logged out or left the rendering distance. 

**Actual behavior**
The creature continued to have the ash decal overtop of its own skin, even after leaving the area and logging in and out safely.

**Screenshots & Video**
Attached

**Branch Version**
Live

**Character Information**
1.2 growth Saichania

**Additional Information**
Rival Shores, Fire weather

![Sai example](https://user-images.githubusercontent.com/26982447/146826341-97c2cf7a-7d7f-4987-a192-dee5dd00b62a.png)

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
