### ISSUE TITLE
Meeting Example 

### ISSUE THREAD

**Issue by themurdock13** [BoBAdministration/QA-Bug-Reports#127]
**Describe the Bug**
ash decals left by fire show over the top of a creature's model. This is not supposed to happen!

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. ex. Logged into Dedicated Testing 1
2. SpawnFire
3. SetWeather to rain to remove fire after forest is gone
4. Walk through the burnt / ash  spots left by the fire
5. test with different creatures to see what creatures cause this issue 

**Expected behavior**
Ash mesh layer hovers above the character model 

**Actual behavior**
the player walks through high spots of the ash spots and there is a mask layer that applies to the player model 

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/74908355/146825254-93be0bb5-5026-43fb-99d3-00543444ece0.png)

**Branch Version**
Tester--.

**Character Information**
Sai growth lvl 1.0 

**Additional Information**
Ancest plaines ,  on Mtn Lake

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
