### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by Macarani123** [BoBAdministration/QA-Bug-Reports#128]
**Describe the Bug**
Ash patches left behind by an extinguished fire, overlay their texture on any part of a dino that is above the patch.

**To Reproduce**
1. Spawn in as any dino.
2. Travel to a recently burned location with persisting ash patches.
3. Walk over the persisting patches of ash on the ground.
4. Ash texture overlays on the dino model as you walk into it, glow layers show through this texture.

**Expected behavior**
Ash should remain on the ground instead of climbing up the dino like some sort of symbiote.

**Actual behavior**
The ash texture from the persisting patches, overlays on the dino that stands on it or over it.

**Screenshots & Video**
![u6IfomaDTyauK8lhKEmXeg](https://user-images.githubusercontent.com/96443517/146827712-e596796e-fd5c-408b-a78f-359b13374e33.png)

**Branch Version**
Live

**Character Information**
Nested shimmer sai. 1.0 growth.

**Additional Information**
Ancestral Plains, remnants of a forest fire.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
