### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by Ihmislehma** [BoBAdministration/QA-Bug-Reports#129]
**Describe the Bug**
As a Sai, when standing on a burned ground texture, burned ground texture layers over Sai. Uncertain if this will affect other playables. 

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. ex. Logged into Meeting Example Server
2. ex. Spawned as 1.2 Saichainia
3. ex. Observed fire from a relatively close distance, when it extinquished on it's own walked over to it
4. ex. Walking into the burned ground texture, the texture layers over the Saichania I was playing as. Observer texture "move over" the Sai as it moves, and not with the Saichainia. Leaving the burned area drops the burned effect from the Saichania.

**Expected behavior**
Burned ground texture to not affect playables within it's area

**Actual behavior**
Burned ground texture layers on top of played Saichainia

**Screenshots & Video**
Added screenshot of effect

**Branch Version**
Tester

**Character Information**
1.2 Saichania, no talents

**Additional Information**
Ancestral Planes, Dry Lightning, short lived small fire
![u6IfomaDTyauK8lhKEmXeg_png](https://user-images.githubusercontent.com/29692166/146827775-db4ecd63-a6e8-43bc-be2d-2d2867f0caec.png)

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
