### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by SweetLilYuleCat** [BoBAdministration/QA-Bug-Reports#130]
**Describe the Bug**
Fire ash is left ontop of sai model

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into ancestrial plains map
2. Spawned in jungle near the ocean during a fire
3. Ran towards the edge of the ocean 
4. As I ran from jungle to the ocean I passed a large rock near 3 Salt crystals, there was ash everywhere and as I passed the rock I got covered in the ash

**Expected behavior**
I expected to have my feet and some spots covered in a dusty ash texture from running through it.

**Actual behavior**
My entire sai was covered and you can see a white outline right above the ash which is also quite blurry and smudged.

**Screenshots & Video**
![Screenshot_20211220-144623_Discord](https://user-images.githubusercontent.com/96404685/146830642-5944226f-3858-42de-95cf-447ffb29ca21.jpg)

**Branch Version**
Live.

**Character Information**
SAI GROWTH: 1.4
SAI INHERITS/POINTS: All combat with +1 inherits in gp, +2 in aqua infinity, and +1 weather resistance 

**Additional Information**
Ancestrial plains (Noobz server 2)
Server crashed
Dry lightning storm

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
