### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by muffinnuke** [BoBAdministration/QA-Bug-Reports#131]
**Describe the Bug**
When walking onto burnt area after forest fire,  Ash/burnt ground texture appears on-top of character model. 

**To Reproduce**
1. Logged into Dedicated Testing 2
2. Spawn in as 1.0 Saichania
3. Walk into ash textured area destroyed by forest fire. 
4. Ash texture appears to cover atop of character model base texture.
5. Leaving area effected by ash texture, reverts effect.

**Expected behavior**
Walking into areas effected by forest fires WOULD NOT display ash texture on top of character. Texture would remain on properly effected areas (ie. ground, trees, etc.) 

**Actual behavior**
Walking into areas effected by forest fires WOULD display ash texture on top of character. Aswell as, expected effected areas (ie. ground, trees, etc.) 

**Screenshots & Video**
![AF9BE05D-8FC8-4FD5-9BDE-A1EB44DF798E](https://user-images.githubusercontent.com/83020002/146827670-127dcd3b-61b5-424f-af88-6ed15f237c1a.png)

**Branch Version**
Tester

**Character Information**
Dino: Saichania 
Growth: 1.0 

**Additional Information**
Rival Shores -> After forest fire

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
