### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by theonlyRaw** [BoBAdministration/QA-Bug-Reports#132]
**Describe the Bug**
Ash textures overlap dinosaur model after wild fire.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 1
2. Spawned in as Saichania at Forest Island
3. Spawn wild fire near Saichania.
4. Bring Saichania over ashy area where fire had been.

**Expected behavior**
Expectation should be ash texture should **not** touch dinosaur model or lay over top the model.

**Actual behavior**
Ash texture lays over top the dinosaur model.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/54249603/146832579-856e5ef6-5b25-4df3-a8a7-4bbd4f628def.png)

**Branch Version**
Live.

**Character Information**
Saichania 1.2

**Additional Information**
Rival Shores map - after wild fire.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
