### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by JusttynG** [BoBAdministration/QA-Bug-Reports#133]
**Describe the Bug**
After a fire, when walking over ash the ash textures show as your skin.

**To Reproduce**
Log on to Dedicated Testing 1, spawn as Sai, after a fire has burnt through the area walk over ash textures. Creature skin is now shows as ash textures.

**Expected behavior**
when walking over the ash the creatures skin should not be mapping the ash textures.

**Actual behavior**
When moving over the ash textures the creatures skin is changed to the ash textures.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/96445354/146833135-d9571412-a6bf-4d3a-9f50-f06d04ab26e2.png)

**Branch Version**
Testing.

**Character Information**
Nested pink shimmer Sai , growth .6, female, all speed talents, thirsty. water 12%, food 78%, bias 4.8, comfort 46.

**Additional Information**
Ancestral Plains, fire caused by dry lightning.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
