### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by FadedSage** [BoBAdministration/QA-Bug-Reports#134]
**Describe the Bug**
Ash decal from fire, over-layering on a creature's skin when walking through it

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log onto server
2. Spawn on any creature, in my scenario it is a Sai
3. Force grow to 1.0 or larger for better visual change
4. Spawn a fire 
5. Let spread for about 5 minutes
6. Set weather for heavy rain to put out fire
7. Set weather to clear
8. Set time to daytime for clarity
7. Go to a patch of ash
8. Walk through it
9. The ash decal then appears as an over layer on the dino's skin 

**Expected behavior**
The Burned texture should not overlap onto a player's skin and should remain only on the ground that was burned.

**Actual behavior**
After walking over the charred area, the Ash Decal hovers onto of the creature's skin until you leave the visible texture line it's on.

**Screenshots & Video**
https://cdn.discordapp.com/attachments/922324689177673778/922567776688803950/u6IfomaDTyauK8lhKEmXeg.png

**Branch Version**
Live

**Character Information**
Any creature, any growth, 1.0 and over is easiest to see the occurrence.

**Additional Information**
After fire hazard has passed and all the remains is the ash terrain.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
