### ISSUE TITLE
Meeting example

### ISSUE THREAD

**Issue by Revstiel** [BoBAdministration/QA-Bug-Reports#135]
**Describe the Bug**
When a saichania walks in ash, the ash overlays on top of the dino.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log in to saichania.
2. Go to where a fire has recently been put out
3. Walk over  a patch of ash.
4. Observe, the ash will be overlayed on the saichania.
5. Upon leaving the ash, this temporary affect seems to go away until you walk back in the ash again.

**Expected behavior**
When a saichania or any dinosaur walks over ash. It should not affect their appearance. 

**Actual behavior**
The ash transfers on top of the saichania when you walk over the ash, causing it to create a temporary overlay affect.

**Screenshots & Video
![146827775-db4ecd63-a6e8-43bc-be2d-2d2867f0caec](https://user-images.githubusercontent.com/96402095/146840611-8967f64d-ea5b-435b-a717-628c74d15369.png)

**Branch Version**
Tester

**Character Information**
Dinosaur: Saichania
Growth: 1.0

**Additional Information**
Fire is required to replicate this bug. Was done on Ancesteral Plains map.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
