### ISSUE TITLE
Ory Burrow light effect outside of burrow

### ISSUE THREAD

**Issue by Silemara** [BoBAdministration/QA-Bug-Reports#136]
**Describe the Bug**

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Live Server (Rebirth) RS map
2. spawned in as 1.16 nested glimmer ory
3. Entered burrow for salt
4. Exit burrow, burrow lighting in effect

**Expected behavior**
exit burrow and in game lighting should go from burrow limited view lighting effect without vigilance to full lighting/view

**Actual behavior**
Bug appears inconsistent, exit the burrow and burrow lighting effect remain in place upon exiting the burrow, the effect remains until re-entering the burrow animation where it reverts back to standard lighting

**Screenshots & Video**

![image](https://user-images.githubusercontent.com/96402288/146843643-b8bc3a03-b61b-4641-bc74-9fa4530ceacd.png)

**Branch Version**
Live branch

**Character Information**
1.16 Ory, nested, no points in vigilance 

**Additional Information**
Rival Shores map, Top of forest water fall

**Comment by Predatoria** [comment]
I believe I fixed this a while back and forgot to close this.
