### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by Soapx91** [BoBAdministration/QA-Bug-Reports#137]
**Describe the Bug**
The ash decals that are left by fires, show over top of player creature models when walking or standing over it. 

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Server
2. Spawned in as a Sai
3. Saw a fire dissipating 
3. Found ash on the ground left from a fire
4. Walked over to the ash on the ground
5. When walking over the ash, the ash shows up over my creatures model

**Expected behavior**
Ash should only be overlaid on the ground, and not overtop of the creature model

**Actual behavior**
When walking over ash on the ground, the ash is displayed overtop of the creature model walking over the ash. 

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/73155134/146852645-1c236ce0-1675-4411-815b-2fcfcd707603.png)

**Branch Version**
No information given with screenshot provided

**Character Information**
Dinosaur growth and type. Include any other relevant character information such as talents, inherits, gender, and stats if necessary.
Dino Growth: N/A
Dino Type: Saichania

**Additional Information**
Map type, weather, or any other context about the problem here.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
