### ISSUE TITLE
Falling into a hole inside of the shrines.

### ISSUE THREAD

**Issue by finchye** [BoBAdministration/QA-Bug-Reports#138]
**Describe the Bug**
There seems to be a missing area on the right side of the shrine which can cause players that are small enough to fall underneath shrines.

**To Reproduce**
1. Logged into Dedicated Testing 3.
2. Spawned as an Acro.
3. Teleported to a shrine.
4. Setgrowth to 0.3
5. Walked up the right side of the shrine and into the hole.

**Expected behavior**
Should be able to walk up the shrine without being trapped underneath it.
**Actual behavior**
When something that is the similar size or smaller growth than a 0.3 Acro, they can fall into a hole on the right side of the shrine.

**Screenshots & Video**
https://www.youtube.com/watch?v=Hgtn3DxVWNo&ab_channel=finch
**Branch Version**
Both Tester and Live.

**Character Information**
Dino was a 0.3 acro, also work with any smaller sizes.

**Additional Information**
AP.

**Comment by tinystarpaws** [comment]
Please remember to post the written coordinates whenever you submit map bugs! <3

Coords: -84740 -82002 5079
Located on AP

**Comment by Vallyhalla** [comment]
This still isn't fixed, confirmed by the testers. There's one on each side. Happens on all of the shrines!

**Comment by Predatoria** [comment]
I can reproduce this.  I'm going to send it to Soals.

**Comment by Soals** [comment]
simplified collision had a hole, I fixed it

**Comment by WayaShinzui** [comment]
Hole is gone! The smalls can walk safely.
