### ISSUE TITLE
Meeting Example.

### ISSUE THREAD

**Issue by KayFeral** [BoBAdministration/QA-Bug-Reports#139]
**Describe the Bug**
After a fire occurs and the ashes are left, they show over the dinosaur's model.

**To Reproduce**
Steps to reproduce the behavior in detail.
1. Logged into Testing 1
2. Spawned as a saichaia and grow it to 1.2
3. Started a light fire and let it spread for a couple minutes
4. stopped the fire making it rain then stopped the rain
5. walked through the ashes.

**Expected behavior**
The dinosaur remains the same and is able to walk over the ashes without changes

**Actual behavior**
The ashes appear over the dinosaur and override it's skin, acting as if they were the skin.

**Screenshots & Video**
https://tinyurl.com/2vy93f4y

**Branch Version**
Tester

**Character Information**
Saichaia at 1.2 growth

**Additional Information**
Fire and rain were forced for testing purposes in order to not wait for a fire to spawn in.
Also happens with Natural fires / not forced.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
