### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by skullyzs** [BoBAdministration/QA-Bug-Reports#141]
**Describe the Bug**
 Ash overlapping the players dinosaur skin when walking through or standing in. 

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1.  Logged into Live server
2.  Spawned in a Saichania at Mountain Lake near bridge 
3.  Walked onto ash 
4.  What happened was Ash lapped over the Saichania's skin

**Expected behavior**
When walking over ash and or standing in it there should have been no glitching/overlap of any part of the players dino skin. Should have the players dino skin fully showing when standing/walking on it.

**Actual behavior**
When the player stood on the ash it completely covered the top part of the dinosaur's skin making it look ashy as well, the bottom half of the dinosaur was fine and showed its glim. 

**Screenshots & Video**
![u6IfomaDTyauK8lhKEmXeg (1)](https://user-images.githubusercontent.com/96402084/146877376-b8bd0723-5ade-4db3-8531-98e5ce65d17a.png)

**Branch Version**
Live

**Character Information**
Sai - Around 1.2 growth - Shimmer skin - 

**Additional Information**
Ancestral Plains - Clear skys/weather - fire still going in the background -

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
