### ISSUE TITLE
Enter a one-line concise summary.

### ISSUE THREAD

**Issue by Skyedrago** [BoBAdministration/QA-Bug-Reports#143]
**Describe the Bug**
While swimming, moving your camera up from underwater allows you to see the outline of land highlighted ahead of you.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log into a server with Ancestral Plains
2. Choose a random dino
3. Swim out to sea
4. Move camera underwater.
5. Quickly move camera above water. Alternatively, leave camera close to the surface.
6. Land will be highlighted either light colors or bright cyan color, making it easily visible in deep fog.

**Expected behavior**
Land should not be visible in foggy conditions.

**Actual behavior**
Land is visible even in heavy fog where it shouldn't be visible.

**Screenshots & Video**
![20211221023339_1](https://user-images.githubusercontent.com/96404852/146891802-863532cf-145b-4a95-ba68-29f74dd366fd.jpg)
![20211221023349_1](https://user-images.githubusercontent.com/96404852/146891805-6116d746-f15d-40c0-b4ec-cef426ce645c.jpg)

**Branch Version**
Live

**Character Information**
Character growth, build, and stats are irrelevant. Appears to occur on all dinos.

**Additional Information**
Especially noticeable in foggy conditions. Does not seem to work for fresh water.

**Comment by tinystarpaws** [comment]
This will not be fixed; limitation of the shader/water effects.
