### ISSUE TITLE
RS under mapping for small creatures. Desert cave on the shoreline.

### ISSUE THREAD

**Issue by IsJoshIE** [BoBAdministration/QA-Bug-Reports#147]
**Describe the Bug**
Near the location shown in my video on desert, there is a small section in between rocks above the desert cave entrance facing pt tower/jungle that you can walk through. This can be abused to have easy safe growth or to escape being hunted and also allows you to go underneath the map. Cords are 144250 188027 5315.

**To Reproduce**
1. Log on to Dedicated Testing 2.
2. Spawn as a Velo or Ory.
3. Teleport to 144250 188027 5315.
4. Set growth to 1.2
5. Walk through the opening shown in my video and screenshots.

**Expected behavior**
I expected the terrain to stop me from being able to walk through the wall allowing me to get under the map.

**Actual behavior**
I was able to walk straight through the wall that should normally have collision to stop you.

**Screenshots & Video**
![location](https://user-images.githubusercontent.com/96402089/146955230-5c13ef32-2789-42d5-baad-be2168831528.png)
https://youtu.be/j6H_G8Xjn1w

**Branch Version**
Live and Tester.

**Character Information**
Velo and Ory at .5 growth. (Can also fit when at 1.2 growth but I didn't have access to admin commands on the RS Dedicated Testing 2 server to test it for the video)

**Additional Information**
Rival Shores.

**Comment by Dinorunp** [comment]
still not fixed
