### ISSUE TITLE
Undermapping spot on ancestral plains

### ISSUE THREAD

**Issue by Slicer1** [BoBAdministration/QA-Bug-Reports#148]
**Describe the Bug**
Its possible to swim through textures and undermap at the spot on ancestral plains map at coordinates X=37611 Y=105561 Z=105

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into dedicated testing 3
2. Spawned any aquatic or semi aquatic creature up to 1.2 
3. teleport to coordinates on picture and swim through a hole in the textures
**Expected behavior**
Textures are supposed to block me from swimming through and undermap

**Actual behavior**
Its possible to swim right through and stay undermapped 

**Screenshots & Video**
![billede](https://user-images.githubusercontent.com/96415370/146961067-8e27f63e-8196-492f-b8d7-3ee80f99d4ad.png)

**Branch Version**
Testerbranch

**Character Information**
Any aquatic and semi aquatic creature at growth 1.2 can enter. 

**Additional Information**
Ancestral plains map

**Comment by Vallyhalla** [comment]
A 3.0 Icthy can fit through

**Comment by Predatoria** [comment]
Put rocks in way
