### ISSUE TITLE
Under mapping spot on Rival Shores 4566 265424 351

### ISSUE THREAD

**Issue by teatimejess** [BoBAdministration/QA-Bug-Reports#15]
**Describe the Bug**
Under rmapping on Rival Shores

**To Reproduce**
1. Log into Rival shores on any pawn
2. TeleportAt 4566 265424 351

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/77513445/130312777-53f6a028-11eb-45ab-889c-d519dec675d8.png)

**Branch Version**
Live

**Character Information**
N/A

**Additional Information**
Spot is underwater.

**Comment by Predatoria** [comment]
fixed

**Comment by teatimejess** [comment]
Confirmed fixed.
