### ISSUE TITLE
Footsteps are not shoving and footsteps sounds sound muffled on Ancestral plains

### ISSUE THREAD

**Issue by Slicer1** [BoBAdministration/QA-Bug-Reports#151]
**Describe the Bug**
It appears that dinos do not leave footprints on sandy area on ancestral plains in low tide and footsteps sound are played muffled

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged in to dedicated testing 3
2. Spawned in on Acrocantosaurus or Parasaurolophus
3. Forcegrow to 1.2
4. Wait till its low tide
4. Walked to these cords X=48680 Y=-119404 Z=2589

**Expected behavior**
Creatures should leave footprints on sandy area and play sandy area footstep sounds

**Actual behavior**
No footsteps are left behind and footsteps sounds play muffled

**Screenshots & Video**
Screenshot
![billede](https://user-images.githubusercontent.com/96415370/146985888-baf6e873-a1d4-4d59-a8b1-1cbfd6812604.png)
Video
https://youtu.be/hd59vrjSlCE

**Branch Version**
Testerbranch

**Character Information**
Tested with Acrocantosaurus and Parasaurolophus at 1.2 growth 

**Additional Information**
Ancestral plains canvas map at low tide in clear weather

**Comment by Predatoria** [comment]
fixed it!
