### ISSUE TITLE
Certain Foliage Item Crashing Server Upon Erasing

### ISSUE THREAD

**Issue by Macarani123** [BoBAdministration/QA-Bug-Reports#153]
**Describe the Bug**
The Foliage item ![20211221161021_1](https://user-images.githubusercontent.com/96443517/147006047-cc7b3d92-1b51-418f-81c8-aa9921e77538.jpg) causes a server crash upon attempting to delete or erase the placed item.

**To Reproduce**
1. Spawned in as an ory (can be any dino)
2. Use the command EnterSpectate and open the foliage editor. 
3. Locate the 
![20211221161021_1](https://user-images.githubusercontent.com/96443517/147006047-cc7b3d92-1b51-418f-81c8-aa9921e77538.jpg)
foliage item and spawn one or two in.
4. Select the eraser tool and attempt to erase said foliage item. 
5. Server proceeds to crash.
6. Using deleteall at the bottom of the UI also causes a crash

**Expected behavior**
Items (the cursed coral item) in the foliage editor should be easily erased and deleted without causing instant server crashes.

**Actual behavior**
The coral item causes the server to crash upon attempting to erase or delete it.

**Screenshots & Video**
![20211221161021_1](https://user-images.githubusercontent.com/96443517/147006248-64413ae2-f7f6-418e-ac0f-ec44358883f6.jpg)
![20211221161621_1](https://user-images.githubusercontent.com/96443517/147006291-0d10da18-7227-408d-ae48-9de3bdfbcb9a.jpg)

I managed to erase the other items in the picture with ease, they did not crash the server. I erased them one by one, and only when deleting the coral last, it crashed.
**Branch Version**
Live

**Character Information**
N/A as this is not a dinosaur glitch.

**Additional Information**
Forest island, non-canvas map.

**Comment by Predatoria** [comment]
These were removed from the tool
