### ISSUE TITLE
Velo cannot climb objects that are placed.

### ISSUE THREAD

**Issue by finchye** [BoBAdministration/QA-Bug-Reports#157]
**Describe the Bug**
Velo cannot climb on placed object using the new admin panel.

**To Reproduce**
1. Logged on Live Testing Open Console.
2. Spawned in as a 0.4 velo.
3. Set growth to 1.2.
4. Entered spectate.
5. Spawned in any object that a velo should be able to climb on.
6. Left spectate.
7. Attempted to climb on object, to which I could not.

**Expected behavior**
Should be able to climb on objects placed by an admin.

**Actual behavior**
Objects cannot be climbed on that are placed as admin.

**Screenshots & Video**
https://www.youtube.com/watch?v=HTtVc_c4jKI&ab_channel=finch

**Branch Version**
Live.

**Character Information**
1.2 spawn velo.

**Additional Information**
BB_Test_Map.

**Comment by Vallyhalla** [comment]
This has been fixed!
