### ISSUE TITLE
Gores fall through placed objects.

### ISSUE THREAD

**Issue by finchye** [BoBAdministration/QA-Bug-Reports#158]
**Describe the Bug**
When gore is dropped on placed objects via admin panel, it does not sit on the object, and instead goes through.

**To Reproduce**
1. Logged on Live Testing Open Console.
2. Spawned in as a 0.4 meg.
3. Set growth to 1.2.
4. Entered spectate and spawned any object that could be stood on.
5. Left spectate.
6. Spawned any size gore that was carryable.
7. Picked up gore and stood upon the object.
8. Dropped gore to find that it goes under the object.

**Expected behavior**
Gore should be able to be above placed objects, via admin panel.

**Actual behavior**
Gore goes under placed objects via admin panel.

**Screenshots & Video**
https://www.youtube.com/watch?v=1rfVund8_qI

**Branch Version**
Live.

**Character Information**
1.2 spawn meg.

**Additional Information**
BB_Test_Map.

**Comment by Vallyhalla** [comment]
This has been fixed!
