### ISSUE TITLE
Megaraptor - While using backwards jump and drinking continues drinking animation

### ISSUE THREAD

**Issue by Soapx91** [BoBAdministration/QA-Bug-Reports#160]
**Describe the Bug**
While drinking water as a Megaraptor, when you use your backwards jump ability while drinking water. The drinking water animation continues but you are still thrown backwards. 

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into dedicated testing 2
2. Spawned in as a Megaraptor
3. Drank from lake in Jungle
4. Pressed my use ability key button, and got thrown back in the drinking animation (Note: drinking does stop)

**Expected behavior**
When drinking water, and using the megaraptor backwards jump, the animation for drinking should stop, or you shouldn't be able to use the ability while drinking

**Actual behavior**
When drinking as a megaraptor and using the backwards jump ability, you continue the drinking animation as you jump backwards

**Screenshots & Video**
(https://youtu.be/i2RXuHpNHZg)

**Branch Version**
Test Branch

**Character Information**
Dino: Megaraptor
Growth: 0.639

**Additional Information**
Rival Shores

**Comment by Vallyhalla** [comment]
This is now fixed, it cancels megaraptor drinking.
