### ISSUE TITLE
Tab no longer cycles through chat windows

### ISSUE THREAD

**Issue by theriversedge** [BoBAdministration/QA-Bug-Reports#162]
**Describe the Bug**
Pressing the Tab key no longer cycles through chat windows, it simply closes the in-game chat box

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged onto Official 2 East US
2. Opened the chat box
3. Pressed Tab to cycle through chats
4. Chat box closed

**Expected behavior**
Pressing the Tab key cycles through chat windows

**Actual behavior**
Pressing the Tab key closes the in-game chat box

**Screenshots & Video**
N/A

**Branch Version**
Live

**Character Information**
N/A

**Additional Information**
N/A

**Comment by teatimejess** [comment]
Currently works for me, may need more specific reproduction? 🤔

**Comment by Zer0Health** [comment]
Found this issue as well while in spectate, not being able to tab to cycle through chats: https://youtu.be/LoW-ys2ZjqI
