### ISSUE TITLE
Tree is pickupable infinitely

### ISSUE THREAD

**Issue by Alyrius** [BoBAdministration/QA-Bug-Reports#165]
**Describe the Bug**
This tree on the forest island map can be picked up infinitely example tree at X: -1955 y:-139121 z: 8329
This is a tree already on the map. Appearently there are multiple such trees in the foliage spawner itself, however I have not been able to find them (perhaps removed with update? https://media.discordapp.net/attachments/605979793716019205/923182342032486430/Screen_Shot_2021-12-22_at_6.56.33_AM.png?width=799&height=676)

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. ex. Log into forest island
2. ex. spawn a herbivore
3. ex. Pickup and drop tree over and over
4. ex. infinite Tree

**Expected behavior**
Noninfinite tree

**Actual behavior**
Infinite tree

**Screenshots & Video**
(https://youtu.be/0A8W1NtGiRs)

**Branch Version**
Tester or Live.

**Character Information**
herbivore of size to piick tree

**Additional Information**
On forest island

**Comment by Vallyhalla** [comment]
This has been fixed!
