### ISSUE TITLE
collision plant 

### ISSUE THREAD

**Issue by Arko3** [BoBAdministration/QA-Bug-Reports#166]
**Describe the Bug**
collision on small fern 

**To Reproduce**
1. ex. Logged into Dedicated Testing 3
2. ex. Spawned in as any dino
3. ex. go into spectate and select SM_Fern_01/04 and place them
4. ex. they have collision on.

**Expected behavior**
you should just walk right thru them

**Actual behavior**
you get bumped up and walk over them as if they are solid.
**Screenshots & Video**
![image](https://user-images.githubusercontent.com/96443166/147122730-9a118beb-2148-4c4c-b7f5-0e581b6abfdc.png)

**Branch Version**
Tester both Live.

**Character Information**
none

**Additional Information**
none

**Comment by Vallyhalla** [comment]
This has been fixed!
