### ISSUE TITLE
The game crashes after pressing Alt+Enter while on Talents screen

### ISSUE THREAD

**Issue by AgentHawke** [BoBAdministration/QA-Bug-Reports#167]
**Describe the Bug**
For some reason the game crashes if the player is playing in fullscreen and pressing Alt+Enter while on Talents screen

**To Reproduce**
1. Log into any Live or Testing server
2. Spawn any creature (e.g. Rex)
3. Open Talents screen
4. Press Alt+Enter

**Expected behavior**
The game should exit fullscreen mode and stay open as a window

**Actual behavior**
The game exits fullscreen mode to window and crashes

**Screenshots & Video**
https://youtu.be/R5XabvSH0vM

**Branch Version**
Both Live and Tester

**Character Information**
Tested with various species (Rex, Ichty, Apa), the growth is not important

**Additional Information**
The game should be run in fullscreen mode

**Comment by themurdock13** [comment]
This Bug appears to be fixed, i have tried on multiple attempts

**Comment by Vallyhalla** [comment]
Seems to be a problem with people with lower end PC's as the screen is being forced to be smaller so quickly, and their PC can't handle the game doing that so it crashes. Closing this.
