### ISSUE TITLE
Glitch in ptera tower shelves textures

### ISSUE THREAD

**Issue by Akaraasaur** [BoBAdministration/QA-Bug-Reports#171]
**Describe the Bug**
When a velociraptor climbs the wall of Ptera tower, it can glitch into the texture of a shelf and into a rock and end up inside the tower. People can use it to nest and grow safely, but also to see people inside the cave and outside.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log into any server with Rival Shores map
2. Spawned as a velo
3. Walk and climb to 
![image](https://user-images.githubusercontent.com/96403359/147140297-f58e1ec8-1fb3-4de0-923c-9daa6ea5d925.png)

4. Continue to climb inside the shelf and the rock and when you fall, jump.
5. You're inside the tower.

**Expected behavior**
I should not pass through the texture of the rock and go inside the tower.

**Actual behavior**
I can pass through the textures of the rock and go inside the tower.

**Screenshots & Video**
https://youtu.be/yXwivgiB0wI

**Branch Version**
Live Branch

**Character Information**
Velociraptor, 1.2.

**Additional Information**
Rival Shores map, Ptera Tower

**Comment by Dinorunp** [comment]
still not fixed
