### ISSUE TITLE
Floating Tree on Rival Shores -136698 25754 15893

### ISSUE THREAD

**Issue by teatimejess** [BoBAdministration/QA-Bug-Reports#18]
**Describe the Bug**
Tree is unearthed and ascending.

**To Reproduce**
1. Log into Rival Shores on any pawn
2. TeleportAt -136698 25754 15893
3. Observe tree.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/77513445/130313047-fc4b7596-42b6-4563-8ffd-d7d1434c36d7.png)

**Branch Version**
Live.

**Character Information**
N/A

**Additional Information**
N/A

**Comment by Predatoria** [comment]
fixed

**Comment by teatimejess** [comment]
Confirmed, no floating tree at teleport location.
