### ISSUE TITLE
Admin Slots Log-In Bug

### ISSUE THREAD

**Issue by Zer0Health** [BoBAdministration/QA-Bug-Reports#180]
**Describe the Bug**
When trying to log into a server with space available it shows that the remaining slots are admin slots (when the server in question only has 4 admin slots and 11 admin were online)

**To Reproduce**
1: Launch BoB
2: Try logging into server when there is at least 149/150
3: If not an admin for the server, sometimes the pop up will state: removed from server: This server is full! The last available slots are reserved for admins.

**Expected behavior**
To allow player to enter server when there is empty space and admin slots filled.

**Actual behavior**
When trying to log into a server with space it will kick you thinking there is open admin slots.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/96402102/147263560-f0cc4fcd-8072-4755-969c-be8412162565.png)

**Branch Version**
Live Branch

**Additional Information**
Server: Le Hideout | Player Slots: 150 | Admin slots: 4

**Comment by tinystarpaws** [comment]
This is not a bug. This is a limitation of Steam.
