### ISSUE TITLE
Dropping Babies While Holding them

### ISSUE THREAD

**Issue by Vallyhalla** [BoBAdministration/QA-Bug-Reports#183]
**Describe the Bug**
As any creature if you pick up a hatchling while it's jumping, it will slingshot depending what direction you travel. Eventually you will drop the baby randomly. This also applies to birds baby snatching.

**To Reproduce**
1. Logged into Moo server
2. Spawned a Ptera
3. Set growth to 1.4
4. Put in 3/3 Baby snatcher, 3/3 GP, and 3/3 stoic.
5. Had someone as a baby jump
6. Pick up the baby while it's jumping
7. Fly around until the baby eventually falls out of your mouth.

**Expected behavior**
Baby should not glitch or fall out of the mouth of the one carrying it, whether in the same group or not.

**Actual behavior**
Baby glitches while picked up, and will eventually fall out of the carriers mouth,

**Screenshots & Video**
https://www.youtube.com/watch?v=MWztjimABsQ&ab_channel=ValHalla

**Branch Version**
 Live.

**Character Information**
1.4 Ptera, .3-.4 sized babies.

**Additional Information**
Tested on Rival Shores.

**Comment by tinystarpaws** [comment]
This problem is caused by a bug in Unreal Engine. Sadly, it is not something we can fix ourselves.
