### ISSUE TITLE
Megaraptor Grab animation Bug

### ISSUE THREAD

**Issue by Ruined-Omega** [BoBAdministration/QA-Bug-Reports#184]
**Describe the Bug**
Megaraptors' grab animation doesn't play when you try to grab while walking

**To Reproduce**

1. Logged into Dedicated Testing 3
2. Spawned as a Megaraptor and grew to 1.2
3. Spawned Crystal to help see the issue easier
4. First walked through having pressed grab before walking forward
5. Second walk through I pressed grab during the walk

**Expected behavior**
The grab animation played when you press grab before walking should also play when you try to grab during walk

**Actual behavior**
The megaraptors head doesn't move for its grab animation so it looks like it's just walking instead of grabbing objects

**Screenshots & Video**
https://www.youtube.com/watch?v=uj6Xq9uywHw

**Branch Version**
Tester 

**Character Information**
1.2 Speed Megaraptor

**Additional Information**
Clear weather but will happen during any. Animation also doesn't play on .4 model as well

**Comment by Predatoria** [comment]
Reproduced and fixed in PIE
