### ISSUE TITLE
Rex Holding Baby Issue

### ISSUE THREAD

**Issue by SweetLilYuleCat** [BoBAdministration/QA-Bug-Reports#186]
**Describe the Bug**
I was being carried by my rex mother and noticed I looked like I was about to fall out of her mouth and trying to hang on for dear life.

**To Reproduce**
Have a rex try to grab and hold its baby while the baby is between .3 and .5

**Expected behavior**
I expected the mother to hold the baby fully in its mouth to where the baby is curved around the lower jaw a bit

**Actual behavior**
Baby rex looks more like it is holding on to the teeth of its parent

**Screenshots & Video**

![20211223010531_1](https://user-images.githubusercontent.com/96404685/147291219-2531c550-882c-4edc-97a3-c5a75b252966.jpg)

**Branch Version**
Live.

**Character Information**
Rex baby size: .3 or .5 (before .7) no talents/points/inherits put in the baby

Additional Information
Server name: Noobz 2

This could be an issue due to size since the growth rates are faster now, however I feel I was small enough as i had only hatched about 5 maybe 10 minutes prior to this and this is the first time I've seen a baby look like it is falling out of its parent's mouth

**Comment by Vallyhalla** [comment]
Couldn't replicate! Seems to be fixed so I'll close this!
