### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by LanikaTerDeil** [BoBAdministration/QA-Bug-Reports#188]
**Describe the Bug**
Ash decals left by fire show over top of a creature's model

**To Reproduce**
1. Logged into Official 2 (Live branch)
2. Appeared on the Sai near the site after a fire (ashes)
3. Went to the burned area
4. The ash texture was shown over top of the creature's model

**Expected behavior**
The texture would not interact and would not affect the dinosaur model in any way.

**Actual behavior**
As a result, the ash texture was reacted to the creature's model and shown over top of it.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/96621531/147362314-c88019eb-4de5-4773-aa91-96aff70d3d17.png)

**Branch Version**
Live branch

**Character Information**
Saichania 1.2

**Additional Information**
AP. Calm weather just after the recent fire

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
