### ISSUE TITLE
Velo able to mesh through almost any mesh when climbing.

### ISSUE THREAD

**Issue by JusttynG** [BoBAdministration/QA-Bug-Reports#189]
**Describe the Bug**
When climbing Velo's can mesh through objects.

**To Reproduce**
1. Log into any map.
2. Spawned in a Velo.
3. Climb a climbable object that has another object meshing through it.
4. Climb through meshed object.

**Expected behavior**
Velo should ether fall or start to climb the other mesh.

**Actual behavior**
velo can mesh through object when climbing.

**Screenshots & Video**
https://youtu.be/xuzFHlIfrl0

**Branch Version**
Any

**Character Information**
Velo, no other information is relevant for this bug.

**Additional Information**
Video is from Titania Dedicated testing 12.
Location: X:453104 Y:380130 Z:-12160

**Comment by tinystarpaws** [comment]
This is not a bug; this is a limitation of the feature to avoid Velo's camera going absolutely bonkers

**Comment by JusttynG** [comment]
Just so i understand this better, in order to stop the Velo's camera from shaking, velo has been made to mesh through the map?

**Comment by tinystarpaws** [comment]
Not quite. It is to optimize the game.
Camera collision is quite expensive. This is not the best solution, but with what we have at the moment, it is our best option right now.
