### ISSUE TITLE
Crevice on Rival Shores causes players to fall through map. -129971 30509 11731

### ISSUE THREAD

**Issue by teatimejess** [BoBAdministration/QA-Bug-Reports#19]
**Describe the Bug**
Crevice on Rival Shores causes players to fall through map.

**To Reproduce**
1. Log onto Rival Shores, spawn pachy.
2. SetGrowthLevel 0.7
3. TeleportAt -129971 30509 11731
4. Walk backwards into wall.
5. Fall through world.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/77513445/130313137-19fc6f68-69cf-47b3-8a9f-b776bde1cbeb.png)

**Branch Version**
Live

**Character Information**
This occurred when tested on Pachy 0.7 size, though will affect any pawn small enough.

**Additional Information**
N/A

**Comment by Predatoria** [comment]
fixed

**Comment by teatimejess** [comment]
Fixed on tester, attempted steps with 1.2 Velo and was unable to phase through wall.
