### ISSUE TITLE
Velo collision with palm leafs.

### ISSUE THREAD

**Issue by JusttynG** [BoBAdministration/QA-Bug-Reports#191]
**Describe the Bug**
Velo has collision with palm leafs.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 12.
2. Spawned in a Velo.
3. Find a tree with palm leaf's, or TP to coordinates in provided screenshots.
4. Jump onto palm leafs.

**Expected behavior**
Velo should fall through the leafs.

**Actual behavior**
Velo can jump onto the leafs as if they are the ground.

**Screenshots & Video**
![Beastsofbermuda Screenshot 2021 12 24 - 14 47 16 50](https://user-images.githubusercontent.com/96445354/147370852-ec7438ca-badd-4980-b442-ac6717a647c3.png)
![Beastsofbermuda Screenshot 2021 12 24 - 14 48 00 73](https://user-images.githubusercontent.com/96445354/147370855-7a8cad17-3c5f-4a05-bb23-f8ff2797ed2b.png)

**Branch Version**
Tester.

**Character Information**
Velo, 1.4

**Additional Information**
Titania.

**Comment by tinystarpaws** [comment]
This is not a bug; Velo uses complex collision and can most often rest on palm leaves. Also, please submit Titania bugs in the Titania-Zone channel in the QA discord!
