### ISSUE TITLE
Small Animation bug with Megaraptor

### ISSUE THREAD

**Issue by Macarani123** [BoBAdministration/QA-Bug-Reports#192]
**Describe the Bug**
When swimming as Megaraptor and breaching the water vertically, the head and neck will whip back or forwards at a broken angle.

**To Reproduce**
1. Log into a testing server with megaraptor available for play, i used dedicated 3.
2. Spawn in as a megaraptor
3. Grow to adult size 1.0-1.2
4. Head to the ocean and swim out a bit so you can get a good vertical position floating in the water. 
5. Hold shift and space so you swim straight up quickly, breaching the surface. 
6. Behold Megaraptor neck snap depending on if you're looking up or down or straight, at the time, the neck snap will be different.

**Expected behavior**
Megaraptor probably shouldnt be snapping its neck so violently for swimming upwards.

**Actual behavior**
Megaraptor's head and neck will snap oddly and break if you swim up vertically and breach the surface of water.

**Screenshots & Video**
First image is with no broken neck, just vertically floating with a straight ahead, screenshot mode head.
![20211225060645_1](https://user-images.githubusercontent.com/96443517/147384861-de0e558b-f406-4f6d-9469-f8909be2e5f3.jpg)
![20211225060648_1](https://user-images.githubusercontent.com/96443517/147384863-b6524e1a-d396-4269-b685-2cc4cbe86ced.jpg)
![20211225063629_1](https://user-images.githubusercontent.com/96443517/147384936-27d85d22-2d74-49a5-872e-714931f104bf.jpg)

**Branch Version**
Tester

**Character Information**
Growth 1.2, talent points in aqua, stronglungs, and general speed talents.

**Additional Information**
Ancestral Plains Canvas, clear weather but it did rain later.

**Comment by MarshmallowMaiden** [comment]
Confirmed fixed on tester branch
