### ISSUE TITLE
Mega raptor can knock down trees

### ISSUE THREAD

**Issue by Arko3** [BoBAdministration/QA-Bug-Reports#194]
**Describe the Bug**
megaraptor can knock down some trees as early as 1.2

**To Reproduce**
megaraptor > 1.2 > run against a tree
1. ex. Logged into Dedicated Testing 12
2. ex. Spawned in a Megaraptor
3. ex. Run against a small ish tree
4. ex. got know down . in some cases a non collison clone was left behinde

**Expected behavior**
Tree should have been not knocked over since a megalo at 1.2 cant even knock it down

**Actual behavior**
casualy walks thru it and sends it flying/ on a megalo the tree didnt get knock down (1.2)

**Screenshots & Video**

https://user-images.githubusercontent.com/96443166/147385548-e264ecf5-6f4e-47c9-9304-381bf1f717c7.mp4

**Branch Version**
Tester.

**Character Information**
Dinosaur growth 1.2 ( tested 1.1 but didnt know down the same tree type)

**Additional Information**
map was titania

**Comment by Predatoria** [comment]
oops,  Stat mistake.  Fixed it
