### ISSUE TITLE
Dino floats at particular spot on Ancestral Plains

### ISSUE THREAD

**Issue by Skyedrago** [BoBAdministration/QA-Bug-Reports#196]
**Describe the Bug**
Dinos float above a particular set of rocks

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log into an Ancestral Plains server
2. Spawn as a dino (I chose tropeo). It is most easy to see with small dinos.
3. Travel to the coordinates X:-37475 Y:-2870 Z:13508
4. Your dino will float

**Expected behavior**
Dino stands on rock

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshots & Video**
![20211226060602_1](https://user-images.githubusercontent.com/96404852/147406171-8a2aee7f-f6e0-4a99-802e-07c8ba773c4f.jpg)

**Branch Version**
Live.

**Character Information**
Tropeo only had 3/3 Resilience and 2/3 swiftness.

**Additional Information**
Ancestral Plains. This works in all weather types although in this case, there was fire nearby.

**Comment by Vallyhalla** [comment]
This is still happening! 
![image](https://user-images.githubusercontent.com/96442596/226446385-c65a867e-69e6-4133-903e-07a4b6e61a9a.png)
