### ISSUE TITLE
Seeing through a rock from one side

### ISSUE THREAD

**Issue by Skyedrago** [BoBAdministration/QA-Bug-Reports#197]
**Describe the Bug**
Two crevices in the rock at the below coordinates allow a player to hide inside while watching the area around them. Players outside see the rock as solid.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into server Moo.
2. Spawn as an aquatic (I chose krono)
3. Head to the rock near the coordinates in the screenshots.
4. Spin the camera toward what should be solid rock
5. Player can now see the ocean around them from inside the crevices.

**Expected behavior**
Rock cannot be seen through and behaves as a solid from the crevices and outside.

**Actual behavior**
Player can see others through the rock crevices but the rock is solid from the outside.

**Screenshots & Video**
![20211226063443_1](https://user-images.githubusercontent.com/96404852/147406780-71a8032f-67cc-4ff6-b351-9ea040a428f4.jpg)
![20211226063446_1](https://user-images.githubusercontent.com/96404852/147406781-c0734f3f-6caa-4118-b546-7eff05b19056.jpg)
![20211226063506_1](https://user-images.githubusercontent.com/96404852/147406782-ba121347-5081-40cc-9c00-a557c0d431ab.jpg)
![20211226063522_1](https://user-images.githubusercontent.com/96404852/147406783-136cf8ec-5cc7-4378-baf2-5d88946da605.jpg)

**Branch Version**
Live

**Character Information**
Fresh spawn krono with no talents.

**Additional Information**
Rival Shores Canvas map. Originally posted at https://github.com/Thy-Vipe/BeastsOfBermuda-issues/issues/6073 but did not get stuck (per the translated dialogue). The third pictures is a shot of the rock from the outside. The three other pictures are shots from within the rock's crevices. The crevices that seem most abusable are X:34051 Y:65200 and Z:-5224 and X:34556 Y:63825 Z:-6078 because players can hide inside as a small aquatic and see the ocean around them.

**Comment by Predatoria** [comment]
moved rocks, should be fixed
