### ISSUE TITLE
[Megaraptor] Stray vertice on fat morph

### ISSUE THREAD

**Issue by theriversedge** [BoBAdministration/QA-Bug-Reports#198]
**Describe the Bug**
Megaraptor's fat morph has a stray vertice on the throat

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log onto any available QA test branch server
2. Spawn in as Megaraptor
3. Grow to 1.2 and acquire 130 food (max fat)
4. View the throat area, press Alt if it can't be seen easily

**Expected behavior**
Megaraptor's fat morph should not have any stray vertices

**Actual behavior**
Megaraptor's fat morph has a noticeable stray vertice on the throat

**Screenshots & Video**
![20211226153403_1](https://user-images.githubusercontent.com/55609311/147421016-3f1b4896-9597-4688-844e-4e06a99c214d.jpg)

**Branch Version**
Tester

**Character Information**
1.2 Megaraptor with 130 food

**Additional Information**
N/A

**Comment by Predatoria** [comment]
Seems to be fixed.
