### ISSUE TITLE
Near full-body bio mutation on Ichthy.

### ISSUE THREAD

**Issue by tinystarpaws** [BoBAdministration/QA-Bug-Reports#2]
**Describe the Bug**
The "Sides" Marking layer of the Ichthy Wildfire skin is able to mutate, and it covers most of the body.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Spawn in Ichthy with a randomized Wildfire skin
2. MakeBrood with yourself until the undesired result pops up

**Expected behavior**
This layer should not be able to mutate.

**Actual behavior**
This layer does have a chance to mutate.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/38923098/129317198-59ce8763-40b5-445c-95d6-18cadf8fb9dc.png)
![image](https://user-images.githubusercontent.com/38923098/129317217-115f3e45-7573-40ac-875d-affe9630cbde.png)

**Branch Version**
Occurred on Live servers.

**Character Information**
Ichthyovenator, Wildfire skin. 

**Additional Information**
N/A

**Comment by Soals** [comment]
Fixed Clamping Issue: All layers in the Markings Row should not pass.

**Comment by CeciliaSE** [comment]
Have been unable to reproduce any biomutation in the markings category. The issue can be considered fixed until further notice, and the ticket closed
