### ISSUE TITLE
Under mapping on Rival Shores -216831 -12155 19237

### ISSUE THREAD

**Issue by teatimejess** [BoBAdministration/QA-Bug-Reports#20]
**Describe the Bug**
Under rmapping on Rival Shores

**To Reproduce**
1. Log into Rival shores on any pawn
2. TeleportAt -216831 -12155 19237

**Screenshots & Video**
https://www.youtube.com/watch?v=qf9fcU5Pc9U
![image](https://user-images.githubusercontent.com/77513445/130313184-d992938e-0540-4b89-a484-4c30935cf656.png)

**Branch Version**
Live

**Character Information**
N/A

**Additional Information**
Spot is underwater.

**Comment by Predatoria** [comment]
fixed

**Comment by teatimejess** [comment]
Fixed on tester, attempted to breach crevice with 0.1 krono, .4 krono, and 0.1 elasmo and was unable.
