### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by HereSad** [BoBAdministration/QA-Bug-Reports#202]
**Describe the Bug**
Ash left after fire overlaps character models

**To Reproduce**
    1. Log into any server (public branch) (a test server makes this process easier)
    2. Walk to an area that was recently exposed to fire and has ash overlapping the ground
    3. step into the burned area
    4. the ash from the ground will overlap the dinosaurs model

**Expected behavior**
Ash textures should not overlap dino models, should only cover charred lands.

**Actual behavior**
Ash textures overlap dino models rather than strictly covering charred lands. Results in... charred dino.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/47996176/147515572-a27b9522-482f-4bce-ad36-509fe6c1473c.png)

**Branch Version**
Live 

**Character Information**
1.2 Sai

**Additional Information**
Occurs on all maps, 100% reproduction rate.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
