### ISSUE TITLE
"Fake" glimmer rex / Bio rex give bio reincarnated babies

### ISSUE THREAD

**Issue by Akaraasaur** [BoBAdministration/QA-Bug-Reports#205]
**Describe the Bug**
The rex with a bioluminescent skin or with the stripes of the glimmer skin glowing or not) have the particularity to give bioluminescent babies if they are reincarnated after being nested. I've seen some players doing this kind of nesting for several days now, but others with bioluminescent skins can give bio babies after reincarnation as well. More than 30 bio rex babies were born like that in a row, it's not just luck in my opinion.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log into any server
2. Spawn as a rex with non glowy glimmer stripes or with glowy glimmer stripes (but not owned).
3. Nest with an other rex
4. Nested baby need to reincarnate at .8
5. They should have now bioluminescent layer (showing or not).
6. If this reincarnated baby nest with an other rex, they give reincarnated bio kids too.

**Expected behavior**
This kind of reincarnation should not give so much chance to have bio skin.

**Actual behavior**
Reincarnated babies have bio skin all the time.

**Screenshots & Video**
<img width="795" alt="Screenshot_1019" src="https://user-images.githubusercontent.com/96403359/147787552-9cc442a7-c4d9-468b-9fcf-9e0dc4161269.png">

<img width="251" alt="Screenshot_1020" src="https://user-images.githubusercontent.com/96403359/147787563-08b5b24f-60d6-4d2b-918a-1d1e4e37a311.png">
<img width="794" alt="Screenshot_1021" src="https://user-images.githubusercontent.com/96403359/147787575-d82fb897-8d6e-4ac8-b708-83451da1f39c.png">

(I have more screenshots if needed, I have also some conversations with players about this bug)

**Branch Version**
Live Branch

**Character Information**
Rex with glimmer stripes (not glowing or glowing but without owning the glimmer skin) or Rex with reincarnated bio skin.

**Additional Information**
Any map

**Comment by Thy-Vipe** [comment]
This issue should be fixed during next patch. The code was not specifically looking for biomutation data, only assuming it if a texture overrides the glimmer layer id. I Followed the reproduction steps and could not get it to happen with the fix.

**Comment by MarshmallowMaiden** [comment]
Confirmed Fixed
