### ISSUE TITLE
Some Foliage Undeletable in Foliage Tool.

### ISSUE THREAD

**Issue by KattofKits** [BoBAdministration/QA-Bug-Reports#207]
**Describe the Bug**
Whilst testing what foliage would be the best for my herbivore players, I came across this odd bug where after SM_Tree_Medium_01 was eaten, it could not be deleted. Even upon placing a new one it still could not be deleted. Eaten foliage (with remnants such as bare branches or twigs) can not be erased, but I could previously just select them and delete them manually. The Tree types were able to be removed once they were knocked down by a player (not shown).

**To Reproduce**
1. Log into any Live Open Consol server.
2. Enter Foliage Tool
3. Place SM_Tree_Medium_01 and/or SM_Tree_Medium_02
4. Have yourself or someone else eat said tree
5. Try to delete SM_Tree_Medium_01 and/or SM_Tree_Medium_02

**Expected behavior**
Be able to remove SM_Tree_Medium_01 / SM_Tree_Medium_02 regardless of its current state within the foliage tool.

**Actual behavior**
SM_Tree_Medium_01 / SM_Tree_Medium_02 become undeletable once eaten, until knocked down.

**Screenshots & Video**
https://user-images.githubusercontent.com/90863811/147912898-4c60bab8-1381-492f-a45f-3bf6c0136971.mp4

**Branch Version**
Live

**Character Information**
1.8+ Naturally Grown Sai 

**Additional Information**
Rival_Shores, Tier 5 Admin Forced Storm

**Comment by Predatoria** [comment]
I think we fixed this a while ago
