### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by Docattt** [BoBAdministration/QA-Bug-Reports#211]
**Describe the Bug**
Ash leftover by fire show over top of a creatures model

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 1
2. Spawned in a Sai at Forest
3. A fire started
4. After the fire died down the ash that was leftover showed on top of my creature

**Expected behavior**
Ash should show up on the ground, but not over the creature.

**Actual behavior**
Instead of the ash only showing up on the terrain it showed up over my creature.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/96480280/147960154-a80e53d7-b7fb-4c57-a4cb-a2b53e4418a4.png)

**Branch Version**
Tester.

**Character Information**
Sai 1.2

**Additional Information**
Rival Shores, after a fire.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
