### ISSUE TITLE
Ferns with Mesh in Foliage Tool

### ISSUE THREAD

**Issue by Sonatasuarus** [BoBAdministration/QA-Bug-Reports#212]
**Describe the Bug**
SM_Fern_01 
SM_Fern_04

These two items have collision, I don't feel like they're supposed to. Once picked up they also glitch in the area they were in so if you walk into the blank space you get caught on a block of air with collision.

**To Reproduce**
1. Logged into Forest Island Canvas server
2. Enter Spectate, open foliage tool
3. Place SM_Fern_01 and SM_Fern_04
4. Return to ferns on a dinosaur and attempt to walk through them, then pick them up and attempt to walk in the space they were in.

**Expected behavior**
Ferns and space where they had been should be walked through without issue.

**Actual behavior**
The ferns and the vacant place they were both have collision.

**Screenshots & Video**
https://www.youtube.com/watch?v=5lmVW5Z6Wi4&ab_channel=SonaOmi

**Branch Version**
Live.

**Character Information**
Ichthy, 1.2 spawn.

**Additional Information**
Forest Island Canvas, clear weather.

**Comment by Predatoria** [comment]
These were fixed in a recent tester build
