### ISSUE TITLE
Acrocanthrosaurus can smell itself (it's kinda stinky).

### ISSUE THREAD

**Issue by KattofKits** [BoBAdministration/QA-Bug-Reports#213]
**Describe the Bug**
As an Acrocanthrosaurus, I can smell myself walking, which when hunting can be disorientating. Trying to identify what a dinosaur is in front of you, and it tells you "Acrocanthrosaurus" as a huge yellow cloud surrounds you.

**To Reproduce**
1. Log into any Live server
2. Spawn in as a fresh or already existing Acrocanthrosaururs (above .7-.8)
3. Sniff around you
4. Sniff yourself

**Expected behavior**
A player playing Acro should not be able to sniff their own trail but instead other players' trails only.

**Actual behavior**
A player playing Acro is able to smell themselves, including their own walking path.

**Screenshots & Video**
https://youtu.be/LYBrWu1Mmwo

**Branch Version**
Live

**Character Information**
1.83 Naturally grown/nested Acrocanthrosaurus

**Additional Information**
Rival_Shores, Tier 5 Admin spawned growth storm

**Comment by themurdock13** [comment]
after 10 min of waling around on 2 different across no sent cloud appeared and was unable to replicate

**Comment by Vallyhalla** [comment]
If you exit to main menu and hit 'reconnect' and spawn directly back onto that creature you can smell your own scent cloud. Closing this!
