### ISSUE TITLE
Secondary accounts owning BoB crash upon entering a game

### ISSUE THREAD

**Issue by Bizare** [BoBAdministration/QA-Bug-Reports#216]
**Describe the Bug**
Primary account works fine. After the last patch if I log onto my alt account (which owns a copy of bob) and attempt to create or save a skin on any server my game crashes. Friend having same issue. Verifying game files did not prevent this.

**To Reproduce**
1. Log into account, open BoB
2. Select any server
3. go into creature creation with any creature
4. Edit skin and enter game (crash occurs) OR
5. click save skin, name skin (after attempting to name skin and enter, crash occurs) OR
6. enter the game with a default skin (game crashes upon attempting entry)

Additionally, clicking your "saved skins" tab with any creature in character creation will create an extremely long lag spike that eventually resolves itself without crashing the game. Game also crashes upon trying to enter with a default skin.

Unreal Engine 4 Crash Reporter pops up after and says:
 "Fatal error: [File:C:\GameDev\UnrealEngine\Engine\Source\Runtime\Core\Public\Serialization/MemoryWriter.h] [Line: 42] FMemoryWriter does not support data larger than 2GB. Archive name: None."
 
**Expected behavior**
I should be able to enter any server without crashing and freely edit and save skins like normal on a secondary account with its own copy of the game.

**Actual behavior**
Game lags upon checking your saved skins tab, crashes upon attempting to enter any server or save a skin. 

**Screenshots & Video**
Video of me entering random server, clicking saved skins to showcase the lag, then attempting to enter the server and crashing.
https://youtu.be/-838UTD9Rv8

**Branch Version**
Live

**Character Information**
N/A

**Additional Information**
Seemingly occurs on any map and in any game type. (tried many at random and changed up game type)

**Comment by Vallyhalla** [comment]
This is fixed!
