### ISSUE TITLE
Krono gets stuck in prime Lunge pose when out of ability or stamina.

### ISSUE THREAD

**Issue by KattofKits** [BoBAdministration/QA-Bug-Reports#217]
**Describe the Bug**
Kronosaurus, when using its lunge ability whilst out of stamina or ability, will appear to other players stuck in the prime lunge pose, locked in that pose with no animation whatsoever. It appears when leaving the area/out of render of the afflicted player, this issue will correct itself.

**To Reproduce**
1. Log into any live branch server
2. Spawn in as a kronosaurus
3. Use up all stamina or ability
4. Try to lunge with no stamina or ability
5. Have someone who was in the area at the time of the event look at you to see if you are stuck in a nonanimated pose

**Expected behavior**
Krono should go back to moving/idling like normal after a lunge, no animation should play when player tries to activate their lunge ability.

**Actual behavior**
Player gets locked into an animationless pose after attempting to lunge with no stamina or ability. However, it does not show them locked in this position client side.

**Screenshots & Video**
https://www.youtube.com/watch?v=YfeCBqI4FOg
![BeastsOfBermuda_ACOJuTZmau](https://user-images.githubusercontent.com/90863811/148623452-02d39523-e1df-4012-a19f-f19b219cd6e8.png)
![unknown (4)](https://user-images.githubusercontent.com/90863811/148623457-b032a3de-64e5-4c4b-94f5-b298225ad1dc.png)

**Branch Version**
Live

**Character Information**
1.3 (Naturally grown Spawn) & 1.25 (Naturally grown reincarnate) Kronosaurus

**Additional Information**
Rival_Shores, Admin Summoned Tier 5 Growth Storm, Locational decore created with Foliage Brush tool

**Comment by Predatoria** [comment]
I cannot reproduce this.
