### ISSUE TITLE
Same named accounts can not be teleported, despite different steam ID and in game ID.

### ISSUE THREAD

**Issue by KattofKits** [BoBAdministration/QA-Bug-Reports#218]
**Describe the Bug**
Players with the exact same name can not be teleported places without one or more being left out. (Example, my admin Owl could not teleport her alternative account to herself, due to the same name, despite having different steam ids, and in game ids, I tried this myself, and had the same result).

**To Reproduce**
1. Log into any live branch server with two or more players under the exact same name
2. Make sure each person does not share a family account with either person or alt account, have different steam IDs, in game IDs, are two different entities that can connect to the server
3. Try to teleport both accounts to a location or player

**Expected behavior**
There should be some way the system should be able to recognize each individual player, aside from their name. Supposedly the in-game ID should do this, so perhaps this is not working as intended at the moment.

**Actual behavior**
Any number of players with the exact same in game name will not be able to be teleported, or one can be teleported but the other can not.

**Screenshots & Video**
https://user-images.githubusercontent.com/90863811/148637015-4a48830d-b273-4598-9aa6-f7d83ee5f2f8.mp4
![Discord_dT1BNG1TtC](https://user-images.githubusercontent.com/90863811/148637023-d39d6a44-7fbd-49bc-bbf6-43a6c0db488d.png)
![BeastsOfBermuda_RydWTYi2BM](https://user-images.githubusercontent.com/90863811/148637027-8cb2288a-3ff7-4935-a24d-1d6ddf559561.png)
![BeastsOfBermuda_mCr4NTwqVd](https://user-images.githubusercontent.com/90863811/148637029-d2141632-6511-483c-8770-7e816b502dae.png)

**Branch Version**
Live

**Additional Information**
Both "Brew-Owls" are the same person, different computer, non-shared account, different steam IDs, different in-game IDs, two different entities. However, due to having the same name in-game, it becomes an issue. Changing one name fixed the issue.

**Comment by Vallyhalla** [comment]
You can't teleported to someone with the same name as you if you do TeleportToP Valhalla, but you can teleport using their in-game 3 digit ID. Closing this now.
