### ISSUE TITLE
Meeting example bug

### ISSUE THREAD

**Issue by The-Grand-Tickler** [BoBAdministration/QA-Bug-Reports#22]
Ash decals now cover players

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Spawn and put out a fire
2. Spawn as any creature
3. Stand on the ash decal
4. Ash projects onto player

**Expected behavior**
Ash on the ground and foliage only

**Actual behavior**
Ash projects onto player

**Branch Version**
Live.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
