### ISSUE TITLE
[Megaraptor] Tail snapping issue during stand-to-sit animation

### ISSUE THREAD

**Issue by theriversedge** [BoBAdministration/QA-Bug-Reports#220]
**Describe the Bug**
Megaraptor's tail snaps to a neutral position during the stand-to-sit animation

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 3
2. Spawned as a Megaraptor and grew to 1.2
3. Pressed the sit key while my creature was looking to the right, activating the aforementioned animation
4. Witnessed the tail snapping behavior as my creature sat down

**Expected behavior**
The tail curl should smoothly transition into the stand-to-sit animation

**Actual behavior**
The tail snaps unnaturally during the stand-to-sit animation

**Screenshots & Video**
N/A

**Branch Version**
Tester

**Character Information**
1.2 Megaraptor

**Additional Information**
Ancestral Plains Canvas

**Comment by Predatoria** [comment]
It should now interp smoothly into the sitting pose
