### ISSUE TITLE
Pit where dino gets stuck and are unable to escape without unstuck or admin

### ISSUE THREAD

**Issue by Skyedrago** [BoBAdministration/QA-Bug-Reports#223]
**Describe the Bug**
A map pit on Ancestral Plains where a dino that cannot jump high (ie rex, apa, etc) cannot escape after falling down.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log onto a server hosting Ancestral Plains
2. Travel to the ledge above coordinates -26622 392 12599 as a dino such as a rex or apa, or another dino that cannot jump well or at all
3. Climb down to the left of the rock, toward the coordinates
4. Dino will slip and land on the ledge in the below picture, then be unable to escape without unstuck or an admin.
5. Some dinos, such as a 1.2 rex, will act as though they are falling and landing.

**Expected behavior**
Dino slides down hill and takes damage, or dino is able to climb out.

**Actual behavior**
Dino becomes stuck. In the below picture, my rex was continuously acting as though it was falling and landing.

**Screenshots & Video**
![20220108222556_1](https://user-images.githubusercontent.com/96404852/148668150-428b0099-831a-43a2-8908-60c85e4d3bf5.jpg)

**Branch Version**
Live.

**Character Information**
This rex was slightly over 1.2 (approx 1.203) with no powerful legs.

**Additional Information**
Ancestral Plains map

**Comment by Vallyhalla** [comment]
Either move the rock or place another so people don't get stuck. 
![image](https://user-images.githubusercontent.com/96442596/226442724-5e81e479-a641-4345-9438-0a4f4ff619ac.png)
