### ISSUE TITLE
Softcap/Hardcap for Ichthyovenator not displaying correctly. 

### ISSUE THREAD

**Issue by KattofKits** [BoBAdministration/QA-Bug-Reports#224]
**Describe the Bug**
Looking at the group menu of my server's mixpack, Ichthy appears overpacked, when they are only one ichthy at the moment.

**To Reproduce**
1. Log into any mixpacking live server
2. Join or create a group with multiple carnivores/other players, especially Ichthy
3. Tab into Group menu
4. Observe odd grouping number behaviour

**Expected behavior**
Group functions being able to display correctly, despite odd group numbers.

**Actual behavior**
Ichthyovenator displaying incorrectly/at max capacity when actual member count is far, far less.

**Screenshots & Video**
![BeastsOfBermuda_7IJ50mYdHd](https://user-images.githubusercontent.com/90863811/148713173-a8a1f6f6-984d-4859-8a79-6ae627b81a91.png)
![BeastsOfBermuda_XBJzaDEN1x](https://user-images.githubusercontent.com/90863811/148713176-513bb281-87ab-44a1-af15-bf9477b80f62.png)
![chrome_aoQZxpvbTp](https://user-images.githubusercontent.com/90863811/148713184-5b3af8f0-eb4e-4dbb-bc76-6edce2606129.png)

**Branch Version**
Live

**Additional Information**
Rival_Shores, Tier 5 Admin Spawned Growth Strom, This bug was viewed from an egg, specifically an Acrocanthrosaurus egg.

**Comment by Predatoria** [comment]
Ichthy is the default for an unitialized group count widget.  Should be fixed now
