### ISSUE TITLE
Lurdu doesnt have any walk noises

### ISSUE THREAD

**Issue by Alyrius** [BoBAdministration/QA-Bug-Reports#225]
**Describe the Bug**
Lurdus walking sounds seem to have disappeared somewhere along the way, he is now the sneakiest boye. His idle grunts are gone as well in sitting position I think

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log into any server (tested RS and titania)
2. git lurd
3. run around
4. no sound

**Expected behavior**
Lurdu has walking noises and idle sounds

**Actual behavior**
Lurdu doesnt have walking noises and idle sounds

**Screenshots & Video**
Player Video: https://youtu.be/mM1xi4WzIDw - live branch
My video: https://youtu.be/bg9FnqOQrfE - tester

Tester or Live. = Both

**Character Information**
Lurdus at any growth

**Additional Information**
Tested on RS and titania on multiple materials

**Comment by Predatoria** [comment]
I was able to reproduce and fix this in UE.
