### ISSUE TITLE
Kapok_Tree_01  & Kapok_Tree_Small unable to remove after placing using the "erase mode" 

### ISSUE THREAD

**Issue by EkkoEctasy** [BoBAdministration/QA-Bug-Reports#228]
**Describe the Bug**
Using the admin foliage tool, placing down Kapok _Tree_01 & Kapok_Tree_Small and unable to remove them using the erase mode. You can however remove them using the "delete" function when selected, but this removes all kapok trees. 

**To Reproduce**
1. Log in to any server (any canvas map) with Admin build permission
2. Go into spectate and press X to activate build-mode
3. Search "Kapok" in the search bar and select either Kapok_Tree_01 or Kapok_Tree_Small, and place them down on the ground. (any scale)
4. Select the "Erase mode" and try removing these placed trees. 

**Expected behavior**
Kapok Trees should be "erased" upon using the "Erase Mode" 

**Actual behavior**
Kapok Tree stays at said location and can't be removed using the Eraser mode.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/96417223/149362159-b63d38cb-b694-43a9-88f5-c457053f36e8.png)

**Branch Version**
Live version; 1.1.1427

**Additional Information**
Works on any ground type & any map. Weather does not affect this.

**Comment by Predatoria** [comment]
Should be fixed next patch.  Was a data table error
