### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by Peter22FIN** [BoBAdministration/QA-Bug-Reports#23]
**Describe the Bug**
Detes is broken. Pls fix.

**To Reproduce**
1. He is using wrong skins on creatures
2. He is often upside down
3. He is a malfunction

**Expected behavior**
Detes should be like other devs

**Actual behavior**
Detes is a malfunction

**Screenshots & Video**
If applicable, add screenshots to help explain your problem, or attach a video/gif. You can do this by just pasting in your image(s)!

**Branch Version**
Tester and Live.

**Character Information**
Detestation

**Additional Information**
Help

**Comment by tinystarpaws** [comment]
smh 2 stinkee for this world. how dare
