### ISSUE TITLE
[Foliage Tool] Juniper Tree double respawning when removed during floods.

### ISSUE THREAD

**Issue by EkkoEctasy** [BoBAdministration/QA-Bug-Reports#230]
**Describe the Bug**
The "JuniperTree02-03 & 04" respawn twice. Once under the map, and once on the correct spot.  This bug mostly happens when its being removed during a flood, but it's inconsistent/random. It causes the tree to respawn under the mesh (& on the correct spot). The only way to solve it is a server restart. Unable to remove them with the eraser tool.

**To Reproduce**
1.  Go into spectator mode and press X to open the foliage tool
2. Look for "JuniperTree02" (or any JuniperTree) and place them down on the ground
3. Either force a random storm or make it flood. Then knock down the trees. 
4. Wait for them to respawn and check under the mesh. You'll see they respawned under the mesh

**Expected behavior**
Once a tree has been knocked down, it should respawn at the spot it was placed.

**Actual behavior**
Once a tree has been knocked down, it respawns both on top of the mesh and underneath.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/96417223/149657429-90280d62-323e-474d-8211-5b0e21299925.png)
 (Picture was taken during the flood, trees respawned)

**Branch Version**
Live version: 1.1.1427

**Character Information**
/

**Additional Information**
This happened on Rival Shores Canvas.
Weather type: Storm + Flood
The location is in the picture. (desert)

**Comment by Predatoria** [comment]
I haven't been able to reproduce this
