### ISSUE TITLE
Icons duplicate and get stuck on the screen

### ISSUE THREAD

**Issue by Katze-eng** [BoBAdministration/QA-Bug-Reports#231]
**Describe the Bug**
players icons get stuck on your screen if a player respawn in the egg that's in your group

**To Reproduce**
1. get a group with the eggs
2. have 1 or more players take these eggs and force respawn in it
3. repeat this process a few times, by laying new eggs and giving them to a players that force respawn in it
4. let one of this players that is been taking the eggs join your group and hang around
5. this player in your group will randomly start to duplicate it's icon anywhere it walks 

**Expected behavior**
icons should duplicate this way

**Actual behavior**
it duplicates

**Screenshots & Video**
https://yapx.ru/u/QJyKn

**Additional info**
This icons can't be hidden with an I button

**Branch Version**
live and tester

**Comment by Predatoria** [comment]
Found a fix for this. Should be fixed next patch.

**Comment by MarshmallowMaiden** [comment]
Will need to test on server without admin powers
