### ISSUE TITLE
foliage clients desinc

### ISSUE THREAD

**Issue by Katze-eng** [BoBAdministration/QA-Bug-Reports#232]
**Describe the Bug**
Players that playing on a server long enough for eaten foliage to respawn can't see some of it, after it did respawned, only relogging helps with that.
Players that logged in can't see the eaten foliage, for example the eaten trees, which makes them stuck in it since they can't see it

**To Reproduce**
1. Eat the foliage (for example the trees, a lot of them) and wait for it to respawn, only half of it will be respawned
2. Or eat a lot of the trees so there would be an empty logs around, relog and you won't see the most of them

**Expected behavior**
all respawned and eaten trees should be visible for all of the players, doesn't matter for long they are on

**Actual behavior**
not all of the eaten and respawned trees is visible

**Branch Version**
Live

**Additional Information**
It happens with me on AP map, haven't tried that on other maps

**Comment by Predatoria** [comment]
I haven't been able to reproduce this.

**Comment by Vallyhalla** [comment]
This is still happening but still unable to replicate. I've had it happen on Titania as well.
