### ISSUE TITLE
Elasmos abusing interaction button in a fight

### ISSUE THREAD

**Issue by Katze-eng** [BoBAdministration/QA-Bug-Reports#233]
**Describe the Bug**
Elasmos with holding the E button while in the fight (by trying to pick up the objects) increase their aim range for the neck and curve it's head close to the body, so their prey can't fight back

**To Reproduce**
1. spawn as a 1.2+ elasmo
2. get any creature to fight with
3. double tap and hold E
4. while holding E bite the prey

**Expected behavior**
Elasmo neck should increase it's neck range and hide in it's body while it bites the prey

**Actual behavior**
With this bug they can bite they prey and  they can't hit it back

**Screenshots & Video**
(https://youtu.be/Hj_rBxSU9vY)
the normal sized neck
![Снимок экрана (2516)](https://user-images.githubusercontent.com/67237609/149780567-5c9f8ab2-4dfb-4d23-8b17-80fec7f00a95.png)
the neck with an E interaction bug 
![Снимок экрана (2517)](https://user-images.githubusercontent.com/67237609/149780645-2cb52d42-3234-47f1-a615-a337d32ba91c.png)
and this
![b1](https://user-images.githubusercontent.com/67237609/149781465-b7adb526-648d-47d3-856d-d31348ee0459.png)
https://cdn.medal.tv/source/19031890/1629148458-medaltvbeastsofbermuda20210816190307-tr-edit.mp4?t=social&c=202133&missing

**Branch Version**
Tester and Live.

**Comment by Predatoria** [comment]
Cute picture!  I fixed it.
