### ISSUE TITLE
Talents abuse with an aquatic creatures

### ISSUE THREAD

**Issue by Katze-eng** [BoBAdministration/QA-Bug-Reports#234]
**Describe the Bug**
You can get 3/3 or 5/3 in to the bruiser for the mosa or elasmo, get 3/3 aqua affinity and 3/3 aa (from the land creature talent) as an aquatic to have an insane speed, mosa can get an elusiveness, elasmo can get keen senses and so on

**To Reproduce**
1. For example you want to get bruiser and constitution on your mosa
2. Spawn as an ory and put 3/3 points up to brawler and botanic
3. Then you need to open your talent tree AN DON"T CLOSE IT
4. some one should send an invite to be a mosa kiddo
5. accept this invite by still being in the talents menu
6. you will hatch, then you have to wait while your tiny mosa will grow up to 0.440 growth or more
7. put a new points in to the constitution and bruiser
8. close the talents menu
9. CONGRATS you have a mosa with 3/3 bruiser and 3/3 const

**Expected behavior**
you should not be able to get talents from the diff creature or put point earlier that you should to

**Actual behavior**
well you can do it

**Branch Version**
Tester and Live.

**Additional Information**
if you are confused, I can show it to you

**Comment by Predatoria** [comment]
Should be fixed next patch
