### ISSUE TITLE
Server Config for Weather Commonness "0" is false.

### ISSUE THREAD

**Issue by KattofKits** [BoBAdministration/QA-Bug-Reports#235]
**Describe the Bug**
On my server, we have makeshift "seasons" where we randomize the server configs every week to spice things up. This week we rolled a "0" for rain commonness, and it has proven to rain regardless of this setting.

**To Reproduce**
1. Set any live or testing branch server to 0 commonness of rain.
2. Restart the server to update files.
3. Let natural weather take its course.
4. Watch as rain eventually happens.

**Expected behavior**
As stated in the patch notes of "A Very Merry QoL Update" it is stated "The above four variables control how frequent each weather type is. When the weather generator generates a weather event, it selects Rain, Fog, Overcast or DryLightning. Increase or decrease the above numbers to make various weather types more or less common or, at 0, **they will never happen**". Thus rain set to 0 should not happen at all in theory.

**Actual behavior**
Despite server settings being set to 0 on rain commonness, it still rains regardless.

**Screenshots & Video**
https://user-images.githubusercontent.com/90863811/150061376-dde38af5-42cb-4d0f-891b-7fe342e008e7.mp4
My server's settings;
![chrome_YFNfHm0NL9](https://user-images.githubusercontent.com/90863811/150061384-8957c84b-234c-4604-ba17-323f7a3404c4.png)
Patch notes;
![steam_QGK1c4y4LE](https://user-images.githubusercontent.com/90863811/150061412-49b40895-7ba9-4c71-95d4-aef77d2b20d0.png)

**Branch Version**
Live

**Additional Information**
Isle of Wolves - Relax and Chill (Community Server), Rival_Shores, Natural spawning rainstorm

**Comment by Predatoria** [comment]
I tried this and was not able to reproduce it.  I tried in both a cooked build and in UE4.  The settings worked as expected, with no rain.
