### ISSUE TITLE
Holding + on Switch Pro Controller does not open talents

### ISSUE THREAD

**Issue by Rehlik** [BoBAdministration/QA-Bug-Reports#236]
**Describe the Bug**
Holding +(start equivalent) on Switch Pro controller does not open talents.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log in to dedicated testing (not live)
2. Use Switch Pro Controller
3. Hold +(aka start/home)

**Expected behavior**
Holding the button, as per current patch note review, should open the talent menu.

**Actual behavior**
Does nothing. Tried multiple different button holds just to make sure it wasn't a mapping issue and could not get the talent menu to open. (tried +, home, screenshot button, and -)

**Branch Version**
Tester

**Character Information**
N/A

**Additional Information**
Attempted with only a Switch Pro controller, but will add additional info once I test with Playstation and Xbox equivalents.

**Comment by Peter22FIN** [comment]
Make sure that your Switch Pro Controller uses standard Controller-inputs through Steam's settings. + button should be bind to Start button.

**Comment by Peter22FIN** [comment]
Tested on Switch Pro, Xbox One and PS4 controllers. It works fine. Holding start button opens talents. Tapping the button works like Esc-key meaning it opens Esc menu or closes other menus. Check your controller's settings!
