### ISSUE TITLE
[UI/Menu] Shifted status icons when opening the esc menu

### ISSUE THREAD

**Issue by Zi-Mom** [BoBAdministration/QA-Bug-Reports#238]
**Describe the Bug**
If you have more than 8 Icons and the bleed/(Possibly injury as well) icon are on the top row it shifts the bottom row down so it cannot be seen properly.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into creature(Example Para)
2. Get Shrine Pledge
3. Achieve 7 or more positive/neutral icons (In this example I had: Healthy Herbs, balanced diet, water satiation, Near Friends, Satiated, Well Fed, Survival Pledge) 
3. Testing dmg vs a Coah (Anything that does bleed AND injury)
4. Open the escape menu

**Expected behavior**
For the icons to be lined up in neat rows to be able to be seen so one could see what status issues/buffs they have.

**Actual behavior**
Seems that the faded part of the bleed status gets put up top and pushes the bottom row down to where it cannot be seen. 

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/88993347/151206976-3a96d94a-a4d9-4b10-8139-5464f053a177.png)

Example of it not working because of the extra icon ^

![image](https://user-images.githubusercontent.com/88993347/151207075-08ba9c51-5db0-4025-b7ed-2844db90ae05.png)

Example of it working with the bleed being healed. ^

**Branch Version**
Live

**Character Information**
Was a Para on Wild West server during a Safe Zone event, around 1.44+, female, vs a Coah of unknown size.

**Additional Information**
It might have something to do with the bleed icon having the the fade under it and being put on the top. It seems to work find when those negative status are on the bottom though.

**Comment by Predatoria** [comment]
These now always show up at the end of the icon list, so it should be fixed
