### ISSUE TITLE
[Model Glitch] End of Acro tail crunches/bends with ALt

### ISSUE THREAD

**Issue by Zi-Mom** [BoBAdministration/QA-Bug-Reports#239]
**Describe the Bug**
The very tip of the Acro's tail bends/crunches when it uses alt to put its head up. On land it can happen standing or moving, in the water you have to be moving for it to happen.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 1 during live play test (Combat mode)
2. Spawned as Default Male Acro
3. Swim
4. Press Alt to get head to look up while swimming and move camera for crunch tail
5. Get out of water onto land
6. Press Alt and move camera, little tippy tail break

**Expected behavior**
Smooth animations and for the tip of the tail to not be connected to the alt?

**Actual behavior**
Alt is making the tail tip animation bend/crunch strangely

**Screenshots & Video**
https://youtu.be/TGefHAUVFPg
https://youtu.be/ZgAV7KJ2ruQ

**Branch Version**
Public Test (Tester)

**Character Information**
1.2 Acro Male.

**Additional Information**
 Combat testing server Rival Shores, Clear weather

**Comment by Vallyhalla** [comment]
Getting new acro animations soonTM so I'm closing this
