### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by Zi-Mom** [BoBAdministration/QA-Bug-Reports#24]
**Describe the Bug**
A dino walking over burned ground acquires the burned texture overlaid on their creature as a layer

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Find a charred/burned section of ground
2. Walk on top of this spot with any creature
3. You now look pleasantly crisp

**Expected behavior**
The burn texture to stay on the ground and not cover the dino

**Actual behavior**
Texture overlays onto the dino

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/88993347/130489563-1f47c1a2-131a-46e3-8822-7cb812243afc.png)

**Branch Version**
Live

**Character Information**
Pictured - Sai, but can be done with any growth and any dino

**Additional Information**
After fire burned ground

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
