### ISSUE TITLE
Client crashes after leaving spectate in foliage tool.

### ISSUE THREAD

**Issue by KattofKits** [BoBAdministration/QA-Bug-Reports#242]
**Describe the Bug**
Whilst in spectate, and in the foliage tool, trying to leave spectate whilst in the foliage tool crashed my client. 

**To Reproduce**
1. Join any open consol server
2. Enter Spectate
3. Enter Foliage tool
4. Leave spectate without closing foliage tool
5. Crash

**Expected behavior**
A player should be able to leave spectate without crashing, even whilst in the foliage tool.

**Actual behavior**
Client crashes when they don't close the foliage tool before leaving spectate.

**Screenshots & Video**
https://user-images.githubusercontent.com/90863811/152258792-0e54a72d-2881-408c-9814-fb5efd67390c.mp4

**Branch Version**
Live

**Comment by Predatoria** [comment]
I cannot reproduce this on tester branch.
