### ISSUE TITLE
Player "drowns" in a forest fire. 

### ISSUE THREAD

**Issue by KattofKits** [BoBAdministration/QA-Bug-Reports#249]
**Describe the Bug**
Why dying in a fire, it says "drowning" instead of suffocated, which is more accurate to how one dies in a fire if not by the fire itself. Not sure if this is able to be done, but thought I would share!

**To Reproduce**
1. Summon or attend a forest fire on any live branch server
2. Spawn in a fire location
3. Suffocate to death (not on fire)
4. "Drowned"

**Expected behavior**
Dying from suffocation should say suffocation.

**Actual behavior**
Dying from suffocation via fire says "drowned."

**Screenshots & Video**
https://www.youtube.com/watch?v=NcyYfJ-1V0U

**Branch Version**
Live

**Character Information**
1.72+ Bio Megalo

**Additional Information**
Rival_Shores, Forest Fire

**Comment by Predatoria** [comment]
Fixed
