### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by Romanov0** [BoBAdministration/QA-Bug-Reports#25]
As of this recent public patch, ash decals show over creatures

Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Spawn as any creature.
2. Spawn a fire to speed up the process.
3. Walk over to ash covered terrain.
4. Ash terrain layer covers over the skin of the creature.

Ash stays on the ground and the skin is shown normal.

Skin gets covered by the ash ground layer.

https://cdn.discordapp.com/attachments/786600023575232562/870377000219590747/u6IfomaDTyauK8lhKEmXeg.png

Public branch

**Character Information**
Dinosaur growth and type. Include any other relevant character information such as talents, inherits, gender, and stats if necessary.

**Additional Information**
Map type, weather, or any other context about the problem here.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
