### ISSUE TITLE
Meat sticks disappear upon being grabbed

### ISSUE THREAD

**Issue by Falcarius9** [BoBAdministration/QA-Bug-Reports#252]
**Describe the Bug**
The meat sticks disappear from your mouth upon eating

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Spawn as Megaraptor (Possible different animals but have not experienced it)
2. Kill large animal, capable of legging the gore
3. Grab a leg, wait a few seconds
4. The leg will disappear from your mouth

**Expected behavior**
Leg stays in your mouth, allowing you to move and eat

**Actual behavior**
Leg disappears from your mouth, leaving you hungry

**Screenshots & Video**
[

https://user-images.githubusercontent.com/57926053/153771588-3190df6e-121b-40e9-aa5d-71ed9765646a.mp4

](url)

**Branch Version**
Live

**Character Information**
Megaraptor, 1.299
**Additional Information**
Rival Shores

**Comment by tinystarpaws** [comment]
This happens because the large carcass is old. Smaller meat rots at a faster rate than large meat, so the small meat goes bad when you remove it from the gore.
