### ISSUE TITLE
Anti-mesh detection activating on waterfall asset.

### ISSUE THREAD

**Issue by Macarani123** [BoBAdministration/QA-Bug-Reports#256]
**Describe the Bug**
When standing perpendicular in a waterfall, halfway in and halfway out, it prevents hits from registering on whichever end pokes out of the front of the waterfall.

**To Reproduce**
1. Logged onto live branch community server, Etheral Realms.
2. Spawned as a lurd, this also works with  megaraptor and megalo.
3. Travel to a location with a waterfall asset placed down with the foliage editor tool.
4. Position yourself in the waterfall perpendicular to it, halfway in and halfway out. 
5. Have a friend attempt to hit whichever end is sticking out of the front of the waterfall asset.
6. The hit will not register, the anti mesh detection activating.

**Expected behavior**
The waterfall asset should not be acting as if its solid mesh and rejecting hits.

**Actual behavior**
The waterfall ends up rejecting any hits on the half of the creature that is poking out from the front of the waterfall. This is similar to the meadow grass issue from before.

**Screenshots & Video**
First image is perpendicular, second is parallel. 
![20220224055916_1.jpg](https://user-images.githubusercontent.com/96443517/155520257-e4a40251-3ac0-4a96-94de-f162476bfd0c.jpg)
![20220224055924_1.jpg](https://user-images.githubusercontent.com/96443517/155520269-e3ad1b8a-f83f-4c73-989d-ce5f2f151911.jpg)

**Branch Version**
Live.

**Character Information**
-Lurd 1.292
-Lurd 1.0 

**Additional Information**
Map- Ancestral Plains Canvas
Server- Etheral Realms

**Comment by Predatoria** [comment]
Fixed it
