### ISSUE TITLE
Arboreal Nests not breaking after tree is knocked down

### ISSUE THREAD

**Issue by Silemara** [BoBAdministration/QA-Bug-Reports#259]
**Describe the Bug**
Arboreal nests placed on trees do not break after tree is knocked down, and continue to have hit box

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log into any dino that can knock down trees (apa, para, ludu, ect)
2. have a velo place a nest in a tree (must have the arboreal talent)
3.  then knock the tree over with apato
4.  tree vanishes, nest remains floating in the air, does have hit box and can be repaired by owner

**Expected behavior**
tree is knocked down and nest breaks with tree

**Actual behavior**
tree is knocked down and nest remains floating in the air

![image](https://user-images.githubusercontent.com/96402288/156944675-6e5f676d-9bae-40dd-a5ef-9827ca19e664.png)

**Branch Version**
Live

**Character Information**
1.65+ apato

**Additional Information**
nest breaks if tree is eaten, but will remain if tree is picked up or knocked down

**Comment by Vallyhalla** [comment]
This has been fixed! The nest breaks when you knock the trees down now.
