### ISSUE TITLE
MEETING EXAMPLE

### ISSUE THREAD

**Issue by QueenIcy** [BoBAdministration/QA-Bug-Reports#26]
**Describe the Bug**
When a fire has burnt out go to the ashes and walk over them. They will show over your dino.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Start/Wait for a fire to start.
2. Let the fire burn and make some ashes.
3. Wait for the fire to extinguish/extinguish it.
4. Then walk on the ashes and it will show on your dino.

**Expected behavior**
When walking over ashes they should not interact with the player.

**Actual behavior**
When walking over ashes they show over skin and dino.

**Screenshots & Video**
https://cdn.discordapp.com/attachments/786600023575232562/870377000219590747/u6IfomaDTyauK8lhKEmXeg.png

**Branch Version**
Most recent public Patch

**Character Information**
Growth and size does not matter.

**Additional Information**
All maps, after fires.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
