### ISSUE TITLE
Velociraptor collides with certain foilages that shouldn't be collided with

### ISSUE THREAD

**Issue by ITechnicPyroI** [BoBAdministration/QA-Bug-Reports#263]
**Describe the Bug**
When you're a velociraptor and try to walk through certain bushes such as SM_Fern_01, SM_Fern_04, SM_BushA_01
you will collide and get stuck inside of them. It does this with all sizes of velociraptor however does not do this on any other dino.

**To Reproduce**
1. Logged onto an open console live server.
3. Placed down bushes SM_Fern_01, SM_Fern_04, SM_BushA_01
4. Spawned on a velociraptor (any size works)
5. Attempt to walk into bushes.

**Expected behavior**
Bushes should allow the Velo to pass through.

**Actual behavior**
Velo gets stuck instead, walks ontop of the bushes, or cannot pass through.

**Screenshots & Video**
Had to post these in a dropbox cause they were too big

https://www.dropbox.com/s/fkdlmyyabj6mdcm/BeastsOfBermuda%20Development%20%202022-03-23%2022-30-22_Trim%20%282%29.mp4?dl=0
https://www.dropbox.com/s/q5gd75l084k4aw0/BeastsOfBermuda%20Development%20%202022-03-23%2022-42-46.mp4?dl=0

**Branch Version**
Live, both most likely works.

**Character Information**
Velociraptor, any size works. 
**Additional Information**
We tested it with all smaller dinos and it only worked for velociraptors. We also tested with all bushes possible to make sure that it was only these select three.

**Comment by Vallyhalla** [comment]
This has been fixed!
