### ISSUE TITLE
Megaraptor's Neck clipping through itself while calling during swimming

### ISSUE THREAD

**Issue by ITechnicPyroI** [BoBAdministration/QA-Bug-Reports#264]
**Describe the Bug**
When in certain calls such as the two call while swimming or in a vertical position, the megaraptor's neck will clip heavily through itself.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log onto any server.
2. Get into any water source.
3. Swim upwards to where your body is vertical
4. Use your friendly call.

**Expected behavior**
You should play the two call animation just fine.

**Actual behavior**
The megaraptor's neck will clip in and out of it's mouth and will intensify if it is fat.

**Screenshots & Video**
https://user-images.githubusercontent.com/48891088/159837238-36d3cf24-fb75-445a-9b3a-9390c41d527d.mp4

**Branch Version**
Live

**Character Information**
Megaraptor, 1.2

**Comment by Vallyhalla** [comment]
Spoke to Lifeon about this and since it's not her model there's nothing she can do about it. It has to do with how the morphs were made.
