### ISSUE TITLE
The names of the parents in "Possess the egg?" message are not correct

### ISSUE THREAD

**Issue by Akaraasaur** [BoBAdministration/QA-Bug-Reports#267]
**Describe the Bug**
When selecting an egg from two parents, the associated message ("Possess the egg?" message) does not give the correct names of the parents. It gives the name of other parents that have recently nested (of the same kind of dino or another dino) or shows the parents as being offline when they are actually present on the server.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged on any server on the live branch
2. Spawned as any dino (.8+ dino) and mate with the same dino of the opposite gender, lay eggs.
3. Go to the Creature select menu and create a new dinosaur, select the previous eggs.
4. It should show the parents as offline or the name of other nesting players.

**Expected behavior**
The message should tell me the correct names of my parents

**Actual behavior**
The associated message does not give the correct names of the parents or other parents names.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/96403359/160876997-55ca448d-1525-449f-b541-c9c88812b1a6.png)
![image](https://user-images.githubusercontent.com/96403359/160877037-50ed4328-bc69-43b1-a9ad-2291404a5011.png)

**Branch Version**
Live branch

**Character Information**
1.2+ paras on both screens.

**Additional Information**
Any map, any server.

**Comment by Vallyhalla** [comment]
This is still happening!
