### ISSUE TITLE
Megaraptor animation bug while moving & eating

### ISSUE THREAD

**Issue by theriversedge** [BoBAdministration/QA-Bug-Reports#268]
**Describe the Bug**
Megaraptor slides along the ground if it moves while eating

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log into any live server
2. Spawn in as a Megaraptor
3. Find something to eat, whether that's a flower, crystal, or carcass
4. Begin eating, release the eat key, then start moving

**Expected behavior**
The walk animation should be playing while the eat animation finishes playing

**Actual behavior**
The walk animation does not play while the eat animation finishes playing

**Screenshots & Video**
N/A

**Branch Version**
Live

**Character Information**
Megaraptor

**Additional Information**
N/A

**Comment by Predatoria** [comment]
Can't reproduce it.  Maybe it was fixed on tester
