### ISSUE TITLE
Stray vertice on max fat Megaraptor

### ISSUE THREAD

**Issue by theriversedge** [BoBAdministration/QA-Bug-Reports#269]
**Describe the Bug**
A stray vertice appears on Megaraptor's throat while it is sitting and max fat

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log onto any server
2. Spawn in as a Megaraptor and grow to 1.2
3. Eat until max fat
4. Play the sit animation and view the throat area for the stray vertice

**Expected behavior**
There are no stray vertices on Megaraptor's max fat morph

**Actual behavior**
There is a stray vertice on Megaraptor's max fat morph in the throat area

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/55609311/161407611-ffd5a4a0-b1be-4cd6-a1bc-883569afaf58.png)

**Branch Version**
Live

**Character Information**
1.2 Megaraptor with max food/fat

**Additional Information**
N/A

**Comment by Vallyhalla** [comment]
This is still a thing! Will have to get Lifeon to take a look at this sometime.
