### ISSUE TITLE
Meeting example

### ISSUE THREAD

**Issue by Katze-eng** [BoBAdministration/QA-Bug-Reports#27]
**Describe the Bug**
Velos climbing through the textures

**To Reproduce**
1. Spawn as a velo any size
2. Jump on some wall that have a stone/rock clipped to this wall
3. Climb closer to this object
4. You would be able to get through it/inside of it

**Expected behavior**
Velo will not be able to move if there is an object in front of it

**Actual behavior**
Velo will go through the object

**Screenshots & Video**
Nu

**Branch Version**
Tester and Live.

**Character Information**
Velo, any growth type

**Additional Information**
Any map

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
