### ISSUE TITLE
Admin commands seem to remove the UI indicating relationship

### ISSUE THREAD

**Issue by Falcarius9** [BoBAdministration/QA-Bug-Reports#272]
Describe the Bug
When I was playing on Encompass, I decided to nest with Agony, a male Coah. After some growing with my kids, they started getting a couple negatives. We found it weird and decided to check our relationship. It turns out Agony was my father but they did not know due to the Family UI not showing up for them, only for me. ( I forgot to check beforehand too)

To Reproduce

- Use admin commands on a certain creature (Known ones in this instance is the gender change command)
- Upon using this command, the UI for Family will disappear for the affected player
- The relationships will still apply but the UI will be gone

Expected Behavior:
- The UI stays up regardless of admin commands, allowing players to realize they're doing the incest

Actual behavior:
- The UI disappears for the affected player, tricking players into the incesty-westy

Screenshots & Video

![image](https://user-images.githubusercontent.com/57926053/162084681-7bb946a2-3205-4579-be2c-32f4e130196e.png)
(What I see)

![image](https://user-images.githubusercontent.com/57926053/162084707-66ac96d1-3d6d-4031-b64d-056a4c59d322.png)
(What they see)

**Comment by Predatoria** [comment]
I can't seem to reproduce this
