### ISSUE TITLE
SetBind is bypassing the FOV limitations

### ISSUE THREAD

**Issue by Falcarius9** [BoBAdministration/QA-Bug-Reports#274]
**Describe the Bug**
SetBind is bypassing the FOV limitations, and it does not print bound admin commands used

**To Reproduce**

- Press ~ and open console
- SetBind any button to "FOV 30" and "FOV 120"
- These buttons will now zoom in and out 

**Expected behavior**
FOV is limited, unable to zoom in or out

**Actual behavior**
With SetBind enabled, the player is able to zoom in and out with their camera

**Screenshots & Video**
[If applicable, add screenshots to help explain your problem, or attach a video/gif. You can do this by just pasting in your image(s)!]

(https://www.reddit.com/r/BeastsofBermuda/comments/u06pxy/useful_console_commands/?utm_medium=android_app&utm_source=share)

**Branch Version**
Live

**Character Information**
Any character type

**Additional Information**
Map type, weather, or any other context about the problem here.

**Comment by Predatoria** [comment]
blocked it
