### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by MysteryKit66** [BoBAdministration/QA-Bug-Reports#28]
**Describe the Bug**
Ash decals show over creatures

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. ex. Logged in a server
2. ex. Spawned as a Sai in forest
3. ex. Walked on a burned path 
4. ex. Sai got covered in Ash

**Expected behavior**
Sai should walk over the covered ash ground without getting it on them

**Actual behavior**
Sai gets covered in ash decals while walking on a ashful ground

**Screenshots & Video**
![AshSai](https://user-images.githubusercontent.com/89144000/130489975-4bc49e83-06ef-4aa9-bdc0-1e2a8908cd8c.png)

**Branch Version**
Live

**Character Information**
Sai, 1.3

**Additional Information**
Rival_Shores, forest

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
