### ISSUE TITLE
Lurd doesn't take leg hits.

### ISSUE THREAD

**Issue by Vallyhalla** [BoBAdministration/QA-Bug-Reports#280]
**Describe the Bug**
When playing Lurdu you will not receive leg hits, it's always body hits or tail hits.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 
2. Spawned in as 1.2 Lurdu.
3. Had a Megalo bite me on the legs.
4. Only received body or tail hits.

**Expected behavior**
When hitting a Lurd's leg it should deal a leg hit.

**Actual behavior**
Hitting a Lurd's leg only registers as a body or tail hit.

**Screenshots & Video**
https://www.youtube.com/watch?v=xxwA4N_pB9s&ab_channel=Lynann

**Branch Version**
Live.

**Comment by themurdock13** [comment]
attempted multiple times with lurdu at 1.2 and 4.0  and meglo rangering in size and unable to receive a single leg hit 
https://youtu.be/EsqzXtIUz8M

**Comment by Vallyhalla** [comment]
Fixed with remodel!
