### ISSUE TITLE
Megaraptor gets stuck glowing when it gets sniffed while evading

### ISSUE THREAD

**Issue by Alyrius** [BoBAdministration/QA-Bug-Reports#286]
**Describe the Bug**
When you sniff a megaraptor and then it does the evade, it keeps the fullbody glowing. Nice to abuse in combat because they cant hide well anymore

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. make 1 Megaraptor, 1 other
2. sniff the Megaraptor
3. Megaraptor evades WHILE it is being sniffed
4. Glowyraptor

**Expected behavior**
Megaraptor is not a Glowstick

**Actual behavior**
Megaraptor is a glowstick

**Screenshots & Video**
https://youtu.be/Yqh1eutJpis

**Branch Version**
Live

**Character Information**
1 megaraptor, 1 other

**Additional Information**
Nothing else matters

**Comment by Predatoria** [comment]
fixed it
