### ISSUE TITLE
Spectator presence triggers Big Creature warning

### ISSUE THREAD

**Issue by CeciliaSE** [BoBAdministration/QA-Bug-Reports#287]
**Describe the Bug**
When logging onto a creature in the area of a spectator, the warning for nearby creatures pops up on the selection screen.

**To Reproduce**
1. Log onto any server on Live branch
3. Enter spectate and go to the location of an existing creature that is not spawned in yet
4. Have someone spawn in on the existing creature.
5. The message should appear.

**Expected behavior**
I expected the game to ignore the spectator cam, as it is not a dino in the game and cannot do damage.

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshots & Video**
https://www.youtube.com/watch?v=fWFhBLBKIqc 

**Branch Version**
Live

**Character Information**
Ptera 1.8

**Additional Information**
Initially tested on RS canvas map, the weather has no effect on the issue.

**Comment by Predatoria** [comment]
fixed it
