### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by TeacupDreams** [BoBAdministration/QA-Bug-Reports#29]
**Describe the Bug**
Ash decals show over regular skin.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Spawn in on any dino.
2. Normal decals should show but they do not.

**Expected behavior**
Normal decals should show on dino

**Actual behavior**
Ashen decals show instead

**Screenshots & Video**
owo 

**Branch Version**
Tester and Live

**Character Information**
Sai - 1.2(maybe it looks 1.2)

**Additional Information**
Any map after a fire.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
