### ISSUE TITLE
Akro roar does not work in duels on your oponent if you are grouped with them

### ISSUE THREAD

**Issue by Alyrius** [BoBAdministration/QA-Bug-Reports#290]
**Describe the Bug**
Akro roar cannot be used in a duel, if the 2 duelling parties are in a group with each other

**To Reproduce**
1. make akro and enemy
2. go get grouped together
3. duel and attempt to roar
4. doesnt work

**Expected behavior**
Can use roar for duels 

**Actual behavior**
Cant use roar in grouped duels

**Screenshots & Video**
https://youtu.be/KDtvvvxJLoM

**Branch Version**
both

**Character Information**
Any acro and any other dino in a group

**Additional Information**
/

**Comment by KattofKits** [comment]
This also does not work for grouped paras with their call ability.
