### ISSUE TITLE
Creatures cannot knock over uneaten trees

### ISSUE THREAD

**Issue by Vallyhalla** [BoBAdministration/QA-Bug-Reports#291]
When running into any trees you do not knock them over unless they are eaten.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged any Live Branch server.
2. Spawn in on a sai
3. Run into a tree
4. tree does not get knocked over

**Expected behavior**
When running through a tree you knock it over regardless of it being eaten or not

**Actual behavior**
When running through an uneaten tree it does not get knocked down.

**Screenshots & Video**
If applicable, add screenshots to help explain your problem, or attach a video/gif. You can do this by just pasting in your image(s)!

**Branch Version**
Live.

**Character Information**
Tested as my 1.9 sai on live branch, but it was happening with other creatures including large carnivores.

**Additional Information**
Map type, weather, or any other context about the problem here.

**Comment by Predatoria** [comment]
I'm unable to reproduce this.  Sai can knock down trees at 1.2, and cannot at 1.0.
