### ISSUE TITLE
Egg vision is broken

### ISSUE THREAD

**Issue by Vallyhalla** [BoBAdministration/QA-Bug-Reports#293]
**Describe the Bug**
When sitting in an egg and press K to remove the HUD your view seems as if you're underwater.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log onto any server.
2. Become an egg.
3. Press K.
4. Look around and your vision is as if you're underwater

**Expected behavior**
When hitting K your vision should be normal.

**Actual behavior**
When hitting K your vision is as if you're underwater.

**Screenshots & Video**
![eggvis](https://user-images.githubusercontent.com/96442596/166151216-353bcac1-57fc-47a5-a786-dfc99aed27e4.png)

**Branch Version**
Live.

**Character Information**
Dinosaur growth and type. Include any other relevant character information such as talents, inherits, gender, and stats if necessary.

**Additional Information**
AP map.

**Comment by Predatoria** [comment]
Vipe fixed it
