### ISSUE TITLE
Duel with egg

### ISSUE THREAD

**Issue by Akaraasaur** [BoBAdministration/QA-Bug-Reports#295]
**Describe the Bug**
You can start a duel with someone in an egg.

**To Reproduce**
1. Logged into any server
2. 1 player spawn as a creature and the other take an egg and stay inside
3. The player with the creature request a duel with the egg and if the egg confirm they can fight in a duel.

**Expected behavior**
You can't start a duel with an egg.

**Actual behavior**
You can start a duel with an egg.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/96403359/166248183-3e3b03af-9bc8-4c98-b3e6-e68fde21924b.png)

**Branch Version**
Live

**Character Information**
1 dinosaur of any growth + 1 player in an egg.

**Additional Information**
Any map, weather.

**Comment by Predatoria** [comment]
Not a bug.  We thought it was funny.
