### ISSUE TITLE
mosa ignors slopes

### ISSUE THREAD

**Issue by Arko3** [BoBAdministration/QA-Bug-Reports#297]
**Describe the Bug**
mosa visual bug where is not aline with the ground
**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. ex. Logged into Dedicated Testing 3
2. ex. Spawned mosa
3. ex. walk on land
4. ex. mosa stays straigt

**Expected behavior**
mosa leans to the side of the slop

**Actual behavior**
stay straigt
**Screenshots & Video**
![image](https://user-images.githubusercontent.com/96443166/166336903-86ca3431-5b62-4754-95ed-aa02cb6a3430.png)

**Branch Version**
Tester both Live.

**Character Information**
mosa
**Additional Information**
rs

**Comment by MarshmallowMaiden** [comment]
Confirmed fix on tester
