### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by Lazulie14** [BoBAdministration/QA-Bug-Reports#30]
As of this recent public patch, ash decals show over creatures

To Reproduce
1. Spawn and put out any fire
2. Spawn as any creature
3. Stand on the ash decal
4. Ash decal will cover over the players creature

Expected behavior
Ash covering the ground and foliage only

Actual behavior
Ash covers the player

Branch Version
Live.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
