### ISSUE TITLE
Portals allow a "cheat" for travel distance trial.

### ISSUE THREAD

**Issue by finchye** [BoBAdministration/QA-Bug-Reports#301]
**Describe the Bug**
When using a portal, travel distance trail increases by the amount of distance between the portals.

**To Reproduce**
1. Join any rival shores map that has portals enabled.
2. Spawn in on any dino with the travel distance trial.
3. Teleport or travel to either portal at desert mountain or jungle cave.
4. Note what your travel distance is.
5. Enter the portal.
6. Wait for the next growth tick
7. Note that the travel distance has gone up a significant amount.

**Expected behavior**
Travel distance should remain normal and only move a few meters.

**Actual behavior**
Travel distance jumps ahead as if the dino is traveling between portals rather than teleporting.

**Screenshots & Video**
(https://www.youtube.com/watch?v=XjmVNjchkgA&ab_channel=finch)

**Branch Version**
Live.

**Character Information**
Dino shown in the clip is a fresh spawn 0.4 acro on the open console 200 server.

**Additional Information**
Map is rival shores but works on other maps too.

**Comment by Predatoria** [comment]
The amount it goes up by is the same amount you'd go up by if you sprinted for the duration of the growth tick in one direction.

It's working as intended, and is not adding the distance between the portals to your distanced traveled Trial.
