### ISSUE TITLE
Trials "Text Block" Placeholder Text

### ISSUE THREAD

**Issue by Rendezvousxx** [BoBAdministration/QA-Bug-Reports#302]
**Describe the Bug**
When pulling up the trial screen, the placeholder text 'Text Block' can be found underneath Trials.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log onto live server
2. Open up the character stat menu
3. View the trials of the character

**Expected behavior**
There shouldn't be placeholder text underneath Trials

**Actual behavior**
'Text Block' is present underneath Trials

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/96402225/167876358-fdeabc26-d69f-4918-a4df-c55a5b856d53.png) referenced from Bunnimorph on Official Discor d

**Branch Version**
Live

**Character Information**
N/A

**Additional Information**
N/A

**Comment by Zelryn** [comment]
Confirmed Fixed on Tester Branch.
