### ISSUE TITLE
Dino stays in-game after safe logging through exit game

### ISSUE THREAD

**Issue by Skyedrago** [BoBAdministration/QA-Bug-Reports#304]
**Describe the Bug**
Entity stays in-game after safe logging with exit game

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Play as any dino
2. Select Quit Game
3. Wait for the safe log timer
4. You will successfully exit the game, but your dino will stay in-game and can be damaged/killed

**Expected behavior**
Dino disappears due to safe logging

**Actual behavior**
Dino stays in-game

**Screenshots & Video**

**Branch Version**
Live.

**Character Information**
The dino tested was a 1.214 acro per the report by the player

**Additional Information**
Originally reported to the in-game GitHub https://github.com/Thy-Vipe/BeastsOfBermuda-issues/issues/10153

**Comment by Vallyhalla** [comment]
Could not replicate. Closing this since there's multiple of these open.
