### ISSUE TITLE
Exceeding Carry Weight with Fish

### ISSUE THREAD

**Issue by Skyedrago** [BoBAdministration/QA-Bug-Reports#306]
**Describe the Bug**
Dinos can exceed carry weights

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Spawn as something that can carry fish (I chose elasmo based on the in-game bug report)
2. Grow to 1.2
3. Pick up fish
4. You will be able to exceed your carry weight. I had a carry weight of 923 and was able to continue to pick up fish way over that

**Expected behavior**
Dino cannot exceed their carry weight

**Actual behavior**
Picking up fish lets you far exceed your carry weight, as well as continue to move

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/96404852/168413502-dbea1e5c-00fa-4388-8b4a-b7b025315d5a.png)
![image](https://user-images.githubusercontent.com/96404852/168413514-fa551846-2a70-443a-8a1e-453fcd09433f.png)
The first image was taken very shortly before the second. Also note the carry weight does not match between pictures

**Branch Version**
Live.

**Character Information**
Elasmo. This dino had speed inherits and a pure mobility build

**Additional Information**
Map is presumably irrelevant
Report originally made here: https://github.com/Thy-Vipe/BeastsOfBermuda-issues/issues/10018

**Comment by Predatoria** [comment]
It sounds like this is actually deliberate.  Without it, fish are too heavy for the flyers to pick up so we bypassed the check for fish.
