### ISSUE TITLE
New para emote allow player to get up faster

### ISSUE THREAD

**Issue by Akaraasaur** [BoBAdministration/QA-Bug-Reports#308]
**Describe the Bug**
When the new para emote animation is running, the player can get up faster than when it's not running.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Spawn as a para
2. Have 80+% comfort while sitting
3. Play the new para emote (dancing while sitting)
4. Press W (or any other key that allows you to stand up)

**Expected behavior**
Getting up with the emote should be as fast as without.

**Actual behavior**
The player can get up more quickly by having the emote activated.

**Screenshots & Video**
https://youtu.be/v1cBqRpo2Wc

**Branch Version**
Live

**Character Information**
Para with 80+ comfort

**Additional Information**
The player has to hit the "unjam" button to move after getting up but it still faster than without the emote. This bug seems to be random, I could replicate it twice.

**Comment by Predatoria** [comment]
I can't seem to reproduce this.
