### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by OverlordGrima** [BoBAdministration/QA-Bug-Reports#31]
**Describe the Bug**
Walking over ash overwrites the decal onto the character model

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Walked onto ash coated ground
2. decal of ash coated character model
**Expected behavior**
Character skin would stay the same

**Actual behavior**
Ash covered character skin

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/89408428/130490319-10f5e5c7-7a0a-45ca-b8b2-3bff6d7b1d9b.png)

**Branch Version**
Live

**Character Information**
N/A

**Additional Information**
shimmer still shows through the ash

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
