### ISSUE TITLE
Destroyed eggs in burrows cannot be eaten

### ISSUE THREAD

**Issue by CeciliaSE** [BoBAdministration/QA-Bug-Reports#312]
**Describe the Bug**
When destroying an egg in a burrow, the egg cannot be eaten and instead makes the velo shuffle forward when repeatedly holding F to eat.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log onto a live branch server. Confirmed replication on RS canvas and RS
2. Spawn a velo, talents does not matter
3. Grab an egg (we did apa and ory eggs) and destroy it in the burrow
4. It will be inedible when broken in the burrow
5. You can also hold F, release and wait just long enough to not grab, hold F again.
6. Shuffle time

**Expected behavior**
I can eat the egg.

**Actual behavior**
I cannot eat the egg.

**Screenshots & Video**
https://www.youtube.com/watch?v=vFV7RUBkRU0 
https://www.youtube.com/watch?v=qWiS73vw9NU 

**Branch Version**
Live.

**Character Information**
Dinos used- 2 1.2 Orys, 1 1.2 Apas, 1 1.2 velo, **any build**

**Additional Information**
Confirmed on RS canvas, RS.

**Comment by Peter22FIN** [comment]
Reminder: Tester patch needs to be cooked first
