### ISSUE TITLE
Strange Tree Collision with builder tool. SM_Tree_Large_2 specifically.

### ISSUE THREAD

**Issue by Sonatasuarus** [BoBAdministration/QA-Bug-Reports#315]
**Describe the Bug**
SM_Tree_Large_2 leaves an invisible box of collision when knocked over.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Enter Live Branch Server. (We have a canvas map)
2. Open the foliage tool.
3. Place SM_Tree_Large_2.
4. Use a large dinosaur that can knock over trees, knock over the tree and re-enter the place it had been standing.

**Expected behavior**
You should walk right through the vacant space without trouble.

**Actual behavior**
There's still an invisible mesh your dinosaur catches on and cannot pass through where the knocked-down tree was standing.

**Screenshots & Video**
(https://youtu.be/f8nYX80y3oE)

**Branch Version**
Live.

**Character Information**
1.2 Apa (admin spawned) 

**Additional Information**
Canvas map, Forest Island. Has been giving dinos of all growths issues though, Apas, Sais, and Rexes for sure.

**Comment by Predatoria** [comment]
I cannot reproduce this.  It's likely another issue unrelated to SM_Tree_Large_2
