### ISSUE TITLE
Bush Collision SM_BushA_01

### ISSUE THREAD

**Issue by Sonatasuarus** [BoBAdministration/QA-Bug-Reports#316]
**Describe the Bug**
his bush SM_BushA_01 has collision with velos so they can get stuck if you put 2 or more of these bushes together.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Enter a live-branch server.
2. Open Foliage Tool, place **two** or more SM_BushA_01 beside each other.
3. Spawn in a velo and try walking through the bushes.

**Expected behavior**
Velo should be able to pass right through the bushes.

**Actual behavior**
Velo will get caught between the bushes and cannot escape.

**Screenshots & Video**
https://youtu.be/28BxUWGG3ow

**Branch Version**
 Live.

**Character Information**
2.0 Velo

**Additional Information**
Forest Island Canvas map, velos of different sizes get caught in the bushes.

**Comment by Vallyhalla** [comment]
This is still happening, confirmed with a Velo but it doesn't do it with Ory. Must have something to do with Velo climbing and collision mechanic. Closing this for now.
