### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by Sa0327** [BoBAdministration/QA-Bug-Reports#32]
Describe the Bug
Ash on creatures skin

To Reproduce
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.

ex. Log in a server
ex. Spawn as a Sai in forest
ex. Walk on a burnt ground
ex. Sai get ash on skin
Expected behavior
Sai should not get the ash on the skin

Actual behavior
Sai get ash on the skin when walking on a burnt place

Screenshots & Video
![image](https://user-images.githubusercontent.com/89346413/130490867-1f949bdd-71b4-4bd4-ac54-adca9dfeff08.png)

Branch Version
Live

Character Information
1.3 growth Sai

Additional Information
Rival_Shores, Forest

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
