### ISSUE TITLE
Foliage tool scatter duplication glitch

### ISSUE THREAD

**Issue by CeciliaSE** [BoBAdministration/QA-Bug-Reports#322]
**Describe the Bug**
When using the scatter tool, erasing some of the placed assets and restarting the server causes the items to duplicate in the foliage file. The duplicated assets do not appear on the map, since they technically do not exist at all. Over time, the duplications cause servers to double and triple in size compared to what they are supposed to be, and fps issues start to run rampant.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log into a server. As of May 26th it can be any branch, but for future reference _should be on live_
2. Enter spectate and open the foliage tool (X)
3. Pick the scatter tool with an asset that does not duplicate on its own.
4. Example assets you can use include bush05, Flower1-5
5. Place the chosen asset on the ground with the scatter tool
6. Erase **SOME** of the asset. (ex. place 20, erase 10)
7. Wait 5 minutes and restart the server
8. The file size should go up, but the plants that have been added to the file does not show on the map because they do not actually exist

**Expected behavior**
The scatter tool can be used normally without issues.

**Actual behavior**
Using the scatter and erasing some scattered assets cause a duplication, over time increasing the load time and file size to ludicrous levels. This can render a map completely unplayable, with FPS issues and load times dissuading people from playing and using the tool.

**Screenshots & Video**
https://www.youtube.com/watch?v=1nVslkXy8cc

**Branch Version**
Live and tester

**Character Information**
None needed

**Additional Information**
Replicated on tester RS, confirmed happening on RS canvas as well. Fire does not cause an asset duplication

**Comment by Predatoria** [comment]
Fixed it!
