### ISSUE TITLE
Invisible wall at River, AP

### ISSUE THREAD

**Issue by Akaraasaur** [BoBAdministration/QA-Bug-Reports#326]
**Describe the Bug**
There's an invisible wall on a rock at River on Ancestral Plains Map. You can't pass through when the tide is low and you're walking on the rock. There is no problem when swimming.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Go to a server with Ancestral Plains map
2. Go to this coords : X:184978 Y:17371 Z:1851
3. Wait for low tide and try to walk on the rock to go into the ocean

**Expected behavior**
You can walk freely on the rock and go to the ocean at low tide (when walking on the rock)
**Actual behavior**
You can't pass through this invisible wall to go to the ocean at low tide (when walking on the rock)

**Screenshots & Video**
https://youtu.be/Iua27Wyd_vk

**Branch Version**
Tester and Live

**Character Information**
1.5 female lurdusaurus

**Additional Information**
Ancestral plains at low tide (when walking on the rock)

**Comment by Vallyhalla** [comment]
This is still happening, not sure what's blocking the rock.

**Comment by Predatoria** [comment]
put a bigger rock on it
