### ISSUE TITLE
Para is always male in the Character section

### ISSUE THREAD

**Issue by Skyedrago** [BoBAdministration/QA-Bug-Reports#332]
**Describe the Bug**
Para does not switch to the female model in the Growth Preview

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log into a live server (any map)
2. Choose para in the creature select
3. Select Female
4. Go to Character
5. Raise the growth of the para until sexual dimorphism is noticeable (I chose 1.2 since the model is fully developed by this point)
6. The para has the male model

**Expected behavior**
The preview for para switches between male and female depending on what the player has selected (or is random if Random is selected)

**Actual behavior**
The para is always male

**Screenshots & Video**
![20220714005506_1](https://user-images.githubusercontent.com/96404852/178902588-96d0484b-2403-423a-8381-523aef08f9fd.jpg)
![20220714005511_1](https://user-images.githubusercontent.com/96404852/178902592-6c903ba4-3962-448b-bbc5-b769f7ed131c.jpg)

**Branch Version**
Live

**Character Information**
Para with noticeable sexual dimorphism. Female should be selected because the model defaults to male. Stats, talents, etc. are irrelevant since the character has not been spawned.

**Additional Information**
None

**Comment by Thy-Vipe** [comment]
Implemented required scalable code to address this. Was an oversight.

**Comment by Skyedrago** [comment]
Para now properly shows male and female as adults, however, female para up through adulthood has an altered crest.

![20220801214030_1](https://user-images.githubusercontent.com/96404852/182273691-a7e79706-32a0-4bba-a5c1-863a91bd49e4.jpg)
![20220801214043_1](https://user-images.githubusercontent.com/96404852/182273695-8318bb71-ed5d-454e-9e66-707ba95e99c6.jpg)
Comparison of male and female para at 0.1 growth showing greatest model distortion. First picture is male, second is female

![20220801214035_1](https://user-images.githubusercontent.com/96404852/182273693-b41fb773-0ddc-4407-a1c5-b341b83bcbed.jpg)
![20220801214039_1](https://user-images.githubusercontent.com/96404852/182273694-66ce05f1-b1cd-4bfe-8e55-45b58326c23d.jpg)
Comparison of male and female para at 0.4 growth showing female para without a crest. First picture is male, second is female

![20220801214219_1](https://user-images.githubusercontent.com/96404852/182273699-d9e8c90c-1b8c-4543-9d2c-1f218cf88f86.jpg)
![20220801214216_1](https://user-images.githubusercontent.com/96404852/182273697-398360fb-ae75-4470-9a19-1b9f9bef6690.jpg)
Comparison of male and female para at 0.8 growth showing female para with a crest, but it is largely inside the head. First picture is male, second is female
