### ISSUE TITLE
Quit Game Safe Log leaves you in game.

### ISSUE THREAD

**Issue by Zi-Mom** [BoBAdministration/QA-Bug-Reports#337]
**Describe the Bug**

**To Reproduce**
1. Log into any server where you do not have admin/dev permissions
2. Spawn as any creature
3. Safe log with someone in VC with you and in game watching your model
4. Tell them you have left the game and ask if your dino is still there

**Expected behavior**
For the safe log when pressing the Quit Game button to work and get your character out of there

**Actual behavior**
Your dino is left in game even when you have left the server and closed the game. It stays for up to about 5 min

**Screenshots & Video**
There isn't a video however it is easily reproduced and consistent. 

**Branch Version**
Live.

**Character Information**
This is from Vipe's Github as well where someone safelogged and came back to a dead creature.
https://github.com/Thy-Vipe/BeastsOfBermuda-issues/issues/10216

**Additional Information**
Map type, weather, or any other context about the problem here.

**Comment by Skyedrago** [comment]
https://github.com/BoBAdministration/QA-Bug-Reports/issues/304 Commenting to link a previous report on this issue!
Also linking the in-game reporting GitHub report: https://github.com/Thy-Vipe/BeastsOfBermuda-issues/issues/10153
