### ISSUE TITLE
Auroraceratops Sands Everyone

### ISSUE THREAD

**Issue by Falcarius9** [BoBAdministration/QA-Bug-Reports#338]
**Describe the Bug**
Auroraceratops sands everything within the area that is not in the Aurora's group.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.

1. Possess or spawn in as an Auroraceratops
2. Go into a group of people that you are not packed with
3. Press right click
4. Sand everyone

**Expected behavior**
Sand specific people that the attack is aimed at

**Actual behavior**
You can shotgun blast the sand attack and get everything within a certain radius

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/57926053/181864987-bd861392-63c8-48b6-8f0a-f6ad5be147f3.png)
![image](https://user-images.githubusercontent.com/57926053/181865032-a0861907-8042-46e4-b9c9-e92776ee6a4b.png)

**Branch Version**
Tester

**Character Information**
- Auroraceratops
- 1.2 Growth

**Additional Information**
Titania Map
Clear weather

**Comment by Predatoria** [comment]
This is an AOE attack.  It works similarly on Ory.
