### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by o0Sazie0o** [BoBAdministration/QA-Bug-Reports#34]
**Describe the Bug**
Ashen decal issue by standing on ash

**To Reproduce**
Spawn fire, wait for ash to show on ground. Step on ash and ashen decal shows on Sai.

**Expected behavior**
Expected to show on plants.

**Actual behavior**
Weird ashen decal shows on dino players, while stepping on ash.

**Screenshots & Video**
![u6IfomaDTyauK8lhKEmXeg](https://user-images.githubusercontent.com/89360119/130503264-12b44613-b3bf-48a4-9c3a-e9d37e8d56ed.png)

**Branch Version**
Live

**Character Information**
Dinosaur growth is 1.2, full power build with two power inherits. Gender male Sai.

**Additional Information**
Clear weather on Rival Shores.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
