### ISSUE TITLE
Adrenaline working the opposite on Coah

### ISSUE THREAD

**Issue by Akaraasaur** [BoBAdministration/QA-Bug-Reports#341]
**Describe the Bug**
When you have enough damage on your coah for Adrenaline to activate, you actually do less damage to your opponent.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log on an adult coah with 3/3 adrenaline
2. Fight or duel an other player
3. When low on health you do less damage to your opponent.

**Expected behavior**
You should do more damage to your opponent when you are low health and with points invested in adrenaline.

**Actual behavior**
You do less damage to your opponent when you are low health and with points invested in adrenaline.

**Screenshots & Video**
My friend and I were testing how adrenaline works with our coahs. His coah is 2.0 with 3/3 adrenaline and 3/3 Thick hide. My coah is 1.7 with 5/3 adrenaline and 3/3 thick hide. We were in duel.

https://youtu.be/m0PEtjxiJ08

**Branch Version**
Live.

**Character Information**
 Green bio coah is 2.0 with 3/3 adrenaline and 3/3 Thick hide. Pink bio coah is 1.7 with 5/3 adrenaline and 3/3 thick hide.

**Additional Information**
I also tested with paras and megaraptors if it does the same thing but no.
Tested after seeing the bug report #10222.

**Comment by Predatoria** [comment]
It looks like bleed's damage reduction is reducing your damage output, not adrenaline.  I tested it and get similar, but correct results.
