### ISSUE TITLE
[TESTER] Saving skins before spawning in crashes the client.

### ISSUE THREAD

**Issue by EkkoEctasy** [BoBAdministration/QA-Bug-Reports#342]
**Describe the Bug**
Saving a skin made in the character menu before spawning in will crash the client on the tester branch. Saving a skin after spawning in does NOT crash the client. (Does give lag, for some reason?)

**To Reproduce**
1. Logged into Dedicated Testing 12
2. Pick a dino from the dino selection menu (I used megalo for reference)
3. Pick a skin, alter it and hit the "Save Skin" button.
4. The client will close and come up with a crash report.

**Expected behavior**
The game should save your skin.

**Actual behavior**
A crash occurs and closes the client.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/96417223/183065767-b6fdbda7-80ca-4785-8900-0c35d3f3a0f4.png)
![image](https://user-images.githubusercontent.com/96417223/183065909-26f812fb-31d8-49b3-9d83-55f3fa6a7be8.png)

**Branch Version**
Tester (after patch: 1.1.1560)

**Character Information**
Not spawned in (any dino)

**Additional Information**
MAP is Titania

**Comment by Predatoria** [comment]
I found a fix for this.  It was a simple code error
