### ISSUE TITLE
Undermapping Hole on Rival Shores

### ISSUE THREAD

**Issue by tinystarpaws** [BoBAdministration/QA-Bug-Reports#35]
**Describe the Bug**
There is a hole in the mesh that leads underneath the map.

**To Reproduce**
1. Spawn as a Pteranodon
2. Enter command TeleportAt 115348 85015 5468
3. Enter map hole

**Expected behavior**
There should be mesh to stop you from exiting the map bounds

**Actual behavior**
You are able to pass behind the mesh and leave the map bounds

**Screenshots & Video**
(Taken from ticket-5916)
![image](https://user-images.githubusercontent.com/38923098/130539325-060b42cb-93e3-4dca-b5ad-915c891d3a9e.png)

**Branch Version**
Live branch.

**Character Information**
.4 Pteranodon

**Additional Information**
N/A

**Comment by teatimejess** [comment]
Confirmed fixed.
