### ISSUE TITLE
Arganodus are evolving to become land dwellers

### ISSUE THREAD

**Issue by Macarani123** [BoBAdministration/QA-Bug-Reports#352]
**Describe the Bug**
Arganodus on RS map are deciding that they want to evolve and walk up on land, spawning there seemingly and wandering on land.

**To Reproduce**
1. Spawned in on RS dedi 3 on any dino
2. Server has been up for 7:48:36 currently
3. Wandered around the map until finding the location at 
(X:-99548,Y:90868,Z:2823)
4. Found three arganodus frolicking in the area among momos.

**Expected behavior**
I know lungfish are able to breathe air but they probably should be living in water.

**Actual behavior**
The AI Arganodus just want to evolve and become land creatures it seems

**Screenshots & Video**
Sorry for low quality, its like those low quality monster/ghost pictures 
![20220911_221012.jpg](https://user-images.githubusercontent.com/96443517/189562536-7f8a6467-ca19-4d3e-b827-1512c40ce08e.jpg)
![20220911_220922.jpg](https://user-images.githubusercontent.com/96443517/189562546-4ae3cad6-d673-4435-b95f-4ba7f8e1d75e.jpg)

**Branch Version**
Tester

**Character Information**
Any dino, i was a rex and then a megar to chase down the fish easier on land.

**Additional Information**
RS map, server had been up for 7+ hours at the time of discovery

**Comment by Predatoria** [comment]
I think these came from me testing a foliage placement tool spawner that I put on land at this area.
