### ISSUE TITLE
When it is storming and you are in shelter, and then you eat a gore you start dripping again.

### ISSUE THREAD

**Issue by Alyrius** [BoBAdministration/QA-Bug-Reports#356]
**Describe the Bug**
when you are sheltered during a storm and as such, shouldnt drip, but you eat a gore in the shelter, you drip again

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. ex. Logged into Dedicated Testing 1
2. ex. SSpawned a carnivore, enter a rain scenario
3. ex. Be in a shelter until you stop dripping, eat a gore, watch drip reappear

**Expected behavior**
Do not start dripping in shelter

**Actual behavior**
Start drippin on titania

**Screenshots & Video**
https://youtu.be/bu2dri4VT7s

**Branch Version**
Tester 

**Character Information**
carnivpore

**Additional Information**
Rain!

**Comment by Peter22FIN** [comment]
This was velo / utah issue. I bumped up how much shelter dries you up and it seemed to have fixed it
