### ISSUE TITLE
Undermapping Hole on Rival Shores pt 2

### ISSUE THREAD

**Issue by tinystarpaws** [BoBAdministration/QA-Bug-Reports#36]
**Describe the Bug**
There is a hole in the mesh that leads underneath the map.

**To Reproduce**
1. Spawn as a Pteranodon
2. Enter command TeleportAt 120286 83930 5468
3. Enter map hole

**Expected behavior**
There should be mesh to stop you from exiting the map bounds

**Actual behavior**
You are able to pass behind the mesh and leave the map bounds

**Screenshots & Video**
(Taken from ticket-5916)
![image](https://user-images.githubusercontent.com/38923098/130539493-b41bb143-8124-4a05-9fe0-d5b42e14d90d.png)

**Branch Version**
Live branch.

**Character Information**
.4 Pteranodon

**Additional Information**
N/A

**Comment by teatimejess** [comment]
Confirmed fixed, while smaller growths can wedge into the corner, there is not an accessible way to undermap.
