### ISSUE TITLE
Dedicated 3 does not allow character creation

### ISSUE THREAD

**Issue by Alyrius** [BoBAdministration/QA-Bug-Reports#368]
**Describe the Bug**
for the saturday session dedicated 3 was restarted to update to the newest version, after this update, players were unable to create a character!

**To Reproduce**
Updated dedicated 3 to newest tester version
1. ex. Logged into Dedicated Testing 3
2. ex. No ability to create a character, its greyed out

**Expected behavior**
Can use buttons in character select menu

**Actual behavior**
Cant use button

**Screenshots & Video**
![grafik](https://user-images.githubusercontent.com/58645212/192161211-8aac20e9-f93b-4a53-bfd4-0a4ceb61730b.png)

**Branch Version**
Tester 

This may require further testing and checking of logs by someone with access to the servers and their files!

**Comment by Alyrius** [comment]
This seems to not happen to everyone? Cleaf and waya could create characters while me, nova and some others could not!

**Comment by Predatoria** [comment]
I was unable to reproduce this and Dedicated 3 worked for me.
