### ISSUE TITLE
Path note: Ory does NOT get dirty when entering burrows

### ISSUE THREAD

**Issue by Alyrius** [BoBAdministration/QA-Bug-Reports#370]
**Describe the Bug**
According to the patch note ory should get dirty burrowing, it does not!
https://discord.com/channels/605940021568208906/692746530590818384/1008920615153057845

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. ex. Logged into Dedicated Testing 1
2. ex. Spawned in a Ory anywhere on the map
3. ex. Dig a hole and check for dirt
4. ex. Notdirt!

**Expected behavior**
be a lil dirty after digging

**Actual behavior**
you arent dirty after digging

**Screenshots & Video**
message link to video upload on discord:
https://discord.com/channels/605940021568208906/965032727806091354/1023685845712121907
Link to download video in case former doesnt work: https://cdn.discordapp.com/attachments/965032727806091354/1023685844097306716/BeastsOfBermuda_Development_2022-09-25_21-59-49.mp4

**Branch Version**
Tester 

**Character Information**
Ory

**Additional Information**
Any

**Comment by Peter22FIN** [comment]
Only burrow entrance node makes you muddy. Digging does not make you dirty, otherwise orys would always be muddy

**Comment by Peter22FIN** [comment]
Increased how muddy you get when you walk on the first node under the burrow entrance

**Comment by Peter22FIN** [comment]
All burrow nodes now make creatures muddy when they walk on it. The speed is set to similar to blood so it should be subtle effect
