### ISSUE TITLE
Patch Note: Adjusted Goreroot to give -10 health, previously -1

### ISSUE THREAD

**Issue by Xunaria** [BoBAdministration/QA-Bug-Reports#371]
**Describe the Bug**
Goreroot does not remove any health when eaten, it only gives - bias

**To Reproduce**
1.) Enter Dedicated Testing 12
2.)Spawn in as any creature (pt the fastest)
3.)Find an area with Goreroot (Desert Canyon)
4.) Open O Menu
5.) Eat gore root
6.) Observer health staying the same 

**Expected behavior**
Any creature eating a gore root should receive -10 health per Goreroot consumed

**Actual behavior**
Creatures only gain negative bias from Goreroot and lose no health

**Screenshots & Video**
https://youtu.be/-j_RkegeG10

**Branch Version**
Tester

**Character Information**
Any Creature

**Additional Information**
N/A

**Comment by Vallyhalla** [comment]
Sounds like an intentional feature to make it that you don't lose HP if you eat them, since that would alter the gameplay a lot. The gore root should give negative bias and make you sick if you eat too much. Closing this.
