### ISSUE TITLE
Patch Note: Mud can now be cleaned faster by swimming or stepping/running in water.

### ISSUE THREAD

**Issue by Xunaria** [BoBAdministration/QA-Bug-Reports#374]
**Describe the Bug**
When a creature is muddy, it takes around 30 seconds to clear off the mud by running in the water, compared to being muddy and running in grass which takes around 15 seconds. 

**To Reproduce**
1.) Log into Dedicated Testing 12
2.) Spawn in as a white dinosaur (easier to see mud effect)
3.) Run around in mud until completely muddy
4.) Start a timer and start running around in water until the dinosaur is completely clean
5.) Record the time it takes from start to finish of being muddy to clean
6.) Run around in mud until completely muddy
7.) Start a timer and start running around in grass until the dinosaur is completely clean
8.) Record the time it takes from start to finish of being muddy to clean

**Expected behavior**
When being muddy, the dinosaur should be cleaned faster by running or stepping into any body of water

**Actual behavior**
When muddy it takes a gradual amount of time to go from being muddy to clean compared to becoming clean by just being on land

**Screenshots & Video**
https://youtu.be/FT-GLDjoPtg

**Branch Version**
Tester

**Character Information**
1.2 White Para

**Additional Information**
Any Weather except Rain/Storms

**Comment by Peter22FIN** [comment]
Increased the cleaning effect of walking in shallow water
