### ISSUE TITLE
Nesting does not give offspring inherits

### ISSUE THREAD

**Issue by Macarani123** [BoBAdministration/QA-Bug-Reports#376]
**Describe the Bug**
Nesting offspring will not pass inherits to the children and they grow up with no inherits at all. They also hatch with default skin and have to log to creature select and come back for their skin to show up.

**To Reproduce**
1. Log onto tester server, any works. 
2. Find a buddy to boink
3. Make eggs and take those eggs to hatch them, forcegrown or naturally.
4. Hatch with default skin, relog and it shows your skin finally.
5. Grow and you have no inherits.

**Expected behavior**
Expected to have inherits and a skin generated upon hatching

**Actual behavior**
You get no inherits and have to relog for your skin to show

**Screenshots & Video**
N/A :(

**Branch Version**
Tester

**Character Information**
Any dino with talents put in and above 0.8 for breeding.

**Additional Information**
Was on Titania at the time, but a long time ago this was found by Twilight and i when we were messing around with lurd skinmixing.

**Comment by Thy-Vipe** [comment]
Partially fixed: Got the skins to replicate properly once again.
