### ISSUE TITLE
Minor Capitalization issues with creature species names

### ISSUE THREAD

**Issue by Skyedrago** [BoBAdministration/QA-Bug-Reports#377]
**Describe the Bug**
Some creatures have their names uncapitalized in the creature select screen

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log into public or tester branch server
2. Go to creature select
3. Hover over the creature species names for Mosasaurus, Pteranodon, Apatosaurus, and Acrocanthosaurus

**Expected behavior**
All creatures have the same formatting

**Actual behavior**
Some creatures do not have the same formatting

**Screenshots & Video**
![20220927222442_1](https://user-images.githubusercontent.com/96404852/192673870-a3406891-5cf9-4446-87df-795140cf3395.jpg)
![20220927222446_1](https://user-images.githubusercontent.com/96404852/192673871-98c39000-7215-487b-8209-76e940a0508b.jpg)
![20220927222457_1](https://user-images.githubusercontent.com/96404852/192673872-48ff8133-d9c7-44ac-a64f-e1636afd7b3c.jpg)
![20220927222503_1](https://user-images.githubusercontent.com/96404852/192673873-32d2c522-bd01-4dfe-bf3b-3dd0e88afb3e.jpg)

**Branch Version**
Both

**Character Information**
Not relevant.

**Additional Information**
Quality of life. Not a bug.

**Comment by Predatoria** [comment]
This seemed really simple, but I actually can't reproduce it.
