### ISSUE TITLE
Abandoned Egg has no skin edit option.

### ISSUE THREAD

**Issue by KattofKits** [BoBAdministration/QA-Bug-Reports#378]
**Describe the Bug**
Abandoned Lurdu egg hatched, unable to edit the skin, no option TO edit the skin. This bug can be "fixed" by relogging the character.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 12.
2. Took an abandoned Lurdu Egg.
3. Hatched said egg.
4. Open the Character menu, then skin customization.

**Expected behavior**
A player should be able to edit their nested skin.

**Actual behavior**
The player is unable to edit their nested skin.

**Screenshots & Video**
https://youtu.be/_x92NA3d6co

**Branch Version**
Tester Patch 1.1.1590

**Character Information**
Abandoned Lurdu Egg-0.1 Lurdu

**Additional Information**
Titania Test Map

**Comment by Thy-Vipe** [comment]
Fixed it, needs testing.

**Comment by MarshmallowMaiden** [comment]
Confirmed fixed on tester branch
