### ISSUE TITLE
Megaraptors damaged nests and eggs as they pass over them

### ISSUE THREAD

**Issue by Akaraasaur** [BoBAdministration/QA-Bug-Reports#379]
**Describe the Bug**
Megaraptors still damaged others nests and eggs as they pass over them after biting someone.

**To Reproduce**
1. Log on any server
2. Spawned on megaraptor, any growth
3. Bite someone
4. Walk on a nest with eggs in itn it damage eggs and nest 

**Expected behavior**
Megaraptor shouldn't damaged others nest and eggs when walking on them

**Actual behavior**
Megaraptor damaged nests and eggs when walking on them after biting someone

**Screenshots & Video**
Bug happened on live branch when I was nesting. A friend came to bite me and walked on my nest.

https://youtu.be/RptWRXzueKQ

**Branch Version**
Live

**Character Information**
Megaraptor, any size, gender

**Additional Information**
I tested this bug on an open console server on live branch, same thing happened.

**Comment by Zi-Mom** [comment]
Also pulled from Vipe's Github (Issue 10237)

**Comment by Predatoria** [comment]
Duplicate of another issue.  I'm going to close it.
