### ISSUE TITLE
FriendShip icon buff disappearing 

### ISSUE THREAD

**Issue by MysteryKit66** [BoBAdministration/QA-Bug-Reports#38]
**Describe the Bug**
FriendShip icon buff disappears when a friendly player crouch dropping your comfort as if you were alone

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. ex. Log in a public server
2. ex. Spawn in as any creature 
3. ex. Get near a person with a friendship grade
4. ex.  Let them crouch while you stand
5. ex. Friendship icon/buff disappears
**Expected behavior**
The friendship icon/buff should stay no matter if the other creature stands or crouch next to you

**Actual behavior**
When have a friendship grade with someone and they crouch your buff and comfort will drop/disappear. Same goes to them if you crouch their buff will disappear

**Screenshots & Video**
https://youtu.be/nRmkFACfgKM

**Branch Version**
Tester or Live.
Live

**Character Information**
Any dinosaur with a friendship grade of E or above works

**Additional Information**
Need 2 players with a friendship grade to tets it out

**Comment by Predatoria** [comment]
Should be fixed

**Comment by SilverWing430** [comment]
Confirmed fixed on tester
