### ISSUE TITLE
The talent setstats does not dirty a dino and is useable by admins/ hackers

### ISSUE THREAD

**Issue by Alyrius** [BoBAdministration/QA-Bug-Reports#387]
**Describe the Bug**
Setstats is a command that is currently used by hackers as they can increase their comfort (one of the currently main ways you see them, with constant 100 comfort etc). it is not locked and the creatures do not get dirtied. You can set your comfort to 1mil and nothing will happen.

**Expected behavior**
It dirties the creatures/is blocked

**Actual behavior**
It is usable by admins and abused by hackers in some cases. and does not dirty creatures

**Branch Version**
Live.

**Character Information**
Any, needs admin/hacker

**Additional Information**
Any

**Comment by Predatoria** [comment]
I edited the command so it should be fine now
