### ISSUE TITLE
Trope is able to use wingbeat quickly before dive and after dive

### ISSUE THREAD

**Issue by Zi-Mom** [BoBAdministration/QA-Bug-Reports#388]
**Describe the Bug**
A tropeo currently can wingbeat going into the water at speed, then as soon as the dive state and animation is done can wingbeat again underwater.

**To Reproduce**
1. Log into any Server
2. Spawn as a tropeo
3. Go into a dive at speed towards the water (Speed is important)
4. Wingbeat as you are about to hit the water/hitting the water
5. Spam the wingbeat button and you will wingbeat underwater after the dive animation/state

**Expected behavior**
To not be able to wingbeat at all under water.

**Actual behavior**
Smacky smacky wings under the water. Trope should not be able to use their wingbeat ability underwater in any condition.

**Screenshots & Video**
[Video](https://discord.com/channels/605940021568208906/875638060786778123/1025068063940427836)  

**Branch Version**
Both

**Character Information**
Tropeo

**Additional Information**
Air to water

**Comment by Vallyhalla** [comment]
I don't think this is a bug, from the video the tropeo is still in it's diving state and is able to wingbeat. Once it gets its swimming animation it can't wingbeat under water anymore.
