### ISSUE TITLE
space+alt to crash the game and sometimes make character disappear.

### ISSUE THREAD

**Issue by Alyrius** [BoBAdministration/QA-Bug-Reports#39]
**Describe the Bug**
When pressing alt+spacebar while the game is in windowed mode, windows will attempt to do something (according to google, change the window) in any case, holding this combination will crash some computers (usually those already under heavy load) leading to your character disappearing 

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log onto any server
2. Spawn a creature, in my tests a Tropeo
3. Open chat and click out of it (optional: Fly, walk, Move in any way)
4. Press and Hold alt+spacebar
5. Game should crash, removing your character with it

**Expected behavior**
Game may crash, but character stays ingame

**Actual behavior**
Game may crash, but the character disappears

**Screenshots & Video**
https://youtu.be/NaX8iVle374 unable to attach due to size, so heres a link

**Branch Version**
Tester and Live

**Character Information**
Any creature, easiest to test on flyers

**Additional Information**
Just... weaker machines or under heavy load makes this easier to reproduce, this can be done faster than shown in my video, as fast as alt+f4

**Comment by Zi-Mom** [comment]
Confirmed Fixed On tester
