### ISSUE TITLE
The Reskin command can be glitched to forever allow skin editing on subject

### ISSUE THREAD

**Issue by Zi-Mom** [BoBAdministration/QA-Bug-Reports#397]
**Describe the Bug**
Currently when you use the reskin command and open your skin customization it will appear as if you cannot edit it, however if you press either skins or saved skins and then the back button without clicking or hovering your mouse over any other skin you will gain access to your current skin pallet forever. This includes past entering character select, or leaving the server.

**To Reproduce**

1. Logged into Dedi 12
2. Set growth of creature above skin edit
3. Check to make sure you can't edit skin (You can't)
4. Use the reskin command on yourself
5. Open skin customization
6. Press either "Skins" or "Saved Skins"
7. Click any skin and edit OR without clicking/hovering over a skin press the "return" button
8. Play with skin
9. Close skin editing and open it again. You still have access
10. Go to character select and log back into reskinned dino, can still edit
11. Log out of the server and log back into reskinned dino, can still edit

**Expected behavior**
Reskin to open current skin colours to edit as it does on live atm, and for skin customization to lock after it is exited out of. 

**Actual behavior**
First can't tell you can edit skin, then you can edit forever after figuring out how to access it.

**Screenshots & Video**
https://youtu.be/I3rYqp14ITE

**Branch Version**
Tester 

**Character Information**
Above skin edit age, any dino.

**Additional Information**

**Comment by Zelryn** [comment]
Not Fixed Can still Edit Skin after closing window and logging out and relogging back into the game and server.

**Comment by Zelryn** [comment]
This bug has changed. 


1. log into Dedicated 11
2. Spawn on Acro.
3. Reskin your dino.
4. Change the pattern and color on the dino.
5. Close the window.
6. re open the skin window.
7. change color again.
8. Log out of server. 
9. You can still change the color and edit skin. 
10. After you edit this time with logging in and out it locks the skin.

Reproduction 2ed way
This way is Fickle and half the time it locks appropriately and half the time it stays unlocked?
1. Log into Dedicated 11
2. Spawn on a 1.2 Acro
3. Reskin your dino
4. Recolor your skin but do not change the pattern
5. 50/50 it will lock the skin when you close it or leave it unlocked. 

To add on

Wei - Reskin Worked Correctly - One Tester had this work correct one with Incorrect.
Acro - Reskin Worked Incorrectly
Apato - Reskin Worked Incorrectly
Lurdu - Reskin Worked Incorrectly
Ory - Reskin Worked Incorrectly
Pachy - Reskin Worked Incorrectly
Para - Reskin Worked Incorrectly
Sai - Reskin Worked Incorrectly
Coah - Reskin Worked Incorrectly
Pter - Reskin Worked Incorrectly
Trop - Reskin Worked Incorrectly
Elas - Reskin Worked Incorrectly
Krono - Reskin Worked Incorrectly
Megar - Reskin Worked Incorrectly
Velo - Reskin Worked Incorrectly 
Rex - Reskin Worked Incorrectly
Icthy - Reskin Worked Incorrectly
Acro - Reskin Worked Incorrectly

**Comment by Vallyhalla** [comment]
Tried to reproduce and when I logged back into the server the option to change my skin was gone. Not 100% sure why it's a big issue that you can exit out of the skin screen and tab back in and still edit your skin? Can mention that it's a 50/50 and have it fixed that you don't lose the ability to edit your skin when you leave the sceen. Closing this for now.
