### ISSUE TITLE
Lurdu can sniff for fish

### ISSUE THREAD

**Issue by theriversedge** [BoBAdministration/QA-Bug-Reports#398]
**Describe the Bug**
Lurdusaurus can sniff for fish

**To Reproduce**
1. Logged into Dedicated Testing 12
2. Spawned in as a Lurdusaurus
3. Sniffed near/inside water that contains fish
4. The fish highlight red

**Expected behavior**
Lurdusaurus should not be able to sniff for fish, as it is not a piscivore

**Actual behavior**
Lurdusaurus can sniff for fish despite not being a piscivore

**Screenshots & Video**
N/A

**Branch Version**
Tester

**Character Information**
1.3 Lurdusaurus

**Additional Information**
Isla Titania

**Comment by Predatoria** [comment]
This happens with 3/3 aqua and is stated on the talent.  I may change it, but currently it's stated to do so in-game.
