### ISSUE TITLE
Coahuilaceratops baby morph tongue clips through mouth.

### ISSUE THREAD

**Issue by teatimejess** [BoBAdministration/QA-Bug-Reports#4]
**Describe the Bug**
Baby morph tongue clips through the mouth during idle and has a small bump on the frill, though that may be intentional.

**To Reproduce**
1. Log into any tester server
2. Setgrowthlevel 0.1
3. Swivel camera towards mouth.

**Expected behavior**
No clipping occurs.

**Actual behavior**
Tongue clips through mouth.

**Screenshots & Video**
![coah_baby_tongue](https://user-images.githubusercontent.com/77513445/129468633-178e1ae5-61a2-4493-86b2-5f326a71ed7a.png)

**Branch Version**
Tester

**Character Information**
Coahuilaceratops, 0.1 growth. 
Stops occurring at 0.3 growth.

**Additional Information**
N/A

**Comment by BoBAdministration** [comment]
(Starcatcher) Morph has been edited, pending deployment on tester branch.

**Comment by teatimejess** [comment]
Confirmed on tester fixed.
