### ISSUE TITLE
Resubmitting Meeting Test :'>

### ISSUE THREAD

**Issue by Falcarius9** [BoBAdministration/QA-Bug-Reports#40]
**Describe the Bug**
Ashen decal issue by standing on ash

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Spawn the wild fire
2. Wait for the ash to show up on the ground
3. Upon stepping on the ash covered area, the decal will apply to your dinosaur

**Expected behavior**
Ash decal stays on the ground, does not wrap around the dinosaur

**Actual behavior**
Ash decal wraps around the body of your dinosaur, leaving you crispy

**Screenshots & Video**
If applicable, add screenshots to help explain your problem, or attach a video/gif. You can do this by just pasting in your image(s)!

**Branch Version**
Live

**Character Information**
Godzilla, etc

**Additional Information**
Wild fire

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
