### ISSUE TITLE
Lurdu's Spikes Don't Glow When Acro Roars or When Sniffed

### ISSUE THREAD

**Issue by Vallyhalla** [BoBAdministration/QA-Bug-Reports#405]
**Describe the Bug**
I assume this has something to do with Lurdu's spikes not being able to be edited in the skin maker, but when you use the intim roar on the lurdu's spikes wont glow, same when you sniff their builds.
**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 12
2. Spawned in an Acro, Zun as the Lurdu
3. Intim-roared her
4. Sniffed her
5. Spikes don't glow

**Expected behavior**
Entire body including the spikes will glow.

**Actual behavior**
Everywhere but the spikes glow.

**Screenshots & Video**
![Screenshot_1dfdf](https://user-images.githubusercontent.com/96442596/196309395-e2256cc9-c7f7-49c1-816a-3d06ac2382f7.png)
![sdfs](https://user-images.githubusercontent.com/96442596/196309459-7a61ac8b-2d89-409a-b3f8-33943babf184.png)

**Branch Version**
Tester.

**Character Information**
1.2's

**Additional Information**
Map type, weather, or any other context about the problem here.

**Comment by Predatoria** [comment]
Soals fixed this last night
