### ISSUE TITLE
Identification Talent does not correlate properly to results.

### ISSUE THREAD

**Issue by ITechnicPyroI** [BoBAdministration/QA-Bug-Reports#406]
**Describe the Bug**
Despite having 2/3 identification, megalo can see comfort on creatures.

- EDIT Also food and water DOES NOT SHOW!!!

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Invest 2/3 points into the Identification talent.
2. Press Z on a coahuilaceratops or a different dinosaur.
3. Comfort will show even though specified not to.

**Expected behavior**
1/3 Invested - Ability & Stamina
2/3 Invested - Food & Water
3/3 Invested - Comfort & Growth

Having two should only display Ability, Stamina, Food, & Water.

**Actual behavior**
It shows all of the above, Injury, Venom, Bleed, & Comfort. Food and water does not display.

**Screenshots & Video**
If applicable, add screenshots to help explain your problem, or attach a video/gif. You can do this by just pasting in your image(s)!

https://user-images.githubusercontent.com/48891088/196325135-529d068e-dcb3-47bb-a685-39d3662d3510.mp4

**Branch Version**
Live & Tester.

**Character Information**
Megalosaurus, 2.702

**Additional Information**
Rival Shores, in a duel with a Coah. [Happens outside of duels as well.]

**Comment by MarshmallowMaiden** [comment]
Confirmed fixed on tester
