### ISSUE TITLE
Air bubble in Rival Shores aquatic cave

### ISSUE THREAD

**Issue by Romanov0** [BoBAdministration/QA-Bug-Reports#41]
**Describe the Bug**
Air bubble in the water cave on Snowy Mountain, Rival Shores.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged on to Dedicated testing 2.
2. Spawned as any creature that can fit in the tunnels.
3. Teleported to Location: X=-216417.828 Y=-16328.183 Z=17212.293
4. Meshed my head and my breath was not moving.

**Expected behavior**
No air bubble.

**Actual behavior**
Air bubble.

**Screenshots & Video**
https://cdn.discordapp.com/attachments/839021901149241364/879885501480456242/unknown.png
![image](https://user-images.githubusercontent.com/89394401/130707524-e8f42aa1-3dc6-4f93-9cb6-abb88fc374e8.png)

**Branch Version**
Tester and Live. [Moved from Vipes/In-game bug reports after testing it.]

**Character Information**
Any dino that can fit in the caves will do.

**Additional Information**
You need to mesh your head a little to get to the air bubble.

**Comment by teatimejess** [comment]
Partially fixed, able to stand on rocks as if on land, breathe normally, and have coloration as normal. 

1. Logged on to Dedicated testing 2.
2. Spawned as any creature that can fit in the tunnels.
3. TeleportAt -216919 -16239 19358
4. Meshed my head and my breath was not moving.
![image](https://user-images.githubusercontent.com/77513445/134559033-35721697-7df4-425a-80db-376868c9e1d5.png)
