### ISSUE TITLE
Leaderboard Scrolling extremely loud

### ISSUE THREAD

**Issue by ITechnicPyroI** [BoBAdministration/QA-Bug-Reports#410]
**Describe the Bug**
If you scroll too fast in the leaderboard it is extremely loud.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Open Leaderboard
2. Scroll by using right click and dragging quickly.
3. It should be extremely loud compared to all other buttons.

**Expected behavior**
The sounds for scrolling should remain at the same volume of the pressing button sound.

**Actual behavior**
It's double the volume and sounds like it's overlapping.

**Screenshots & Video**

https://user-images.githubusercontent.com/48891088/197320976-39258a37-620b-4dc8-8459-7045772bc7ee.mp4

**Branch Version**
Tester

**Character Information**
Para, 1.2

**Additional Information**
Titania

**Comment by Predatoria** [comment]
I think detest addressed this
