### ISSUE TITLE
Meeting Example!

### ISSUE THREAD

**Issue by Chipboard** [BoBAdministration/QA-Bug-Reports#411]
**Describe the Bug**
As of this recent patch, ash decals show over creatures

**To Reproduce**
1. Go to volcano
2. Walk into ash

**Expected behavior**
I expected the dinosaur to roam without the decal appearing on top of the dinosaur.

**Actual behavior**
The decal projects on top of the dinosaur.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/21075123/197345470-b34f2615-926f-4c9a-b8b5-5918e3c4e395.png)

**Branch Version**
Tester

**Character Information**
2.0 Combat Sai

**Additional Information**
Volcano map, partly cloudy

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
