### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by Revstiel** [BoBAdministration/QA-Bug-Reports#412]
**Describe the Bug**
When you walk over ash as a 1.2 sai, the ash overlays ontop of the dino causing an unintended visual affect with the player's model.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log on to Dedicated Testing 1
2. Spawned in a sai in bridge lake area.
3. Set growth level to 1.2
4. Upon walking over ash, the sai's model was affected by this visual bug
**Expected behavior**
Ash should not overlay on the sai's model

**Actual behavior**
The ash will have a visual affect of the ash overlaying on top of the sai, example in the screenshot

**Screenshots & Video**
If applicable, add screenshots to help explain your problem, or attach a video/gif. You can do this by just pasting in your image(s)!
![image](https://user-images.githubusercontent.com/96402095/197345545-c01f4f79-3900-41be-945b-2d94e8c0d588.png)

**Branch Version**
Live branch

**Character Information**
Sai, 1.2 growth, female gender, shimmer skin.
**Additional Information**
Ash was on the ground from a recent fire

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
