### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by Zelryn** [BoBAdministration/QA-Bug-Reports#413]
**SKY PLANTS!**
I found plants that are within the stratosphere. They do not belong here! 

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 3
2. Wandered around like a freak to avoid Ms. Bean who has killed me once already!
3. Found These !!!!!!! 
4. Was sad could not eat.

**Expected behavior**
Plants to not be air plants?

**Actual behavior**
Plants growing in the air beside a rock probably just placement tool bein a fool.

**Screenshots & Video**
https://i.imgur.com/Kh6PdZu.jpeg

**Branch Version**
Tester 

**Character Information**
Not necessary

**Additional Information**
I love you people, Sky plants was the worst when trying to build on Canvas. It was my job on our server to find LOL sorry Soals

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
