### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by MarshmallowMaiden** [BoBAdministration/QA-Bug-Reports#414]
**Describe the Bug**
Ash decals are appearing to show over the skins of players whom walk in the area after a fire has burnt out. 

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into server where fire had recently burnt out. 
2. Used acro to travel to affected area
3. Walked over scorched earth location
4. Creatures skin was covered in the scorched/ash from the ground 

**Expected behavior**
The expected behavior should have allowed the players creature to walk over the scorched earth without the visual glitch on their skin.

**Actual behavior**
When the creature walked over the ash they were covered in the soot from the ground. 

**Screenshots & Video**
https://media.discordapp.net/attachments/922324689177673778/922567776688803950/u6IfomaDTyauK8lhKEmXeg.png

**Branch Version**
Live

**Character Information**
Dinosaur growth- Elder
Dinosaur type-Acro

**Additional Information**
Recent fire after storms.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
