### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by 0fivu0** [BoBAdministration/QA-Bug-Reports#415]
**Describe the Bug**
Ash decals show over the top of creature skins, instead of staying on the ground.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Server 1
2. Spawned a Saichania at Jungle
3. Walked over an area where there was recently a forest fire, and where there was ash decals on the ground
4. When walked over, the ash decals cover the dinosaur model on top of its skin.

**Expected behavior**
Expected behavior for ash decals is for them to stay on the terrain and not over the top of the dinosaur's skin.

**Actual behavior**
What actually happened was the ash decals covered the entirety of the skin of the dinosaur.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/116113026/197346880-b951ba41-c066-4024-a170-b0e774e9f44c.png)

**Branch Version**
Live.

**Character Information**
0.45 spawn Saichania

**Additional Information**
Forest Island, following a Forest Fire.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
