### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by BackwaterOtter** [BoBAdministration/QA-Bug-Reports#416]
**Describe the Bug**
When walking over areas of ground that are covered in ash, the decals will show over the player creature.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 1
2. Spawned in a Saichaia at Bridge Island
3. Drank from the swamp and both upper bridge water sources.
4. Fire started.
5. Travelled to Para Pond
6. Drank water at Para Pond
7. Returned from Para Pond after the fire.
8. Ash decal displayed over my Saichania.

**Expected behavior**
I expected the ash decals to display only on ground surfaces.

**Actual behavior**
Ash decals display over my saichania.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/24828337/197345717-6cdb4662-8398-4775-b655-91f1f00a2f1a.png)

**Branch Version**
Live

**Character Information**
I was a Saichania, growth 1.212, gender female, with a survival-combat build with 1 inherit in bruiser.

**Additional Information**
The map was Ancestral Plains, this incident followed a fire on Bridge Island.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
