### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by Zelryn** [BoBAdministration/QA-Bug-Reports#417]
**Describe the Bug**
Walking Over areas where there was a fire that now has ash cause your dino to get covered in Ash

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 2
2. Spawned in as a Saichania
3. Was wandering threw the jungle
4. Noticed my sai was a different color..
5. Realized the Sai was covered in Ash from the ground.

**Expected behavior**
Did not expect Ash to cover the player only the ground.

**Actual behavior**
Dino was covered with the ash when walking threw it

**Screenshots & Video**
https://i.imgur.com/TAIVB8z.png

**Branch Version**
Tester

**Character Information**
.6 Saichania

**Additional Information**
Ancestral Plains sunny weather post fire.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
