### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by itendtobite** [BoBAdministration/QA-Bug-Reports#418]
**Describe the Bug**
Burrows not loading in fully sometimes. Therefore when entering the burrow, parts of it doesn't load and you end up falling under the map and drowning.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. ex. Log into any server
2. ex. Spawned in as Ory
3. ex. Make a burrow, fairly large(a staircase should be be enough to test it on). Log out, log back into ory and enter burrow.
4. ex. I make fairly large burrows and sometimes I notice that half the burrow is gone but I wait a few seconds and it loads. However if you're not paying attention while walking(like I've done multiple times), it can actually send you under the map and drown you. Normally if you kicked out due to water or a rock it teleports you to your last burrow entrance used.  This one doesn't do that, it just sends you to the bottom of the ocean & you drown.
5. ex. It doesn't work all the time but I think it's a combination of population(most common for lag but a lot of gores & foliage in one area will cause lag as well), graphic settings and the size of the burrow itself.

**Expected behavior**
To load in fully or if it does do that, for it to teleport you to the last used entrance.

**Actual behavior**
It shows nothing but blackness and if you walk in it, it will send you under the map and drown you instead of porting you to the entrance like it normally does.

**Screenshots & Video**
![burrow bug](https://user-images.githubusercontent.com/116121462/197363697-ecbfa59a-2672-4f35-b33a-8bbb6d6bcb9a.jpg)

https://user-images.githubusercontent.com/116121462/197363789-86d12026-b0c2-4c6d-ac54-edb234eb85ff.mp4

https://user-images.githubusercontent.com/116121462/197363888-78888402-e345-4703-b27b-7f3742959281.mp4

**Branch Version**
Live

**Character Information**
It's not the ory, but the burrow itself if it's fairly large.

**Additional Information**
I can't always get this bug to replicate but when I'm lagging from it loading in, it seems to do this. Perhaps graphic settings have a play as well? I had them set pretty high on the PTR & it saved those settings. I was As you see in the video for a split second, the burrow wasn't loaded in completely. It fixed itself too quickly for me to show what it actually does, but the other video I provided is what happened to me when I was running and didn't stop in time. I couldn't figure out how to mute that video so please excuse the random discord chatter between some friends, it's not me who was speaking lol. The video where it fixes itself in a second, the burrow wasn't as large as the one in the 2nd video where I died in so that could also be why it didn't take as long to load in as the last ones I've encountered have. The one where I died as well was on a different map and highly edited with the map editor. It was very common before the server switched back to the other map, but I did almost die again from the same bug on the current map (Ancestral plains).

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
