### ISSUE TITLE
Meeting Example.

### ISSUE THREAD

**Issue by TriangleLily** [BoBAdministration/QA-Bug-Reports#419]
**Describe the Bug**
Forest fire decal is appearing on top of a Sai's model.

**To Reproduce**
1. Logged into Dedicated Testing 1
2. Spawned in as a Sai in an area that was recently burnt from a Forest Fire
3. Crossed area to reach water source
4. As I stepped onto the burnt areas, the decal moved onto my model
5. Decal does not move with the model, it is still placed onto the ground; model is simply moving through it and showing on top of model skin

**Expected behavior**
Decal to not jump onto model and move through it as if it were a normal texture.

**Actual behavior**
Burnt grass and ash decal jumped onto model and covered usual model detail.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/116124641/197367559-5778e95c-eb72-4ca5-866a-cbe638bee788.png)

**Branch Version**
Live

**Character Information**
1.2 Glimmer Sai

**Additional Information**
Area had recently gone through a forest fire. Weather was clear and sunnny when bug occured but close to a sunset.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
