### ISSUE TITLE
Egg POV in burrow. Nests are cursed.

### ISSUE THREAD

**Issue by Romanov0** [BoBAdministration/QA-Bug-Reports#42]
**Describe the Bug**
Eggs don't see burrows but have the underground POV because of the nest.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 2.
2. Spawned as 1.2 Orys.
3. Mated and nested, the egg MUST BE in the nest.
4. 1 of us got in the egg and couldn't see the burrow.

**Expected behavior**
Normal POV inside the burrow.

**Actual behavior**
The egg POV is underground without seeing the actual burrow.

**Screenshots & Video**
https://cdn.discordapp.com/attachments/605979793716019205/879892645462290462/unknown.png
https://cdn.discordapp.com/attachments/605979793716019205/879892645462290462/unknown.png

**Branch Version**
Tester and Live.

**Character Information**
Ory or Velo any growth.

**Additional Information**
The egg needs to be inside the burrow in the nest!

**Comment by teatimejess** [comment]
Confirmed fixed, followed reproduction steps. Eggs nested view as normal and expected.
