### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by SilverWing430** [BoBAdministration/QA-Bug-Reports#420]
**Describe the Bug**
Ash decals from a recent fire show over dino models

**To Reproduce**
1. Log into a server
2. Have a fire spawn
3. Move dino model to a spot that has ash decal left on the ground
4. Move camera and dino around to see how ash decal moves with dino model

**Expected behavior**
The ash was expected to remain on the ground and not layer over the dino model.

**Actual behavior**
The ash was layered over the dino model, and could then be seen from all angles.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/116122955/197373336-28ef5dd2-1279-44a6-b448-9f0c04087802.png)

**Branch Version**
Live.

**Character Information**
Saichainia, 1.2 growth (I think it is, from the pic provided)

**Additional Information**
Ancestral plains (again I think it is, from the pic provided), fire

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
