### ISSUE TITLE
Meeting Example

### ISSUE THREAD

**Issue by itendtobite** [BoBAdministration/QA-Bug-Reports#421]
**Describe the Bug**
Ash decals left by fire show over creature when walking through it.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. ex. Log into any server
2. ex. Spawned in as any creature
3. ex. Locate the area which a fire has taken place
4. ex. Walk through the ash decals left by fire

**Expected behavior**
To be able to walk through without if transferring onto the creature

**Actual behavior**
It transfers on top of the creature, giving it the grey texture as you walk through it.

**Screenshots & Video**
![ash bug](https://user-images.githubusercontent.com/116121462/197373804-78ffd505-8a82-476f-8d9a-ed2629a83606.png)

**Branch Version**
Both

**Character Information**
None are necessary.

**Additional Information**
Just a fire to take place and to walk over the ash remains.

**Comment by tinystarpaws** [comment]
Meeting Example only; not a true bug report submission. Closing.
