### ISSUE TITLE
Join Last Played Server breaks Server Browser when it fails to join

### ISSUE THREAD

**Issue by Chipboard** [BoBAdministration/QA-Bug-Reports#422]
**Describe the Bug**
Upon trying to Join Last Played Server, and failing to connect, the server listing fails to grab and list any servers.

**To Reproduce**
1. Join Last Played Server on a closed server that is no longer hosted
2. Press "ok" once it fails, and proceed to Multiplayer server listings
3. Observe

**Expected behavior**
I expected it to list the servers available to join

**Actual behavior**
It lists nothing until you restart the game, and do not click Join Last Played Server again

**Screenshots & Video**
[Video!](https://youtu.be/mINRwWWkoJo)

**Branch Version**
tester-team

**Character Information**
N/A

**Additional Information**
My last joined server was the public Titania test from the other night.

**Comment by Chipboard** [comment]
The results of this have changed, however now re-joining the now closed previous server leads the player to an infinite loading loop..  Submitting a new bug request as this has led to two new bugs. This is still pending testing as I am unable to return to the menu.

**Comment by SilverWing430** [comment]
Server list now shows up as normal after a fail to join via the Join Last Played button
Confirmed Fix
