### ISSUE TITLE
Flower causes hurt sound with no damage

### ISSUE THREAD

**Issue by Chipboard** [BoBAdministration/QA-Bug-Reports#426]
**Describe the Bug**
When eating a poisonous flower, my Ory plays his hurt sound even though no damage is done.

**To Reproduce**
1. Log into a Titania server
2. Spawn in Ory
3. Find and eat a red poisonous flower
4. Chicken noises

**Expected behavior**
I expected Ory to get sick and feel uncomfortable

**Actual behavior**
Ory screams at his upset stomach, although he is fine

**Screenshots & Video**
[Ouch!](https://youtu.be/mjKGL74ICs0)

**Branch Version**
tester

**Character Information**
1.3 Male Oryctodromeus

**Additional Information**
Map: Titania

**Comment by Predatoria** [comment]
This is intentional.  Negative bias plants now cause this to warn you you can get sick from them.
