### ISSUE TITLE
Acro can bite while intim roaring

### ISSUE THREAD

**Issue by Revstiel** [BoBAdministration/QA-Bug-Reports#430]
**Describe the Bug**
When an acro intim roars, it is able to bite through the roar, instead of finishing the call animation.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged onto my personal live branch test server ES Testing
2. Spawned in an apato on my other account using my other laptop.
3. Spawned in an acro on my main account.
4. Met up the two dinos and roared the apato
5. During the roar was able to instantly bite the apato, ignoring the call animation

**Expected behavior**
Acro should not be able to bite during its calls, in the video I was unable to bite during the one-call.

**Actual behavior**
Acro is able to bite through it's intim roar call.

**Screenshots & Video**
https://www.youtube.com/watch?v=zkJBE3pE9AM

**Branch Version**
Live

**Character Information**
Spawn Acro and Apato, was able to reproduce

**Additional Information**
N/A

**Comment by Predatoria** [comment]
not a bug
