### ISSUE TITLE
Acacia Tree Branch ends shake like leaves.

### ISSUE THREAD

**Issue by ITechnicPyroI** [BoBAdministration/QA-Bug-Reports#433]
**Describe the Bug**
I think the tips of the branches of the acacia trees are classified as leaves.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log onto a server with Acacia trees, preferably AP
2. Make it windy.
3. Look at the branch tips, they are shaking like leaves.

**Expected behavior**
The tree branch tips should not shake in the wind.

**Actual behavior**
Branch has a party when its windy.

**Screenshots & Video**

https://user-images.githubusercontent.com/48891088/198749923-9bb689bb-ca3b-4fe5-9221-2264cc01bae5.mp4

**Branch Version**
Live.

**Character Information**
Megaraptor 1.3

**Additional Information**
Map is AP

**Comment by Zi-Mom** [comment]
Was noted and fixed in Titania, unsure if this transfers over to the other maps. Will keep open until confirmation.

**Comment by Vallyhalla** [comment]
Looked at them on AP and they are fixed! Closing this.
