### ISSUE TITLE
Blank Dino Information (Quality of Life, not bug)

### ISSUE THREAD

**Issue by Skyedrago** [BoBAdministration/QA-Bug-Reports#434]
**Describe the Bug**
There is no information about several dinos

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log in to any server
2. Go to Creature Select
3. Select one of the pictured dinos
4. Open Creature Info
5. There is no information

**Expected behavior**
A brief set of descriptions about each dino

**Actual behavior**
There is no description

**Screenshots & Video**
![20221028215001_1](https://user-images.githubusercontent.com/96404852/198764695-39f121fa-54ab-42ab-bac5-3abc0e8d0878.jpg)
![20221028215013_1](https://user-images.githubusercontent.com/96404852/198764706-2c6b1b87-cd52-4861-a8e5-d847d2669454.jpg)
![20221028215407_1](https://user-images.githubusercontent.com/96404852/198764710-7baa9f39-3925-409c-9fc1-6f948d68ae22.jpg)
![20221028215515_1](https://user-images.githubusercontent.com/96404852/198764714-83fc8ffe-5f59-4b46-91a6-4792daa10184.jpg)

**Branch Version**
Live.

**Character Information**
N/A

**Additional Information**
N/A

**Comment by Predatoria** [comment]
I can reproduce this in a cooked build but it doesn't reproduce in PIE.  I put a log print in to find the issue.
