### ISSUE TITLE
Trope Speed Glitch

### ISSUE THREAD

**Issue by itendtobite** [BoBAdministration/QA-Bug-Reports#438]
**Describe the Bug**
Rapid speed increase when darting out of the water.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log into any server
2. Spawn in as a Trope
3. Find a water source that is deep enough to swim in.
4. Enter the water(Not too deep, just enough where you're able to dart out of the water)
5. Hold your **strafe** key. Note that it's easier to bind it to a easy reach key(so mine is bound to my mouse for ex)
6. **Look up** while holding the **strafe** key
7. Hold down your **Sprint** key
8. Move **forward** slightly
9. Use the **dart** ability right when you're about to exit the water
10. **SPAM** your **jump** key (Note that this will take a few tries to get it, but this step is the most important. You literally have to **spam** it when you exit the water with the dart)

**Expected behavior**
To just be able to just exit the water without going into space

**Actual behavior**
It gives you extra speed out of no where.

**Screenshots & Video**
https://youtu.be/bY3Ml2P6j-k  (.4 trope no talents or inherits)
https://youtu.be/hDKT9k4yEEM  (Spawn trope on tester branch. Only inherits I got were weather and lungs, so none have affected this test. No points were spent as well.)
https://youtu.be/I2hYM46RnZg (1.2 spawn trope. Not many inherits and points were spent on this one but as you can see from the other 2, you can just perform this even as a .4 spawn.
https://youtu.be/qRhviLAFX8k  (Spawn trope again but this time I used a fresh water source to test to see if the ocean waves were causing this glitch.)
https://youtu.be/jcPFnz8q_9c  (Explained on how to perform)

**Branch Version**
Both

**Character Information**
I've tested it with & without talents, 1.2 & .4 so it's safe to say that no talents or inherits are affecting it.

**Additional Information**
Again this might take a few tries simply because you have to hold down multiple buttons and the timing of it but it can be done. I've managed to do this numerous times when I finally got the hang of it. Anyone can do this at any size, no points or inherits required.

**Comment by Vallyhalla** [comment]
This happens on Ptera as well. Pred hasn't been able to fix this yet, so I'm closing this since there's more than one report open about this atm.
