### ISSUE TITLE
Jumping on a nest kicks you out of the burrow

### ISSUE THREAD

**Issue by Falcarius9** [BoBAdministration/QA-Bug-Reports#44]
**Describe the Bug**
As a Velo or Ory, jumping on a nest in a burrow will insta-boot you out of the burrow

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Construct a burrow as an Ory
2. Construct a nest to lay an egg in it or even just constructing a fresh nest
3. Jump on the nest 
4. It teleports you out of the burrow

**Expected behavior**
Natural jumping on nest behavior, no teleports

**Actual behavior**
Jumping on the nest teleports you out of the burrow, regardless of species

**Screenshots & Video**
https://user-images.githubusercontent.com/57926053/130710812-7fa9ecb7-fdc7-41ba-a021-2727a9b2aaea.mp4

**Branch Version**
Tester 

**Character Information**
1.2 Velo/Ory 
Ory: Full Speed, 3/3 GP, 1 Adrenaline
Velo: 3/3 combat to Vigilance 

**Additional Information**
Rival Shores, clear weather

**Comment by Zi-Mom** [comment]
Confirmed
