### ISSUE TITLE
Placing your creature's face into tree-foliage gives the player a breath bar.

### ISSUE THREAD

**Issue by paratea** [BoBAdministration/QA-Bug-Reports#440]
**Describe the Bug**
A breath bar appears when a player's face is inside a tree.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log into a Titania server on any creature.
2. TeleportAt 112202.898438, 508510.718750, -11232.657227
3. Place your creature's face into the palm tree.
4. A breath bar appears.

**Expected behavior**
Trees can be looked or pushed into without a breath bar.

**Actual behavior**
Trees cause players to not be able to breathe.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/77513445/199390904-791f977a-accf-44b9-ab31-6bc345bf9224.png)

**Branch Version**
Tester

**Character Information**
This applies to rex, coach, ory, velo at various sizes, so the assumption is it will work regardless of creatures.

**Additional Information**
Palm trees, salt rocks, orange trees, other edible non-small foliage, shelters, ory burrow walls and objects.

**Comment by Vallyhalla** [comment]
![breath1](https://user-images.githubusercontent.com/96442596/199391610-32f14fc6-d351-4769-b0e0-5e50d50c941a.png)

**Comment by Zelryn** [comment]
[https://i.imgur.com/JpefX01.png](url)

**Comment by Zelryn** [comment]
![JpefX01](https://user-images.githubusercontent.com/116113475/199391745-77d82a4b-846c-495c-8fbd-97cf1740361d.png)

**Comment by Zelryn** [comment]
![k7494Lt](https://user-images.githubusercontent.com/116113475/199391857-3cf79884-777d-4bbe-8299-3cf59bf90fca.jpeg)

**Comment by Vallyhalla** [comment]
![breath5](https://user-images.githubusercontent.com/96442596/199392127-b1620b1e-fce3-450b-bd81-f36260d31a23.png)

**Comment by Zelryn** [comment]
![it4azWG](https://user-images.githubusercontent.com/116113475/199392206-dba5b7af-4d05-4498-a47c-8b52c3057671.png)

**Comment by Zelryn** [comment]
![25CKEDv](https://user-images.githubusercontent.com/116113475/199392352-0af59ffe-03b7-4a88-ba7e-ec47eb898148.png)

**Comment by Zelryn** [comment]
![nfQYgRz](https://user-images.githubusercontent.com/116113475/199392674-8d02d618-f93e-44ce-bc57-44d506cd7dc9.png)

**Comment by Zelryn** [comment]
![mtVLS7Y](https://user-images.githubusercontent.com/116113475/199392904-04512ea7-dea8-4ab8-aff1-7b72d497c6bf.png)

**Comment by Zelryn** [comment]
![x0YdLPj](https://user-images.githubusercontent.com/116113475/199393702-2aef72fe-dc1b-4a89-9e69-8696320137d3.jpeg)

**Comment by Vallyhalla** [comment]
This has been fixed!
