### ISSUE TITLE
Closed Server Join/Leave Loading Loops

### ISSUE THREAD

**Issue by Chipboard** [BoBAdministration/QA-Bug-Reports#441]
**Describe the Bug**
When joining/leaving a closed server, the player gets stuck in a loading loop.

**To Reproduce**
1. Log into Dedicated Testing 12 as **Client**
2. Choose a dinosaur to play as, and **spawn in**
3. **Shut down** Dedicated Testing 12 **until these instructions are over**
4. **Leave** Dedicated Testing 12 **before** the game kicks you out
5. Get stuck in a loading loop
6. **Force close the application** while stuck in loading loop
7. **Restart** your Beasts Of Bermuda **Client**
8. Click **Join Last Played Server** and **join** with the password
9. **Observe** infinite loading loop

**Expected behavior**
**Upon Leaving:** I expected to be able to leave the server and return to the menu.
**Upon Joining:** I expected the rejoining to fail, and to be booted back to the menu with a connection failure message.

**Actual behavior**
**Upon Leaving:** I am stuck in a loading loop, while I am still able to control my Ory behind the UI.
**Upon Joining:** I am stuck in a loading loop, and have to force close the application.

**Screenshots & Video**
[Joining](https://youtu.be/FgGNx38YzfM)
[Leaving](https://youtu.be/c2UZMqPBvE8)

**Branch Version**
Tester

**Notes**
Dino was an adult Ory

**Comment by Vallyhalla** [comment]
Closing this since the videos have been taken down.
