### ISSUE TITLE
Nesting not putting you in right egg with multiple mates.

### ISSUE THREAD

**Issue by Zelryn** [BoBAdministration/QA-Bug-Reports#445]
**Describe the Bug**
Nesting Bug - Issue #10277
When accepting people into your nest if you have multiple mates you end up in the wrong eggs.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log into game as a Sai
2. Grow to mating age.
3. Find 2 Female Sais to mate with
4. Place the nests down
5. Put the eggs down
6. Have a person attempt to get into the eggs with the second female to put eggs down
7. You will end up in the wrong set of eggs.

**Expected behavior**
You should end up in the correct parents eggs.

**Actual behavior**
When nesting you end up in the wrong parents eggs no matter how many times you try. You have to /nest to get them into the correct egg.

**Screenshots & Video**
If applicable, add screenshots to help explain your problem, or attach a video/gif. You can do this by just pasting in your image(s)!
https://github.com/Thy-Vipe/BeastsOfBermuda-issues/issues/10277

**Branch Version**
 Live and Tester

**Comment by BackwaterOtter** [comment]
Updated notes:

When testing this, we found that players would only enter the wrong egg when the second female parent is unable to accept the request to take the egg. 

When testing with 2 males and 1 female, we found that it would default to the egg from the first male they nested with.

**Comment by Vallyhalla** [comment]
This has been fixed!
