### ISSUE TITLE
Para can Alarm Call with a baby in its mouth

### ISSUE THREAD

**Issue by Zelryn** [BoBAdministration/QA-Bug-Reports#447]
**Describe the Bug**
Para while carrying a baby can alarm call things. Issue #10270

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log into Testing server
2. Spawn on and grow as a para
3. Carry a baby ' In your group' 
4. Z call at a target 
5. You can Z call around the baby with it still in mouth.

**Expected behavior**
Not be able to do a call with a baby in your mouth.

**Actual behavior**
Carrying a baby you are able to Z call other dinos.

**Screenshots & Video**
If applicable, add screenshots to help explain your problem, or attach a video/gif. You can do this by just pasting in your image(s)!
https://github.com/Thy-Vipe/BeastsOfBermuda-issues/issues/10270

**Branch Version**
Tester and Live

**Character Information**
1.2 Para carrying a baby

**Comment by Vallyhalla** [comment]
You can Z call while carrying anything, so this doesn't seem to be a bug at all. Closing this.
