### ISSUE TITLE
Eggs Float Into Sky After Flood

### ISSUE THREAD

**Issue by BackwaterOtter** [BoBAdministration/QA-Bug-Reports#449]
**Describe the Bug**
When flooding, eggs stay below the water's surface. When a player enters and leaves the egg, it proceeds to float to the surface, then pass the surface.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 1
2. Spawn in on Megaraptors
3. Mate and produce an egg.
4. Use commands to raise the water level such that the egg would need to float up.
5. Have a player enter and leave the egg.
6. Watch the egg ascend into space.

**Expected behavior**
The egg stops rising at the surface of the water.

**Actual behavior**
The egg continues past the water's surface and way off into the sky.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/24828337/199834065-811f2cce-3bed-4c74-a908-58cf0f297252.png)

**Branch Version**
Both

**Character Information**
1.2 Megaraptors.

**Additional Information**
https://github.com/Thy-Vipe/BeastsOfBermuda-issues/issues/10233|

**Comment by Vallyhalla** [comment]
This was brought up in another issue that I closed. The game thinks you've crashed and ascends like when you crash and your creature keeps walking forward.
