### ISSUE TITLE
Water drain shows on fish with no water stats

### ISSUE THREAD

**Issue by Chipboard** [BoBAdministration/QA-Bug-Reports#458]
**Describe the Bug**
Water drain message shows on fish with no water stats

**To Reproduce**
1. Play as mosa
2. watch drain stats on left

**Expected behavior**
I expected stats that were relevant to show

**Actual behavior**
It displays a water drain stat that does not exist for mosa

**Screenshots & Video**
![BeastsOfBermuda_tcMH9K4brR](https://user-images.githubusercontent.com/21075123/200182166-02bbe125-8121-4e63-8cd7-c089d30930d9.jpg)

**Branch Version**
Live

**Character Information**
Mosa

**Additional Information**
Ocean, Titania

**Comment by Predatoria** [comment]
Small display bug.  This is supposed to be air.
