### ISSUE TITLE
Wei fits in 1x1x3 burrow

### ISSUE THREAD

**Issue by Chipboard** [BoBAdministration/QA-Bug-Reports#459]
**Describe the Bug**
wei fits in smol space and bites ory

**To Reproduce**
1. get chased by wei
2. run into burrow
3. have wei willing to enter burrow

**Expected behavior**
i expected a wei of such magnitude to be too large to fit

**Actual behavior**
wei bends earth to bite ory

**Screenshots & Video**
https://youtu.be/sz99q0vLkiI
![image](https://user-images.githubusercontent.com/21075123/200182622-fb82db27-01d2-48b4-9efa-2e80ad54a898.png)

**Branch Version**
Live

**Character Information**
Ory & Wei

**Additional Information**
Titania & Burrow

**Comment by Predatoria** [comment]
Not a bug.  It's capsule size related.
