### ISSUE TITLE
Wei eggs still listed as Megalosaurus eggs

### ISSUE THREAD

**Issue by Chipboard** [BoBAdministration/QA-Bug-Reports#461]
**Describe the Bug**
Wei eggs still listed as Megalosaurus eggs

**To Reproduce**
1. try to choose a wei egg and read the name

**Expected behavior**
the rename to be consistent

**Actual behavior**
rename is inconsistent

**Screenshots & Video**
![wei](https://user-images.githubusercontent.com/21075123/200183016-962882e5-0ee6-460f-9e7b-32368b8398e5.png)

**Branch Version**
Live

**Character Information**
wei egg in menu

**Additional Information**
titania, character menu

**Comment by SilverWing430** [comment]
Fixed
