### ISSUE TITLE
Rex can bite sai through mesh, but Sai cannot hit it back

### ISSUE THREAD

**Issue by Chipboard** [BoBAdministration/QA-Bug-Reports#462]
**Describe the Bug**
Rex is so large that it's reaching over top of the mesh, but Sai cannot hit it back

**To Reproduce**
1. Have a sai on top of dock, rex below dock
2. With the rex head clipping through the dock, have it attack the sai
3. Notice the sai cannot hit it back

**Expected behavior**
Expected docks to stop rex from biting the sais on top, or the sai to be able to defend itself

**Actual behavior**
Rex attacks phase through and bite the sai while the sai is left defenseless

**Screenshots & Video**
https://youtu.be/pcrS40hvx7w

**Branch Version**
Live

**Character Information**
Sai & Rex

**Additional Information**
Map: Titania
Worth mentioning that sais keep getting stuck around this area

No coordinates, but it's a very specific area
Bridge off of Spiral Island
Towards Palm Paths

**Comment by Vallyhalla** [comment]
Since there's no video anymore with this showing what's happening, I'm going to close. The problem is drag biting on the rex and the sai tail hitbox being wonky.
