### ISSUE TITLE
Banana Tree LOD Shows Eaten Bananas

### ISSUE THREAD

**Issue by Chipboard** [BoBAdministration/QA-Bug-Reports#463]
**Describe the Bug**
Even if the bananas have been eaten, the distance LOD tricks you into thinking it still has bananas

**To Reproduce**
1. Eat bananas off tree
2. leave area until LOD changes
3. observe banana mirage

**Expected behavior**
I expected the tree to either have/not have bananas

**Actual behavior**
Tree has no bananas but makes me think it does

**Screenshots & Video**
https://user-images.githubusercontent.com/21075123/200186240-60a355ab-ac1c-4767-be4a-76b7f33b5f78.mp4

**Branch Version**
Live

**Character Information**
Para

**Additional Information**
Titania

**Comment by Peter22FIN** [comment]
Pretty sure this was fixed already? Can this be double checked?

**Comment by Undercooked-Mothman** [comment]
has been fixed!
