### ISSUE TITLE
Calling As Fresh Egg Causes Freeze Frames

### ISSUE THREAD

**Issue by Chipboard** [BoBAdministration/QA-Bug-Reports#464]
**Describe the Bug**
When pressing a number (1-5) as a fresh egg, the program momentarily freezes

**To Reproduce**
1. Get a fresh random map egg
2. number call
3. observe freezing while call is pressed

**Expected behavior**
no freeze

**Actual behavior**
freezes for a split second

**Screenshots & Video**
https://youtu.be/C_0d_zZCjz4

**Branch Version**
Live

**Character Information**
Any egg

**Additional Information**
Titania
Each button causes a freeze, individually, but after a call is pressed, the freeze does not re-activate for that specific call.
It's as if a loading resource is causing a lot of buffering, then once it's loaded, it's fine.

**Comment by SilverWing430** [comment]
Fixed
