### ISSUE TITLE
Infinite Kapok trees

### ISSUE THREAD

**Issue by Skyedrago** [BoBAdministration/QA-Bug-Reports#465]
**Describe the Bug**
Kapok trees, which are normally inedible, can be picked up and eaten indefinitely 

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log into a Titania server
2. Spawn as a large dino (ie. apa)
3. Go toward a kapok tree
4. Attempt to grab the tree
5. When tree is grabbed, set it down
6. Eat

**Expected behavior**
The kapok tree is inedible and cannot be picked up or eaten

**Actual behavior**
The kapok tree is able to be picked up indefinitely and is edible

**Screenshots & Video**
![20221107133931_1](https://user-images.githubusercontent.com/96404852/200389679-765af0a9-dd50-429f-ac08-db2ed04e14db.jpg)
![20221107134327_1](https://user-images.githubusercontent.com/96404852/200389681-75017434-ea3f-472f-91ee-8f9f2f2df1c3.jpg)

**Branch Version**
Live

**Character Information**
Tested on a ~2.0 apa

**Additional Information**
Titania and presumably other maps with the same tree model

**Comment by MarshmallowMaiden** [comment]
Tree is inedible however you are still able to infinitely grab it. 
https://www.youtube.com/watch?v=IM9kZ6luVmE
