### ISSUE TITLE
Wiehenvenator stills appears as Megalosaurus when joining a group

### ISSUE THREAD

**Issue by Akaraasaur** [BoBAdministration/QA-Bug-Reports#466]
**Describe the Bug**
Wiehenvenator stills appears as Megalosaurus when joining a group

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Creat a group
2. Have 1 player as Wiehenvenator joining your group
3. The pop up message asking to accept or no the player shows them as Megalosaurus

**Expected behavior**
Wiehenvenator should appears as Wiehenvenator when joining a group

**Actual behavior**
Wiehenvenator appears as Megalosaurus when joining a group

**Screenshots & Video**
<img width="294" alt="Screenshot_300" src="https://user-images.githubusercontent.com/96403359/200419388-7fc68ed2-f9da-47c7-8fa1-18d7ae39803e.png">

**Branch Version**
Live

**Character Information**
Wiehenvenator, any gender, any size

**Additional Information**
/

**Comment by SilverWing430** [comment]
fixed
