### ISSUE TITLE
State jam: Drinking in screenshot mode

### ISSUE THREAD

**Issue by theriversedge** [BoBAdministration/QA-Bug-Reports#468]
**Describe the Bug**
Drinking at a water source while in screenshot mode causes your creature to continuously drink, even after exiting screenshot mode. You cannot move while this is happening. Entering and exiting the O menu fixes it. 

**To Reproduce**
1. Logged into Official 1 East US
2. Spawned in as a Coahuilaceratops
3. Entered screenshot mode while within a small water source
4. Pressed the Use key and began drinking without needing to hold the key down
5. Exited screenshot mode
6. Tried to move to cancel drinking, remained stationary while drinking
7. Opened and closed the O menu, restoring control of my creature

**Expected behavior**
Pressing the Use key near a water source while in screenshot mode should not cause your creature to continuously drink without holding the key down, and movement should still be possible

**Actual behavior**
Pressing the Use key near a water source while in screenshot mode causes your creature to continuously drink without holding the key down, and movement is not possible without opening and closing the O menu

**Screenshots & Video**
N/A

**Branch Version**
Live

**Character Information**
1.282 Coahuilaceratops

**Additional Information**
Isla Titania, Jungle Highlands

**Comment by Vallyhalla** [comment]
I tried to replicate this and when I release the the use key my character automatically stops! Closing this now.
