### ISSUE TITLE
Alt+turning breaks acro tail.

### ISSUE THREAD

**Issue by Romanov0** [BoBAdministration/QA-Bug-Reports#47]
**Describe the Bug**
When using alt and turning the acro tail breaks while meshing.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 2.
2. Spawned in a Acro.
3. Pressed alt, looked up and entered screenshot mode to keep the head in place.
4. While turning and walking around the tip of the tail broke off and up.

**Expected behavior**
Tail keeping in place.

**Actual behavior**
The tail cuts off and faces up.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/89394401/130712723-ee13159e-29c7-4e2a-8de6-23dba37d8f9e.png)
![image](https://user-images.githubusercontent.com/89394401/130712812-513ae3a2-14c8-414f-8dc0-31404d24b6fc.png)
https://cdn.discordapp.com/attachments/605979793716019205/879904700621795369/unknown.png
https://cdn.discordapp.com/attachments/605979793716019205/879904631654842418/unknown.png

**Branch Version**
Tester and Live.

**Character Information**
Tested on a 1.2 acro.

**Additional Information**
Use alt, look up and turn.

**Comment by tinystarpaws** [comment]
This will not be fixed. Acro will eventually be re-animated.
