### ISSUE TITLE
Fish Only Visible Through Trope Mesh

### ISSUE THREAD

**Issue by Chipboard** [BoBAdministration/QA-Bug-Reports#471]
**Describe the Bug**
Fish highlight only visible through trope mesh

**To Reproduce**
1. Play 0.8 Trope
2. Smell for fish while angling camera through trope to view fish

**Expected behavior**
Visible fish behind trope

**Actual behavior**
Visible fish in front of trope

**Screenshots & Video**
https://youtu.be/uZ6CUCBBqwU
![image](https://user-images.githubusercontent.com/21075123/200681495-ace95748-aba9-43a3-a685-3ba61d02e7ab.png)

**Branch Version**
Live

**Character Information**
.8 Trope

**Additional Information**
(X=492527.250000, Y=562915.562500,Z=-9031.028320)
Look for small red spots in trope, compression killed it but they're there (barely) in the image & video

**Comment by Vallyhalla** [comment]
This happens with everything that has aqua affinity. You can see fish across the map, this has always been a thing and helps people find fish.
