### ISSUE TITLE
Skin highlight suddenly turns on after skin menu

### ISSUE THREAD

**Issue by Chipboard** [BoBAdministration/QA-Bug-Reports#477]
**Describe the Bug**
When taking off after looking at skin modify menu, the skin highlights seconds after

**To Reproduce**
1. Reincarnate Tropeo
2. Check skin menu
3. Close skin menu when hovering over slot
4. Skin Issue

**Expected behavior**
Nothing

**Actual behavior**
Skin Issue

**Screenshots & Video**
https://youtu.be/GWoWHY6dfQg

**Branch Version**
Live

**Character Information**
Trope

**Additional Information**
It seems to have turned on at a similar time that it told me I have talent points available
Titania

**Comment by Vallyhalla** [comment]
Could not replicate, and the video was deleted. Closing this.
