### ISSUE TITLE
Floating rocks.

### ISSUE THREAD

**Issue by Romanov0** [BoBAdministration/QA-Bug-Reports#48]
**Describe the Bug**

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 2.
2. Spawned on a Ptera.
3. Teleported to X=156387.375 Y=100124.617 Z=-4811.098
4. Found floating rocks.

**Expected behavior**
Floating rocks.
**Actual behavior**
Either being attached to the ground or gone.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/89394401/130714698-152bbc35-a759-400f-a51f-cae979328a45.png)

**Branch Version**
Tester and Live.

**Character Information**
Not important.

**Additional Information**
Rival Shores.

**Comment by teatimejess** [comment]
Confirmed fixed.
