### ISSUE TITLE
Mosasaurus bugged with specific portals depending on size

### ISSUE THREAD

**Issue by BackwaterOtter** [BoBAdministration/QA-Bug-Reports#488]
**Describe the Bug**
When attempting to enter the Underwater Survival Shrine portal to go to Palm Forest Lake, or the portal to go from Palm Forest Lake to the Underwater Survival Shrine, Mosa experiences a variety of negative results depending on their size.

**To Reproduce**
1. Logged into Dedicated Testing 12
2. Spawned in a 1.32 Mosasaurus at Kelp Forest
3. Attempted to enter the underwater Survival Shrine's portal
4. Was unable to go through to the other sides.
5. Spawned in a 0.9 Mosasaurus.
6. Teleported to underwater Survival Shrine
7. Attempted to enter the underwater Survival Shrine's portal
8. Was able to go through to Palm Forest Lake portal
9. Could not return through Palm Forest Lake portal
10. Spawned in a 0.8 Mosasaurus.
11. Teleported to underwater Survival Shrine
12. Was able to go through both portals.

**Expected behavior**
Mosasaurus is able to go through these portals regardless of size.

**Actual behavior**
Different sizes have different, unwanted outcomes, either being unable to go through both portals, or being able to go through one of the portals and not the other.

**Screenshots & Video**
N/A

**Branch Version**
Both.

**Character Information**
1.32 Mosa: Could not go through either end of the portals.
0.9 Mosa: Could go through the Survival Shrine portal, but could not return.
0.8 Mosa: Could go through bother portal ends.

**Additional Information**
N/A

**Comment by Vallyhalla** [comment]
Could not replicate, seems to be fixed!
