### ISSUE TITLE
Tip of Acro's tail breaks when holding 'Alt' and looking around.

### ISSUE THREAD

**Issue by teatimejess** [BoBAdministration/QA-Bug-Reports#5]
**Describe the Bug**
There is a frame hitch/snap when Acro looks around when holding alt.

**To Reproduce**
1. Spawn into Acro on any map
2. SetGrowthLevel 1.2 (optional for visibility)
3. Hold ALT
4. Look left and right while focusing on tail tip.

**Expected behavior**
Acro's tail is steady.

**Actual behavior**
Acro's tail snaps at a sharp angle.

**Screenshots & Video**
![acrotailtip](https://user-images.githubusercontent.com/77513445/129494045-aef8cd77-bf01-4d4d-b815-860a5b4723bb.png)
![image](https://user-images.githubusercontent.com/77513445/129494069-045d7a2d-ac06-40a5-991e-20f68a0d53cf.png)

**Branch Version**
Tester and Live.

**Character Information**
Acro, any growth, any map. 

**Additional Information**
N/A

**Comment by Predatoria** [comment]
We'd like to re-animate Acro in the future.  I'm going to mark this as won't fix for now.
