### ISSUE TITLE
Coahuila can walk and eat off of a carcass.

### ISSUE THREAD

**Issue by tinystarpaws** [BoBAdministration/QA-Bug-Reports#50]
**Describe the Bug**
Coahuila is able to eat off of a carcass while walking, which is something that not even full carnivores can do.

**To Reproduce**
1. Spawn in a Coahuila
2. SpawnCarcass 200 200 0
3. Line up and begin to eat from carcass
4. Press forwards to begin moving; you will still be eating

**Expected behavior**
Coahuila should be forced to be stationary while consuming a carcass

**Actual behavior**
Coahuila is able to walk after digging into some fleshy gooddness

**Screenshots & Video**
https://user-images.githubusercontent.com/38923098/130747387-cdd8743a-9a5a-43a6-b49e-ee0d3e8f767b.mp4

**Branch Version**
Tester branch.

**Character Information**
.9 Coahuila in video, can be done with any size Coahuila.

**Additional Information**
N/A

**Comment by teatimejess** [comment]
Tested following provided steps, confirmed fixed.
