### ISSUE TITLE
Still have negative bias after resurrection

### ISSUE THREAD

**Issue by SilverWing430** [BoBAdministration/QA-Bug-Reports#502]
**Describe the Bug**
Had negative bias before death, still had it after resurection

**To Reproduce**
1. Log on to Titania
2. Gain negative bias
3. Kill thyself
4. resurrect 
5. Look at character screen

**Expected behavior**
Expected no -bias on resurrection

**Actual behavior**
Had -bias after resurrection

**Screenshots & Video**
https://youtu.be/n81UV9-1dKA

**Branch Version**
Live

**Character Information**
tested on 1.2 Rex, and 1.2 Megaraptor 

**Additional Information**
From Vipes Github issue 10318

**Comment by Predatoria** [comment]
fixed
