### ISSUE TITLE
Wiehenvenator resurrection screen says Megalo

### ISSUE THREAD

**Issue by CeciliaSE** [BoBAdministration/QA-Bug-Reports#503]
**Describe the Bug**
When entering the resurrection screen for the Weiwei, the creature's name shows up as Megalosaurus.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log onto Live branch server
2. Spawn a weiwei
3. Die using any method
4. Return to CS (Character Select)
5. Press resurrect on the weiwei
6. Should show up as Megalosaurus

**Expected behavior**
It displays the new name.

**Actual behavior**
It displays the outdated name.

**Screenshots & Video**
https://www.youtube.com/watch?v=YsXefWmFj90 

**Branch Version**
Live

**Character Information**
Tested on a fresh spawn of random gender. Age/gender/death does not seem to affect the result.

**Additional Information**

**Comment by Zi-Mom** [comment]
Confirmed Fixed
