### ISSUE TITLE
Coah's leg movement in 1 call animation

### ISSUE THREAD

**Issue by DeadHawk** [BoBAdministration/QA-Bug-Reports#51]
**Describe the Bug**
Coah's leg movement in 1 call animation changes unnaturally

**To Reproduce**
1. Log into Dedicated Testing 2 server
2. Spawn in a Coah at Jungle
3. Set growth to 1.2 
4. Press 1 call
5. Coah's leg movement in 1 call animation changes unnaturally

**Expected behavior**
I expected the animation of Coah's leg movement to continue naturally like other call animations

**Actual behavior**
Unlike other call animations, only Coah's leg movement in 1 call animation changes unnaturally

**Screenshots & Video**
https://youtu.be/DwOEAnY3rwM

**Branch Version**
Tester branch

**Character Information**
1.2 growth Coahuilaceratops

**Additional Information**
Rival Shores

**Comment by Vallyhalla** [comment]
Fixed!
