### ISSUE TITLE
Burrow light displacement on exit

### ISSUE THREAD

**Issue by Chipboard** [BoBAdministration/QA-Bug-Reports#516]
**Describe the Bug**
Cancelling exit of burrow has chance to displace burrow light

**To Reproduce**
1. Log in Ory
2. Get in burrow
3. Start to leave burrow
4. Cancel leave burrow with movement

**Expected behavior**
Nothing, just drop

**Actual behavior**
Burrow light displacement

**Screenshots & Video**
https://youtu.be/nyH56E3mb9A?t=12

**Branch Version**
Tester

**Character Information**
1.8 Ory, 3/3 swift claws

**Additional Information**
Titania

**Comment by Vallyhalla** [comment]
Closing this!
