### ISSUE TITLE
Footstep sounds cut out on mud and sand

### ISSUE THREAD

**Issue by Skyedrago** [BoBAdministration/QA-Bug-Reports#519]
**Describe the Bug**
Sound cuts out on certain surfaces

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log into a server
2. Spawn as any dino (the person reporting this bug to me was a trop)
3. Walk over a muddy or sandy surface
4. Footstep sounds occasionally cuts out

**Expected behavior**
Footsteps make noise regardless of the surface

**Actual behavior**
Noise cuts out at particular spots

**Screenshots & Video**
https://cdn.discordapp.com/attachments/494942972740370432/1061320227356418160/ground_sound_go_poof.mp4

**Branch Version**
Live.

**Character Information**
The player in the video was a tropeo. Not sure of the growth, but growth and dino type seems to be irrelevant based on a conversation with someone else who has experienced this bug.

**Additional Information**
Spoke with others and found out it also happens on Rival Shores along with Titania, as well as on sand and mud in particular. Grass on occasion. This bug was reported to me by a player and so the above video was sent to me as evidence.

**Comment by Vallyhalla** [comment]
Tested this and it seems to be fixed! I can hear my footsteps consistantly in this area
