### ISSUE TITLE
New jungle tree collisions

### ISSUE THREAD

**Issue by Sa0327** [BoBAdministration/QA-Bug-Reports#52]
**Describe the Bug**
Collisions where the distance from the tree is not right

**To Reproduce**
1. Log into Dedicated Testing 2 server
2. Spawn in a Coah at Jungle
3. Walk around the new jungle tree
4. Find collisions where the distance from the tree is not right

**Expected behavior**
I expected collisions with the right distance from the tree

**Actual behavior**
I found collisions where the distance from the tree is not right

**Screenshots & Video**
https://youtu.be/B0Ry4-yxjk0

**Branch Version**
Tester branch

**Character Information**
All type of growth Coahuilaceratops

**Additional Information**
Rival Shores

**Comment by teatimejess** [comment]
Tested, seems to be fixed. Able to walk around the base without collision issues.
