### ISSUE TITLE
Herbis can eat bones

### ISSUE THREAD

**Issue by Akaraasaur** [BoBAdministration/QA-Bug-Reports#526]
**Describe the Bug**
When holding the eating button on bones (empty carcasses), herbis can eat them. Eating bones as herbi doesn't give you food. Bones can also be carried.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into any server
2. Find an empty carcass
3. Tap/hold your eating button on it
4. You're eating the bones.
5. You can also grab the bones by double hitting you use button.

**Expected behavior**
You shouldn't be able to eat bones as herbivore.

**Actual behavior**
You can eat bones as herbivore.

**Screenshots & Video**
https://youtu.be/wOtUBUH0G18

![image](https://user-images.githubusercontent.com/96403359/217530220-98c20e20-330b-4bed-b57c-9ada64b25804.png)

**Branch Version**
Live

**Character Information**
Any herbivore

**Additional Information**
/

**Comment by Vallyhalla** [comment]
This seems to be fixed! I can't pick up the empty carcasses and haven't been able to eat various levels of empty gores! I'm closing this now.
