### ISSUE TITLE
When changing settings, food/water/air bars change.

### ISSUE THREAD

**Issue by QueenIcy** [BoBAdministration/QA-Bug-Reports#53]
**Describe the Bug**
When you apply changed settings the omnivore bar appears empty when it is not empty <Visual bug>
When you apply changed settings on Itchy/elasmo water/air is changed to another food bar. <Reverts to normal when relogging/spawning.>
When done on herbivore both food and water bars are swapped to carnivorous<meat> bar.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log onto DED2
2. Spawn as any creature.
3. Go to settings hit apply, then exit menu. Changing setting IS NOT needed simply hit apply.
4. The omnivore bar looks completely empty when it is not. 
On fish eaters the air bar is layered with the meat bar.
On herbivore water and food bars are changed to meat.

**Expected behavior**
When changing settings they should only change gameplay in the way specified.

**Actual behavior**
When changing settings is changes the food/air/water bars in unintended ways.

**Screenshots & Video**
If applicable, add screenshots to help explain your problem, or attach a video/gif. You can do this by just pasting in your image(s)!

![20210825084749_1](https://user-images.githubusercontent.com/89404235/130812795-0e41012c-feed-45cc-9e96-45e8d5fdcacd.jpg)
![20210825084757_1](https://user-images.githubusercontent.com/89404235/130812810-0c91f8a6-bdd3-47b1-b661-2725adf3381b.jpg)

**Branch Version**
Tester

**Character Information**
Any dinosaur, any growth.

**Additional Information**
RS

**Comment by CeciliaSE** [comment]
Still an issue on Live branch.

**Comment by 0fivu0** [comment]
Confirmed fixed on tester. (Tested all dino types.)

**Comment by SilverWing430** [comment]
Followed the replication steps, the stamina bar is now included on the list of things that turn to meat (all maps, all dinos)
![image](https://user-images.githubusercontent.com/116122955/204066407-7cae08e2-125c-40f0-a415-aac962b1b15a.png)

**Comment by Vallyhalla** [comment]
Haven't been able to replicate this, so I'm closing for now .

**Comment by Zi-Mom** [comment]
Still an issue, related now to specifically changing the hud itself. However not able to record replication so will re-close until able to discover reliable replication
