### ISSUE TITLE
Increased Speed Attack Bug

### ISSUE THREAD

**Issue by Dinorunp** [BoBAdministration/QA-Bug-Reports#530]
**Describe the Bug**
This bug is a bug where  the player's dino will have increased attack speed after the player attacks and mid attack they press unjam and it causes them to be able to spam attack bypassing the animation

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. log onto test server
2. Spawn in as dino
3. Press right or left mouse button 
4. press unjam while in attack animation
5. do the attack you want to have increased attack rate on (Para stomp, apa neckswing, rex downbite, etc)

**Expected behavior**
Player pressed unjam and is unable to attack at all till the text disappears 

**Actual behavior**
Player is able to attack mid unjam and is able to attack at a very increased rate 

**Screenshots & Video**
https://youtu.be/wwCCj6Ss3_U

**Branch Version**
Live

**Character Information**
Nothing is needed other then it really depends on what dinos it works on mainly being para, apa, coah, rex and maybe other but they were the main one I tested on 

**Additional Information**
Gameplay Bug. low priority. Graphic

**Comment by CeciliaSE** [comment]
It is fixed by forcing the player to stay still in the pause menu for the ability to press unstuck. I have not found a way around it, and will consider this fixed!
