### ISSUE TITLE
Portal causes damage to some dinos when teleporting 

### ISSUE THREAD

**Issue by SilverWing430** [BoBAdministration/QA-Bug-Reports#538]
**Describe the Bug**
Taking the portal causes fall damage to bigger dinos

**To Reproduce**
1. Enter dedi 12
2. Choose a dino (Rex, Coah, Acro, Sai, Apa)
3. Spawn
4. Grow to 
       .6 for rex
       .9 for acro
       .8 for sai
       .9 for apa
       .8 for coah
5. Go to the spiral portal
6. Go through the spiral portal
7. Watch as you take damage

**Expected behavior**
I expected for there to be no damage when i went through the portal

**Actual behavior**
You take damage, the hurt noise happens, bones crack and the edges of the screen get bloody and you loose health and take injury

**Screenshots & Video**
https://www.youtube.com/watch?v=TBHM4Sa6JN8&ab_channel=SilverWing
https://youtu.be/lYSnxYZacl8

**Branch Version**
Tester

**Character Information**
Minimum growths for damage to happen 
       .6 for rex
       .9 for acro
       .8 for sai
       .9 for apa
       .8 for coah

**Additional Information**
Portal Location: 147447.718750, 645950.687500, -5738.582031
Also, not sure if this was being worked on already, but I figured it wouldnt hurt to put it in here
From Vipes Github issue 10422

**Comment by KattofKits** [comment]
This happens on RS as well. 
https://youtu.be/RCU9zKTIWv4

**Comment by CeciliaSE** [comment]
Confirmed fixed! The issue can now be closed
