### ISSUE TITLE
Any male juvie can lay a nest.

### ISSUE THREAD

**Issue by QueenIcy** [BoBAdministration/QA-Bug-Reports#54]
**Describe the Bug**
When you spawn as a make juvie creature <.4> you can place a nest.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log on a DED server.
2. Spawn as any male.
3. Press your nest button.
4. You place a nest as a juvie.

**Expected behavior**
Juvies should not be able to place nests as they are too young.

**Actual behavior**
Any baby male can place a nest.

**Screenshots & Video**
If applicable, add screenshots to help explain your problem, or attach a video/gif. You can do this by just pasting in your image(s)!

![20210825085734_1](https://user-images.githubusercontent.com/89404235/130814564-960d28ce-9ec5-49f8-a66e-704e13957f56.jpg)

**Branch Version**
Tester

**Character Information**
Male Spawn 

**Additional Information**
Any

**Comment by teatimejess** [comment]
Confirmed fixed, unable to place nest until 0.8
