### ISSUE TITLE
Force respawning a hatchling drops a carcass but only on client side

### ISSUE THREAD

**Issue by Akaraasaur** [BoBAdministration/QA-Bug-Reports#545]
**Describe the Bug**
When you force respawn as a hatchling you can see that you drop a carcass. The other can't see it. The carcass looks like it's not good to eat. But you can't eat from the carcass. When you force respawn multiple hatchlings you ended with multiple unedible carcasses that can drop fps.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Take an egg from a nest
2. Hatch
3. Wait a bit for a growth tick then force respawn
4. You can see that you dropped a carcass

**Expected behavior**
When you force respawn as a hatchling you should drop an empty carcass visible for everyone.

**Actual behavior**
When you force respawn as a hatchling you drop a carcass only visible for you and non edible/movable despite having meat on it.

**Screenshots & Video**
https://youtu.be/PVbzbsqGBW0

Lurdu parent view :
![image](https://user-images.githubusercontent.com/96403359/225321247-1d322760-a783-4b3e-bfd1-544bb12d9a25.png)

**Branch Version**
Live.

**Character Information**
Any dinosaur, hatchling after the first growth tick

**Additional Information**
Any server
(I heard people were complaining about this visual bug when they were trying eggs from a nest. They said after a lot of force respawning it causes lag on their side.)

**Comment by Vallyhalla** [comment]
This is known and was reported previously since the same thing happens with eggs that you force respawn. Going to close this for now!
