### ISSUE TITLE
Female Juv Ptera model broken on CS

### ISSUE THREAD

**Issue by CeciliaSE** [BoBAdministration/QA-Bug-Reports#547]
**Describe the Bug**
When going to spawn in a female ptera, the model is distorted and broken. This is most visible on the beak and crest, with the beak being bent and missing pieces and the crest being crumpled into a mess.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log onto Dedicated testing 12
2. Go to spawn in a ptera
3. Press the female icon
4. The ptera model that pops up will be broken

**Expected behavior**
The model looks as it would when spawned in without distortions.

**Actual behavior**
The model is noticeably broken and disfigured during skin editing before spawning in.

**Screenshots & Video**
https://www.youtube.com/watch?v=ZnmSuexTw1Q

**Branch Version**
Tester

**Character Information**
Non-spawned, 0.4, female ptera

**Additional Information**
It fixes itself when spawned in, so I am very sure that this is an issue specific to the model used before spawning in.

**Comment by Predatoria** [comment]
I may have fixed this.  It won't reproduce in UE4.

**Comment by Zi-Mom** [comment]
Confirmed fixed
