### ISSUE TITLE
Visual bug of the ptera wings

### ISSUE THREAD

**Issue by Akaraasaur** [BoBAdministration/QA-Bug-Reports#550]
**Describe the Bug**
The pteranodon's wings sometimes appear larger to other players when the character is on the ground.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log on any server
2. Select Pteranodon
3. The other players can see you with larger wings than normal

**Expected behavior**
The wings of the pteranodon should keep their normal size when the creature is on the ground.

**Actual behavior**
The wings of the pteranodon are sometime larger than normal when the creature is on the ground.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/96403359/227790181-c91e0fe0-f3c8-42a3-b4bd-0607371e7842.png)
![image](https://user-images.githubusercontent.com/96403359/227790260-1a3206fc-3a7e-4383-afdb-3b5ed58e68bc.png)
![image](https://user-images.githubusercontent.com/96403359/227790273-b483a873-1cd7-46ff-8264-8d790ed2754c.png)

**Branch Version**
Tester branch

**Character Information**
Pteranodon, any gender, any size

**Additional Information**
/

**Comment by Zi-Mom** [comment]
Confirmed fixed through patchnotes
