### ISSUE TITLE
Players are able to nest exclusive skins without owning them

### ISSUE THREAD

**Issue by Akaraasaur** [BoBAdministration/QA-Bug-Reports#551]
**Describe the Bug**
Players are able to nest shimmer and glimmer skins without owning it after reincarnation.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Nest with 2 shimmer or glimmer owners
2. Have a player take an egg of each
3. Reincarnate, one player as to not be related but still have the exclusive skin
4. Mate those two players and they will produce default Shimmer/Glimmer babies with no customization options

**Expected behavior**
Players shouldn't be able to give shimmer/glimmer skins if they don't own them

**Actual behavior**
Players are able to nest shimmer and glimmer skins without owning it

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/96403359/228083401-d5f17034-76ef-442c-9bbf-227c7c1fc9a3.png)

**Branch Version**
Live branch

**Character Information**
Shimmer/glimmer parents (owned)

**Additional Information**
This need to be tested to confirm the bug since we need 2 differents exclusive skins owners.

**Comment by Thy-Vipe** [comment]
I was able to reproduce this behavior. It outputs a semi empty shimmer skin, but the glow is not available, so this behaves as expected. The skin is broken, however, and I do not plan on fixing this on the current skin system, a new implementation is coming that adresses that kind of behavior. Nesting with that skin results in more broken skins. Closing.
