### ISSUE TITLE
1 guardian/1 non guardian apa nesteing

### ISSUE THREAD

**Issue by SilverWing430** [BoBAdministration/QA-Bug-Reports#554]
**Describe the Bug**
nesting with 1 guardian apa and 1 non guardian apa gave random skins to the offspring instead of passing the non guardian parents skin.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged in to dedi 12
2. took an apa egg from a guardian apa and a nonguardian apa parent
3. hatched

**Expected behavior**
should have been passed the skin from my non guardian parent

**Actual behavior**
took 2 eggs, got a random skin for each, but the second one was glimmer apa and i do not own it

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/116122955/229686920-45a6fa85-0345-4257-9560-2db24f922735.png)

**Branch Version**
Tester

**Character Information**
 a guardian apa and a nonguardian apa parents

**Additional Information**
titania

**Comment by Thy-Vipe** [comment]
Did any of the parent own the glimmer?
It's not the player TAKING the egg that determines if you can use the skin, it's the parents.
