### ISSUE TITLE
Full-body bio on Crested Grebe Tropeo

### ISSUE THREAD

**Issue by tinystarpaws** [BoBAdministration/QA-Bug-Reports#56]
**Describe the Bug**
Tropeo is able to obtain a full-body bio using the Crested Grebe skin. The layer that seems to mutate is called "Cover" under the Markings category.

**To Reproduce**
1. Spawn in a Tropeo
2. MakeBrood with self until undesired result is found

**Expected behavior**
The "Cover" layer should never be able to mutate bio lum

**Actual behavior**
The "Cover" layer mutates and causes full-body bio lum

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/38923098/131201067-840c766f-80b3-4e1f-9d45-26d812512abf.png)
![image](https://user-images.githubusercontent.com/38923098/131201078-c6e5b0aa-a6e7-4247-84d7-20ab5ffb2c1d.png)

**Branch Version**
Found on Live branch

**Character Information**
Tropeo of any size.

**Additional Information**
N/A

**Comment by Soals** [comment]
Fixed

**Comment by CeciliaSE** [comment]
After a long testing of making broods, I have been unable to get the shown bio mutation to appear. The ticket can be closed
