### ISSUE TITLE
Infinitely drinking glitch

### ISSUE THREAD

**Issue by Akaraasaur** [BoBAdministration/QA-Bug-Reports#562]
**Describe the Bug**
There's a glitch that allow the player to drink water infinitely. It drains slowly all the water of the watersource. Here is one of the method to drink the water infinitely:

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Place plants or any grabbable objects into the water
2. Start drinking normally by hitting the interaction button
3. After that, quickly double hit the interaction button like if you want to grab the plants / objects in the water and hold the key
4. Open the chatbox while holding the key
5. You're now drinking infinitely

**Expected behavior**
You shouldn't drink infinitely the water and drains all the pond

**Actual behavior**
With this glitch you are able to drink infinitely and it allows player to drains all the pond

**Screenshots & Video**
https://youtu.be/vfXF2sVoNV4

**Branch Version**
Live

**Character Information**
Any dino, size, gender

**Additional Information**
/

**Comment by Predatoria** [comment]
I may have force fixed this
