### ISSUE TITLE
Grabbing carcass bug as Coah

### ISSUE THREAD

**Issue by Sa0327** [BoBAdministration/QA-Bug-Reports#57]
**Describe the Bug**
As soon as you grab the carcass, the grass around you is eaten automatically

**To Reproduce**
1. Log into Dedicated Testing 2 server
2. Spawn in a Coah at Forest
3. Set growth to 1.2
4. Grab the carcass on the grass
5. As soon as you grab the carcass, the grass around you is eaten automatically

**Expected behavior**
I expected to grab only the carcass

**Actual behavior**
As soon as you grab the carcass, the grass around you is eaten automatically

**Screenshots & Video**
https://youtu.be/0jPOlmmTFd8

**Branch Version**
Tester branch

**Character Information**
1.2 growth Coahuilaceratops

**Additional Information**
Rival Shores

**Comment by Predatoria** [comment]
I have brought this to Lifeon's attention.

**Comment by Predatoria** [comment]
Fixed it

**Comment by teatimejess** [comment]
Fixed confirmed via reproduction steps
