### ISSUE TITLE
Velo Falls Through Map When Exiting Ory Burrow

### ISSUE THREAD

**Issue by C-rimsonKnight** [BoBAdministration/QA-Bug-Reports#571]
**Describe the Bug**
When a Velo jumps to interact with an Ory burrow exit, the Velo will fall through the map instead of exiting the burrow properly.

**To Reproduce**
1. Log into a test server.
2. Spawn on to an Ory and create a burrow (if there isn't already an Ory burrow)
3. Go to creature select and spawn in on a Velo (preferably an adult)
4. Go to the burrow and enter it
5. Jump up and interact with the burrow exit at the same time.

**Expected behavior**
The Velo exits the burrow as normal.

**Actual behavior**
The Velo falls through the map.

**Screenshots & Video**
https://www.youtube.com/watch?v=qpb2nl0Xhps

**Branch Version**
Both.

**Character Information**
Velo was 1.38 in growth while testing.

**Additional Information**
-

**Comment by Peter22FIN** [comment]
Couldn't replicate in PIE
