### ISSUE TITLE
"ListAvailableMutations" Command Not Working

### ISSUE THREAD

**Issue by Xunaria** [BoBAdministration/QA-Bug-Reports#575]
**Describe the Bug**
When trying to use the  "ListAvailableMutations" command the command does not list the available mutations into the log/console when pressing F2 twice to expand the console.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 12
2. Selected a random creature to be in-game
3. Click "F2" or "`" to open the console
4. Type ListAvailableMutations in the command line and click enter
5. Click "F2" or "`" twice to fully expand the console
6. Observer the lack of a list under the ListAvailableMutations command

**Expected behavior**
When the ListAvailableMutations command is entered into the console and the console is expanded, a list of all the available mutations should be visible under the "ListAvailableMutations" command. 

**Actual behavior**
When you enter the ListAvailableMutations in the command console, it says the command has gone through but does not give the actual list all of the available mutations.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/114358163/234726397-6a8e629c-f3c9-43ad-bff9-f9e541fbe2eb.png)

**Branch Version**
Tester (1.2.0089)

**Character Information**
N/A

**Additional Information**
N/A

**Comment by Predatoria** [comment]
Vipe fixed it and I confirmed it
