### ISSUE TITLE
Megalo scent trail, not wiehen

### ISSUE THREAD

**Issue by Skyedrago** [BoBAdministration/QA-Bug-Reports#577]
**Describe the Bug**
Scent trail of megalo shows up as wiehen

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1.  Log into Dedicated Testing 12
2. Spawn as any dino
3. Sniff wiehen scent trail
4. It shows up as megalo

**Expected behavior**
Scent trails are wiehens

**Actual behavior**
Scent trails are megalos

**Screenshots & Video**
![20230428171906_1](https://user-images.githubusercontent.com/96404852/235257004-108144f8-a973-4083-9455-bb7259b667af.jpg)

**Branch Version**
Tester

**Character Information**
N/A

**Additional Information**
N/A

**Comment by Predatoria** [comment]
Should finally have fixed thsi!
