### ISSUE TITLE
+QoL (public): The egg HUD now flashes and remains red if you take damage to eggs you are gestating

### ISSUE THREAD

**Issue by Xunaria** [BoBAdministration/QA-Bug-Reports#578]
**Describe the Bug**
After the Egg HUD flashes and remains red from taking damage from gestating the eggs. When the user destroys the eggs or lays the eggs down **BEFORE** mating again. The next clutch of eggs will still have the red ring around the egg HUD even though they were not damaged. 

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 12
2. Spawn in on any creature that gives birth through laying eggs (not live birth)
3. Grow to .8+ (mating growth)
4. Mate with the same creature of the opposite gender
5. Take comfort damage until the "You are Stressed. It has damaged your eggs." prompt has popped up
6. Once that prompt has popped up the Egg HUD will flash red and remain red to indicate the damage
7. Either Delete or Lay the Eggs in a nest so that no gestating icon is visible
8. Wait to regain comfort in a safe range to not damage the eggs (40+ comfort to be safe)
9. Mate again so that a **NEW** batch of eggs are gestating
10. Observe the solid red outline on these new batch of eggs that have not taken damage

**Expected behavior**
Once a set of eggs have taken damage and they have been deleted or laid in a nest, a new batch of eggs should look normal without the red outline around it.

**Actual behavior**
When a set of eggs have taken damage and they have been deleted or laid in a nest, a new batch of eggs still has the solid red outline around the Egg HUD

**Screenshots & Video**
https://youtu.be/HRQuflrzd64

**Branch Version**
Tester, Version: 1.2.0090

**Character Information**
1.2 Growth Rex

**Additional Information**
N/A

**Comment by SilverWing430** [comment]
confirmed fix
