### ISSUE TITLE
Velo drops food when trying to cling to walls - QoL suggestion

### ISSUE THREAD

**Issue by Maddeonn** [BoBAdministration/QA-Bug-Reports#579]
**Describe the Bug**
Velo uses the same button, the use key, for wall climbing and dropping carried items. Holding the use key in midair before hitting the wall causes the velo to immediately latch and drop the food in the same motion.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Be smol chicken
2. Grab a leg of gore
3. Approach wall
4. Jump towards wall and hold use key BEFORE touching wall
5. Hit wall and despair as your food falls to the ground

**Expected behavior**
Velo wall climbs without dropping its carried item

**Actual behavior**
Velo drops its carried item when trying to wall climb by holding the use key

**Screenshots & Video**
https://youtu.be/6dG8Z2wftNA
https://www.youtube.com/watch?v=Q-14PVhVLPE

**Branch Version**
Live

**Character Information**
Any Velo

**Additional Information**
Live, QoL
Taken from Vipe's GitHub, issue 10582

**Comment by SilverWing430** [comment]
Not fixed, will upload video after session

**Comment by SilverWing430** [comment]
Rip, I was just doing what i was told to check XD

**Comment by Zi-Mom** [comment]
Also Issue number 10590 in Vipe's
