### ISSUE TITLE
Rain inside cave on RS

### ISSUE THREAD

**Issue by SilverWing430** [BoBAdministration/QA-Bug-Reports#580]
**Describe the Bug**
While inside a cave while its raining, there is rain inside the cave

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged on to RS server
2. go to Location: -55497.375 332106.062 12531.903
3. Have rain happen (either spawn a storm or wait)
4. Witness the miracle of rain inside a cave

**Expected behavior**
No rain visible

**Actual behavior**
there is rain visible

**Screenshots & Video**
https://youtu.be/Qwl7LXD2o98

**Branch Version**
Live

**Character Information**
Velo (1.2)

**Additional Information**
Rival Shores
Relates to Vipe's Github issue 10575

**Comment by Predatoria** [comment]
I can't get it to happen, and it's rather low priority anyways.  I'm just gonna close this.
