### ISSUE TITLE
Using specific settings can cause ocean water to be unusually clear.

### ISSUE THREAD

**Issue by paratea** [BoBAdministration/QA-Bug-Reports#59]
**Describe the Bug**
Having specific settings can cause the visual quality of the water to be clearer than intended, allowing swimming creatures to see extremely far.

**To Reproduce**
1. Log into any Test server
2. Spawn in on Krono
3. Open user interface settings
4. Set the following:
![image](https://user-images.githubusercontent.com/77513445/131273812-9a409728-3978-47d3-b138-e3407018de3d.png)
5. Apply, then Swim with clear visuals.

**Expected behavior**
Water should appear slightly murky

**Actual behavior**
Water allows a clear field of view

**Screenshots & Video**
Tested on a second PC:
![image](https://user-images.githubusercontent.com/77513445/131273836-906c4ad5-d59e-4a9a-9b8d-2dc6730cb6d5.png)
![image](https://user-images.githubusercontent.com/77513445/131273844-d36e6d78-0e86-4be5-a512-22b178198dde.png)
![image](https://user-images.githubusercontent.com/77513445/131273847-b2d9951a-81cf-4626-8ed5-8c2947224bef.png)

**Branch Version**
Live

**Character Information**
Works on any dinosaur while in water, character information non-specific and isn't reliant on talents.

**Additional Information**
Provides more clarity on RS than on AP due to the water in general.
However, unsure if this is intended or if something we need to worry about, or if unfixable at this time similar to 'low' on foliage.

**Comment by Predatoria** [comment]
I just tried these settings and was not able to reproduce this.  Normal settings:

![image](https://user-images.githubusercontent.com/25803890/132729143-d2ed46a7-dd8f-43f7-ad31-715f65d11aa0.png)


Copy of the above settings:

![image](https://user-images.githubusercontent.com/25803890/132729193-6e5fae83-fd0e-404f-ae22-63d111cfa6bb.png)
