### ISSUE TITLE
Bountiful Lands world event does not affect respawn rate of foliage eaten before the event started

### ISSUE THREAD

**Issue by Undercooked-Mothman** [BoBAdministration/QA-Bug-Reports#591]
**Describe the Bug**
If plants are eaten/knocked over before a bountiful lands event starts in the area, they respawn using their normal timers. Foliage destroyed after the event starts respawns at the increased rate.

**To Reproduce**
1. Spawn into any server as any dino that can destroy foliage
2. eat or otherwise destroy foliage in an area
3. start a bountiful lands world event in that area
4. wait (you can also eat any remaining foliage at this point to see that the event works for that foliage)

**Expected behavior**
Foliage eaten before the event starts is also affected by the event and respawns quickly

**Actual behavior**
Foliage eaten before the event starts is not affected and respawns much slower than foliage eaten during the event

**Screenshots & Video**
https://www.youtube.com/watch?v=hOt26-cbtWQ&ab_channel=UndercookedMoth

**Branch Version**
Live

**Character Information**
1.2 Para was used to eat/destroy the foliage

**Additional Information**
Most likely any map, tested on Titania and Ancestral Plains
Gameplay, Live branch

**Comment by Predatoria** [comment]
it's not really practical to fix this.  It'd be extremely expensive.
