### ISSUE TITLE
Elasmo bite range when using "grab bite" is not replicating accurately on client side.

### ISSUE THREAD

**Issue by paratea** [BoBAdministration/QA-Bug-Reports#6]
**Describe the Bug**
While holding the use key as an Elasmo and biting, the neck is extended. On the non-Elasmo client side, this is being replicated as a curl, causing confusion on the bite range.

**To Reproduce**
1. Spawn Elasmo, any map
2. SetGrowthLevel 1.2 for easy viewing
3. Double-click use key (and hold, while biting)
4. Elasmo's neck extends.
5. Repeat steps with another player viewing to see neck-curl issue.

**Expected behavior**
Elasmo bite is centered around the head.

**Actual behavior**
Elasmo curls neck causing damage to be perceived beyond the expected range.

**Screenshots & Video**
**GIF IMAGE:** https://discord.com/channels/605940021568208906/605979793716019205/876591514157977610
**VIDEO LINK:** https://youtu.be/qmzaUff69Ss
![image](https://user-images.githubusercontent.com/77513445/129494379-a1793e2f-5a69-4416-afb2-840c99694489.png)
![image](https://user-images.githubusercontent.com/77513445/129494380-84e0b044-15d1-4871-af1d-1c6e0a2e2429.png)
![image](https://user-images.githubusercontent.com/77513445/129494385-9f53553d-2566-4d79-97a6-551a95cb0974.png)

**Branch Version**
Tester and Live.

**Character Information**
Elasmo, any size.

**Additional Information**
N/A

**Comment by teatimejess** [comment]
May need to be addressed in addition as changes, adding video here for reference as it seems the head cannot be hit by other players as well during this. https://www.youtube.com/watch?v=13CLqZ7kuns

**Comment by Vallyhalla** [comment]
This seems to have fixed in previous patches, and couldn't replicate.
