### ISSUE TITLE
Force Respawn denies Hunt Points

### ISSUE THREAD

**Issue by The-Grand-Tickler** [BoBAdministration/QA-Bug-Reports#60]
When a player is losing a battle, they can opt to Force Respawn over letting the opposing party finish them to deny the opposing party any Hunt Points

**To Reproduce**
1. Have at least 2 people and log onto any test server as any 1.2 dino
2. Fight until one player is almost dead
3. The almost dead player presses esc and clicks "force respawn"
4. They will die and the other player will receive no hunt points

**Expected behavior**
If a group deals a lot of damage to a creature in a battle, and the creature is finished off to anything but another player (drowning, falling, stress, force respawning) the party that did the most damage to the creature before it died should still receive the hunt points

**Actual behavior**
Force respawning will not count as a hunt

**Screenshots & Video**
N/A (do not have another person to capture video at this time)

**Branch Version**
Live.

**Character Information**
Will work with any creature

**Additional Information**
will work on any map

**Comment by Predatoria** [comment]
fixed

**Comment by MarshmallowMaiden** [comment]
Will need to test on server without admin powers

**Comment by Vallyhalla** [comment]
When you deal damage to a creature and it force respawns it should drop hunt points. Marking this as fixed unless told otherwise!
