### ISSUE TITLE
Velo is sucked into the void after crashing; while clinging to a tree

### ISSUE THREAD

**Issue by D-Malik** [BoBAdministration/QA-Bug-Reports#604]
**Describe the Bug**
Velo is sucked into the void [deep ocean, under the map]. The Velo had been clinging to a tree. Occurs when the game crashes or is force closed.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log into dedi 12
2. Spawn in as a Velo
3. Grow to gauntlet age
4. Cling to a jungle tree [inedible ones]
5. Force close game to simulate a crash [Alt F4, Task Manager]

**Expected behavior**
Velo lands on the ground safely upon logging in.

**Actual behavior**
Velo is not where it logged; is forced into the unknown abyss and drowns, squealing sadly as it dies.

**Screenshots & Video**
If applicable, add screenshots to help explain your problem, or attach a video/gif. You can do this by just pasting in your image(s)!
https://youtu.be/Rr0VJHL7X3w

**Branch Version**
Live
Tester

**Character Information**
Adult Velo, 1.32
With or without talents.
Unsure if this also applies to younger Velos, as it was only tested using gauntlet age Velo

**Additional Information**
any map, any weather

**Labels**
Live Branch
Tester Branch
Gameplay

**Comment by Peter22FIN** [comment]
+Maybe Fixed in next tester patch

**Comment by D-Malik** [comment]
Fixed with Patch 1.2.0096
