### ISSUE TITLE
The mutation gallery does not close on "close" button

### ISSUE THREAD

**Issue by xMeelo** [BoBAdministration/QA-Bug-Reports#606]
**Describe the Bug**
What it says on the tin! The mutation gallery "close" button does not close the mutation gallery.

**To Reproduce**
1. Log onto Tester version server
2. Spawn on any dino
3. Open the character menu
4. Open the Achievements menu
5. Open the mutation gallery
6. Hit the close button :(

**Expected behavior**
Close button should close the menu

**Actual behavior**
Close button does not close the menu. Options disappear. Red square button DOES close the mutation menu!

**Screenshots & Video**
https://youtu.be/tgKbD7uTCeg

**Branch Version**
Tester

**Character Information**
NA

**Additional Information**

Tester Branch, QoL, Text?

**Comment by Thy-Vipe** [comment]
This is expected behavior at the time. 
The close button belongs to the UI behind the gallery, it will not be visible once we have those UIs ready. Red button closes the gallery as expected.
