### ISSUE TITLE
Nest icon in compass shows as world event icon

### ISSUE THREAD

**Issue by xMeelo** [BoBAdministration/QA-Bug-Reports#607]
**Describe the Bug**
The nest icon in the new compass on the tester branch shows up as the same icon as the world event icon.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log onto tester server
2. Spawn onto any male dino
3. Find world event
4. Lay down a nest
5. Sniff to bring up the compass
6. Observe the icons being the same :(

**Expected behavior**
Nest icon for nest, world event icon for world event

**Actual behavior**
World event icon shows up both for your own nest & the world event

**Screenshots & Video**
![image](https://github.com/BoBAdministration/QA-Bug-Reports/assets/133044727/42dc66aa-da34-46bb-a445-62800ed06416)

**Branch Version**
Tester

**Character Information**
Any growth and specie

**Additional Information**
Tester Branch, Art Bug, QoL?

**Comment by Predatoria** [comment]
Easy fix, I just made a small error
