### ISSUE TITLE
Arboreal Nests No longer have collision

### ISSUE THREAD

**Issue by The-Grand-Tickler** [BoBAdministration/QA-Bug-Reports#61]
Arboreal Nests have no collision

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log onto Dedicated Testing 2
2. Spawn as a Male Velo 
3. Grow yourself to at least .8 and get 3/3 arboreal
4. Walk forward and fall out of the tree

**Expected behavior**
Arboreal nests have collision and regular nests do not. 

**Actual behavior**
No nests have collision

**Screenshots & Video**
![20210831190500_1](https://user-images.githubusercontent.com/88917110/131591460-e16ef5bc-106c-4627-89b5-94f92f7ebd67.jpg)
https://www.youtube.com/watch?v=Cmb-v8r4-MA

Branch
Tester

**Character Information**
Male velo with 3/3 arboreal, or male ptera/trope, Grown to at least .8

**Comment by Predatoria** [comment]
fixed

**Comment by teatimejess** [comment]
Confirmed fixed, normal nests do not have collision whereas arboreal nests do.
