### ISSUE TITLE
Compass does not show any icons but player smells

### ISSUE THREAD

**Issue by xMeelo** [BoBAdministration/QA-Bug-Reports#618]
**Describe the Bug**
Compass icons for water, nests, gore, fat plants and world event are not showing up on the compass when sniffing.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log onto testing server
2. Spawn on any dino
3. Sniff and observe lack of icons

**Expected behavior**
Icons for water, nests, gore, fat plants and world event should be showing up on the compass

**Actual behavior**
Icons for water, nests, gore, fat plants and world event do not show up on the compass

**Screenshots & Video**
https://youtu.be/ZuT6VZYu8Rk
![image](https://github.com/BoBAdministration/QA-Bug-Reports/assets/133044727/391b07a7-85f6-479c-8b10-1f61a55d6da9)

**Branch Version**
Tester

**Character Information**
Tested on carni, herbi and aquatic - behaves the same

**Additional Information**
Tester Branch, Gameplay

**Comment by xMeelo** [comment]
Seems to be fixed in the latest patch :) I can now smell gores, fat plants, world events and water as intended

**Comment by Predatoria** [comment]
It was an oversight, I fixed it!
