### ISSUE TITLE
Compass is not pointing the icons in the right direction

### ISSUE THREAD

**Issue by xMeelo** [BoBAdministration/QA-Bug-Reports#619]
**Describe the Bug**
The compass icons are not pointing in the correct direction. 

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log onto testing server
2. Spawn on any dino
3. Sniff to see compass
4. Observe icons not pointing in the right direction

**Expected behavior**
Icons should direct you to where the items or dinosaurs are.

**Actual behavior**
Icons direct you to the wrong side, nearly the opposite.

**Screenshots & Video**
(https://www.youtube.com/watch?v=ZuT6VZYu8Rk)
![image](https://github.com/BoBAdministration/QA-Bug-Reports/assets/133044727/78e50238-748e-4ce6-ab0e-217daab84923)

**Branch Version**
Tester

**Character Information**
Any dinos, tested on Carni, herbi and aquatic

**Additional Information**
Tester Branch, Gameplay

**Comment by xMeelo** [comment]
Compass seem to be pointing towards the right things now!

**Comment by Undercooked-Mothman** [comment]
^ this has been fixed and can be closed
