### ISSUE TITLE
Name reads as channel text color in-game.

### ISSUE THREAD

**Issue by tinystarpaws** [BoBAdministration/QA-Bug-Reports#62]
**Describe the Bug**
Whenever the ">" symbol is used in a Steam name, it breaks the chat box and the rest of their name becomes colors like the rest of the regular channel text. See included screenshot.

**To Reproduce**
1. Open up your Steam profile
2. Edit your Steam name to include a ">" symbol anywhere in it, though for best results, put it near the beginning.
3. Launch BoB
4. Join any server
5. Spawn as any creature
6. Speak in Local chat. Your name color will match your channel text color.
7. Invite someone to group.
8. Speaking in group chat. Your name will match the group chat text color.

**Expected behavior**
Inputting this symbol in your name should have no effect on your name's color.

**Actual behavior**
Using ">" within your name will break your name color.

**Screenshots & Video**
https://user-images.githubusercontent.com/38923098/133914995-9e6eb281-f591-46da-a3c2-2316071ec7bc.mp4

**Branch Version**
Live and tester.

**Character Information**
Any creature will function the same for this.

**Additional Information**
N/A

**Comment by Vallyhalla** [comment]
Unable to replicate this with the new font changes for the game. Closing this now.
