### ISSUE TITLE
Nest Icons replace Player Scent Icons on the compass at random.

### ISSUE THREAD

**Issue by PREACHER-8888** [BoBAdministration/QA-Bug-Reports#620]
**Describe the Bug**
At random times when sniffing, your scent icon or your buddy's icon (if you have any with you) may be replaced with the nest scent icon. It can either just be one of you or both of you.

**To Reproduce**
1. Log onto Dedi12
2. Spawn in a male terrestrial dinosaur
3. Grab a friend 
4. Place a nest
5. Sniff to bring up the compass and observe any changes
6. Repeat step 5 until your icon, your buddy's icon, or both of your icons are replaced by the nest scent icon.

This can also be done solo if you exclude step 3.

**Expected behavior**
When sniffing and using the compass, player scent icons should not be replaced by the nest scent icon.

**Actual behavior**
When sniffing and using the compass, player scent icons can be randomly replaced by the nest scent icon.

**Screenshots & Video**

**SCENARIO A**: One player present, no nest present. 
![image](https://github.com/BoBAdministration/QA-Bug-Reports/assets/134006746/f562ebf5-1aea-4ec5-aae3-1132576e767f)

**SCENARIO B**: One player present, nest present. 
![image](https://github.com/BoBAdministration/QA-Bug-Reports/assets/134006746/89f4c5e8-d8ac-48bc-95b0-d3ec1083fe84)
![image](https://github.com/BoBAdministration/QA-Bug-Reports/assets/134006746/575d5ac3-9f7a-48d1-b305-6d907ea2db7e)

**SCENARIO C**: Two players and one nest present.
![image](https://github.com/BoBAdministration/QA-Bug-Reports/assets/134006746/99b2d3b3-6843-42d0-b17d-a4d9a0868259)
![image](https://github.com/BoBAdministration/QA-Bug-Reports/assets/134006746/b5492ce5-a16f-452c-8214-48e2557fc75c)

**EXTRA**: Two players present, no nest present.
![image](https://github.com/BoBAdministration/QA-Bug-Reports/assets/134006746/75cefe44-4b9c-419d-b968-4e73fc6c73e9)

**Branch Version**
Tester

**Character Information**
Your dinosaur must be able to place a nest ( Adult Male, terrestrial or arial.) 

**Additional Information**

This was tested by Meelo and I at different variables.
**SCENARIO A**: Lone player, no nest. Your own scent icon may be replaced with a nest icon at random.
**SCENARIO B**: Lone player, one nest. Your own scent icon may be replaced with a nest icon at random.
**SCENARIO C**: Two players and one nest. Icons often replaced with nest icon. Can happen to one or to both players.

**Comment by xMeelo** [comment]
Can also be seen here at around 8 seconds https://www.youtube.com/watch?v=ZuT6VZYu8Rk

**Comment by Predatoria** [comment]
I found the issue in the code.  This should be fixed.
