### ISSUE TITLE
Compass In The Middle Of The Screen

### ISSUE THREAD

**Issue by BackwaterOtter** [BoBAdministration/QA-Bug-Reports#623]
**Describe the Bug**
The compass is offset, and sits in the middle of the screen.

**To Reproduce**
1. Logged into Dedicated Testing 12
2. Spawn in any creature.
3. Press the sniff key.
4. Compass was in the middle of the screen.

**Expected behavior**
The compass is at the top of the screen, partially obscured.

**Actual behavior**
The entire circle of the compass is in the middle of the screen.

**Screenshots & Video**
![image](https://github.com/BoBAdministration/QA-Bug-Reports/assets/24828337/693e1f89-b185-4597-ae32-4f5f64353a6c)

**Branch Version**
Tester.

**Character Information**
1.2 Trope

**Comment by Predatoria** [comment]
Dumb mistake, it's fixed
