### ISSUE TITLE
Health HuD Icon Remains Red After Taking Damage

### ISSUE THREAD

**Issue by C-rimsonKnight** [BoBAdministration/QA-Bug-Reports#624]
**Describe the Bug**
When on a creature, taking damage causes the health HuD icon to flash and remain red.

**To Reproduce**
1. Log into a server
2. Spawn into any creature
3. Take damage (can be fall damage or hit by another creature)

**Expected behavior**
Health HuD icon outline should flash red, then return to normal.

**Actual behavior**
The health HuD icon outline will flash red, but remain red instead of returning to its normal color.

**Screenshots & Video**
https://www.youtube.com/watch?v=0H0xmL69vV8
![image](https://github.com/BoBAdministration/QA-Bug-Reports/assets/125211632/ed486987-3018-471d-8819-e844393f0edb)

**Branch Version**
Tester Branch

**Character Information**
Dinosaur used for video and screenshot was a 1.28 Ptera, but this can be reproduced on any creature.

**Additional Information**
N/A

**Comment by CeciliaSE** [comment]
Tested on a 1.32 Ptera with sturdy and followed the steps described in this bug report exactly.

Log into a server
Spawn into any creature
Take damage (can be fall damage or hit by another creature)

It is currently not possible to recreate post-fix with the steps provided
