### ISSUE TITLE
Can scent mutations when sniffing eggs

### ISSUE THREAD

**Issue by SiraPanda** [BoBAdministration/QA-Bug-Reports#625]
**Describe the Bug**
When you smell the egg you can smell what mutation the dino will come out as. That is also when no one is inside the egg.

**To Reproduce**
1. Logged into Dedicated Testing 12
2. Spawned in and nested as Megaraptor
3. Laid egg
4. Sniffed egg
5. Egg gave me an achievement for that mutation the egg had.

**Expected behavior**
The egg should not tell you what mutation it will get.

**Actual behavior**
An egg that has a mutation will give you the achievement for that mutation when you scent it.

**Screenshots & Video**
https://youtu.be/Rz6I3k2fvxQ

**Branch Version**
Tester Branch, Gameplay, Skin Mutation

**Character Information**
Panda was a 2.0 Megaraptor and Zi was 1.9 Megaraptor. Panda was brown and Zi was green.

**Additional Information**
N/A

**Comment by WayaShinzui** [comment]
Seems to be good! Dropped a ton of eggs, none had any indicator on sniff of mutations but several did have mutations. I got a glowy banana velo.
