### ISSUE TITLE
Entering Character Select causes you to lose all Talent Points and Inherits

### ISSUE THREAD

**Issue by Zi-Mom** [BoBAdministration/QA-Bug-Reports#627]
**Describe the Bug**
When you go to character select screen and log back into your dino around other big players you will find all your talent points missing and all inherits missing. 
**To Reproduce**

1. Logged into Dedi 12
2. Spawn as a creature (Tested this on Megar, Icthy, Acro were used) 
3. Have inherits and spend talent points (Grow to 1.2 for best idea of results)
4. Have friends be nearby ( The amount of closeness needed is in the 1st screenshot, the 2nd screenshot shows three megar steps back and when it stopped happening)
6. Go to character select screen
7. Log back in to the same dino
8. Observe and lament the loss of talent points and inherits

**Expected behavior**
For talents and inherits to stay the same on a dino when logging out and in

**Actual behavior**
Entering Character Select screen and then logging back into your dino causes your inherits and talents to go missing. You can revert this by setting your growth low (Before inherits) and then growing back up. Your inherits and the talent points you had spent will come back. Also asked Soal's to undirty the dino to test and see if that had an effect but the same results after logging out and in. Relogging doesn't fix the issue.

**Screenshots & Video**
How Close you need to be to trigger it (At least with Velo and Megar)
![image](https://github.com/BoBAdministration/QA-Bug-Reports/assets/88993347/947c26e1-348e-46a2-b205-deae0f072587)

The 3 Megar steps away that allowed it to work properly
![image](https://github.com/BoBAdministration/QA-Bug-Reports/assets/88993347/a2811292-4750-4801-8abd-92e765f6b689)

Youtube video of it happening
https://youtu.be/NiT5BkUEs7I

**Branch Version**
Tester 

**Character Information**
Any dino 1.2+

**Additional Information**
Gameplay

**Comment by Predatoria** [comment]
woo we finally think we found this.  It was a tough one
