### ISSUE TITLE
Carnivores can grab empty carcasses and eat them.

### ISSUE THREAD

**Issue by Akaraasaur** [BoBAdministration/QA-Bug-Reports#629]
**Describe the Bug**
When carcasses have white bones, carnivores can grab them and move them. They can also eat them but it don't give any food. FPS decreases when empty carcasses are carried.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log on a carnivorous dinosaur
2. Find a white bones empty carcass
3. Double tap your using button like if you want to grab them
4. You can move them and eat them after releasing on the floor.

**Expected behavior**
You should not be able to grab empty carcasses and eat them.

**Actual behavior**
You can grab empty carcasses and eat them.

**Screenshots & Video**
https://youtu.be/Dtw7V2GknWc

**Branch Version**
Live and tester

**Character Information**
Carnivore / piscivore dinosaurs

**Additional Information**
Tested on the tester branch too.

**Comment by Predatoria** [comment]
This is intended.  They're considered bones and act as foliage you can pick up when in this state.
