### ISSUE TITLE
A Rival Shores cave entrance causes frequent Apato stuck cases.

### ISSUE THREAD

**Issue by tinystarpaws** [BoBAdministration/QA-Bug-Reports#63]
**Describe the Bug**
Certain map spot causes a lot of Apatos to get stuck. Attempted on Saichania and Lurdu, neither of them could cause the same issue to repeat. Coordinates are 214432 38708 23489 on Rival Shores.

**To Reproduce**
1. Spawn in as an Apato
2. Grow to .5
3. TeleportAt 214432 38708 23489
4. Witness as you are stuck to the wall!

**Expected behavior**
Apato should not suddenly climb a cave wall

**Actual behavior**
Spider-Apato commits wall climb hijinks

**Screenshots & Video**
https://user-images.githubusercontent.com/38923098/133915511-61c54738-bb19-40ec-964e-75cf3e2c08d6.mp4

**Branch Version**
Tester and Live branches.

**Character Information**
Apato only, .5+ growth. Attempted on a .45 and could not get it to break, although the wall will still stop your movement. You're still able to walk out normally though.

**Additional Information**
Issue is on the Rival Shores map.

**Comment by Predatoria** [comment]
Odd issue.  May have fixed it
