### ISSUE TITLE
Some ory burrow corners are see-through

### ISSUE THREAD

**Issue by Undercooked-Mothman** [BoBAdministration/QA-Bug-Reports#634]
**Describe the Bug**
Some particular arrangements of ory burrow squares cause odd holes or edges where the mesh doesn't quite seem to meet. these don't seem to affect actual collision, however i did not thoroughly test the collision so take that with a grain of salt.

**To Reproduce**
1. log into any server
2. spawn in as ory
3. create a burrow
4. dig out flat area, and then dig into the floor to create a L shaped pit

**Expected behavior**
Ory burrow sections mesh together neatly and no spikes/holes appear

**Actual behavior**
some corners often have holes you can see through

**Screenshots & Video**
![image](https://github.com/BoBAdministration/QA-Bug-Reports/assets/133143622/2a6cf253-8258-4391-a68b-5d5613e7d2fc)
https://www.youtube.com/watch?v=aYNQEtoL1hQ&ab_channel=UndercookedMoth

**Branch Version**
Live

**Character Information**
Ory

**Additional Information**
Tested on titania and RS
art bug

**Comment by Predatoria** [comment]
This won't be fixed.  it's a caveat of how we implemented the burrow system
