### ISSUE TITLE
Wonky Acro Claws

### ISSUE THREAD

**Issue by Falcarius9** [BoBAdministration/QA-Bug-Reports#648]
**Describe the Bug**
New Acro has wonky claw textures

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Spawn in as new Acro
2. Check the claws on any skin

**Expected behavior**
Look like normal claws

**Actual behavior**
Warped textures on the claws

**Screenshots & Video**
![image](https://github.com/BoBAdministration/QA-Bug-Reports/assets/57926053/4be1db83-2a7a-4835-ae14-fd4bc011464d)
![image](https://github.com/BoBAdministration/QA-Bug-Reports/assets/57926053/5db4c55f-6624-4641-97a1-da57f7e79124)
![image](https://github.com/BoBAdministration/QA-Bug-Reports/assets/57926053/18536f8f-932e-4a73-8c98-320a00108b9e)

**Branch Version**
Tester

**Character Information**
Just needs to be new Acro

**Additional Information**
Map type, weather, or any other context about the problem here.

**Comment by Predatoria** [comment]
Lifeon fixed this and it should be fixed in the next cook
