### ISSUE TITLE
Air pocket in RS snowy mountain cave.

### ISSUE THREAD

**Issue by tinystarpaws** [BoBAdministration/QA-Bug-Reports#65]
**Describe the Bug**
Shoving your head into the mesh grants a spot for aquatics to breathe where they should not. Location is -216172 -17117 18033 on Rival Shores.

**To Reproduce**
1. Spawn in as a Mosa
2. Grow to 1.0
3. TeleportAt -216172 -17117 18033
4. Make sure face is through the cave mesh, then press E to breathe.

**Expected behavior**
There should not be any air pocket here to breathe from

**Actual behavior**
Big air for big lungs exists

**Screenshots & Video**
https://user-images.githubusercontent.com/38923098/133915843-c3aa4354-8cde-4c1e-8ec0-a43c7bc07970.mp4

**Branch Version**
Tester and Live.

**Character Information**
Used a 2.0 and 1.0 Mosa to test.

**Additional Information**
Rival Shores only.

**Comment by Predatoria** [comment]
I think this is actually a glitch with overlapping water rather than a map bug.

**Comment by Predatoria** [comment]
ill have to figure out what's going on

**Comment by Dinorunp** [comment]
still not fixed as of 2023
