### ISSUE TITLE
Erased spawn inhibitors dont actually stop inhibiting spawn points

### ISSUE THREAD

**Issue by Undercooked-Mothman** [BoBAdministration/QA-Bug-Reports#656]
**Describe the Bug**
What it says on the tin. Erasing with the erase tool, delete button, or delete all button does not stop destroyed inhibitors from keeping you from spawning at those locations until a server restart has occured.

**To Reproduce**
1. get someone to restart one of the dedicated testing servers on tester branch
2. log in on aforementioned freshly restarted server
3. check that you spawn in normally
4. place inhibitors over a bunch of spawn points, then delete them all using any method
5. spawn in again

**Expected behavior**
The deleted spawn inhibitors do not continue to inhibit the spawning

**Actual behavior**
The spawn points do not reactivate until server restart

**Screenshots & Video**
https://youtu.be/tFZpv4R3e-c

**Branch Version**
Tester

**Character Information**
 works with every kind of spawn point.

**Additional Information**
tested on RS

**Comment by Predatoria** [comment]
Found the issue.  The spawn point inhibitor was using its old default radius of 25 meters when erased rather than considering scale.
