### ISSUE TITLE
Herbivores unable to knockdown plants when moving 

### ISSUE THREAD

**Issue by TheKingMinos** [BoBAdministration/QA-Bug-Reports#659]
**Describe the Bug**
When eating you cannot knock down plants and get stuck

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. select or pick a herbivore 
2. grow to 1.2
3. start to eat and walk at the same time 
4. plants that would be able to get knock over will not move and you will become stuck on them

**Expected behavior**
to knock over those plants and keep eating.

**Actual behavior**
You will get stuck on those plants and not be able to move.

**Screenshots & Video**
https://youtu.be/JI4cBpwFD6k

**Branch Version**
Tester

**Character Information**
Para, 3.0 growth

**Additional Information**
Titania

**Comment by Predatoria** [comment]
This is deliberate and is not a bug so players don't destroy foliage they are trying to eat.
