### ISSUE TITLE
Cannot join dedicated 1 unless admin

### ISSUE THREAD

**Issue by Alyrius** [BoBAdministration/QA-Bug-Reports#66]
**Describe the Bug**
Users that do not have Admin on dedicated testing 1, or are global admin, cannot join the server. They get the loading screen, the blank message box and get kicked to main menu

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Launch tester branch
2. try to join Dedicated testing 1
3. fail to join, get kicked on ocean screen
4. repeat

**Expected behavior**
being able to join the server even though I am not admin

**Actual behavior**
Unable to join the server, you only get the blank error box

**Screenshots & Video**
https://cdn.discordapp.com/attachments/659781268589903898/889859887394332682/unknown.png

**Branch Version**
Tester .1349

**Character Information**
cannot apply

**Additional Information**
It really seems to only happen to non admins/globaladmins, this is the only server set up to not admin console

**Comment by Alyrius** [comment]
Currently still not fixed, unsure if it should be fixed in this version of tester already?

**Comment by Thy-Vipe** [comment]
> Currently still not fixed, unsure if it should be fixed in this version of tester already?

It should be fixed on version 1351! So next patch.

**Comment by cleafspear** [comment]
testing information:
1 and 3 will have console removed to test this bug

**Comment by Chipboard** [comment]
Fixed - Confirmed on Tester branch
