### ISSUE TITLE
Blacks on Coah appear mid-ranged 'velvet' gray.

### ISSUE THREAD

**Issue by teatimejess** [BoBAdministration/QA-Bug-Reports#67]
**Describe the Bug**
Blacks on Coah appear mid-ranged gray, with a velvety sheen.

**To Reproduce**
1. Log onto any test server
2. Spawn Coah
3. Set all skin regions to full black, full opacity

**Expected behavior**
Coah appears (not fully black) but a dark naturalistic gray-black.

**Actual behavior**
Coah appears a strange mid gray with a non-natural sheen.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/77513445/134229638-7083ddd6-a79a-4626-abfe-26d2829b1d12.png)
![image](https://user-images.githubusercontent.com/77513445/134229644-24644e8a-799f-4b89-ba2f-f0a2bda547c1.png)

**Branch Version**
Tester

**Character Information**
Coah, any growth/gender.

**Additional Information**
N/A

**Comment by Soals** [comment]
Hey jess, this is normal, its actually not the coah but seems to be that the world itself is suffering from being washed out via graphic settings and gamma.
