### ISSUE TITLE
Floating plants in the air near "meadow pond" - Jungle Highlands

### ISSUE THREAD

**Issue by MaydayFarcrash** [BoBAdministration/QA-Bug-Reports#673]
**Describe the Bug**

**To Reproduce**
1. Play any dinosaur on Official 2 East US server.
2. Go to Jungle Highlands near the Meadow Pond. [X=308542.500000,Y=529024.062500,Z=-11730.969727]
3. Look up into the air in bewilderment. Is that a bird? Is that a plane? Is it superman? No just some plants.
4. Observe plants, they are floating.

**Expected behavior**
Plants on the floor.

**Actual behavior**
Plants in the air.

**Screenshots & Video**
![image](https://github.com/BoBAdministration/QA-Bug-Reports/assets/137945088/0e4a71fa-3dca-471e-9a2b-195c9d3013a6)
[Unlisted youtube video of reproduction steps](https://youtu.be/oJ2vmbvSyn0)

**Branch Version**
Live - this is on Official 2 East US server

**Character Information**
I believe this is irrelevant (should be visible on any dino) but just in case:
Para Male between .5 and .6 (juvi). Spec'd mostly into survival and combat.

**Additional Information**
Life cycle map on Titania, night time, weather unremarkable
Suggested tags:
Live
Map 
QoL

**Comment by Undercooked-Mothman** [comment]
can you check if this is on other servers using titania? this could have been caused by a tornado, which has been reported in issue #646

**Comment by MaydayFarcrash** [comment]
> can you check if this is on other servers using titania? this could have been caused by a tornado, which has been reported in issue #646

![image](https://github.com/BoBAdministration/QA-Bug-Reports/assets/137945088/85603034-4a02-4a9b-a13f-17e28b8ac6b9)
![image](https://github.com/BoBAdministration/QA-Bug-Reports/assets/137945088/91f43ce3-0ae1-4e1b-9a3f-3d136479cc7e)

Issue not present on Official East 1 - I think you are right
