### ISSUE TITLE
Grabbed pt is not rotated correctly

### ISSUE THREAD

**Issue by Undercooked-Mothman** [BoBAdministration/QA-Bug-Reports#678]
**Describe the Bug**
When grabbed, pt is rotated oddly so it clips through the mouth of the grabbing dino.

**To Reproduce**
1. log into any server
2. spawn in as a pt, have a friend spawn in as any dino
3. Have the friend pick you up

**Expected behavior**
When grabbed, pt is orientated so it is being held up by the neck

**Actual behavior**
When grabbed, pt is rotated so its body clips through the grabbing dino's mouth

**Screenshots & Video**
![image](https://github.com/BoBAdministration/QA-Bug-Reports/assets/133143622/ce714876-cb8b-4c37-b662-e760e634f547)
![image](https://github.com/BoBAdministration/QA-Bug-Reports/assets/133143622/285fee58-af00-461b-b733-7d8437272b1c)

**Branch Version**
Live

**Character Information**
Tested with a 1.24 megaraptor and 0.25 pt

**Additional Information**
art bug

**Comment by Predatoria** [comment]
This is correct.  It's supposed to be grabbed by the neck.
