### ISSUE TITLE
Coah's animation problem after press Alt key and click left mouse to attack

### ISSUE THREAD

**Issue by Sa0327** [BoBAdministration/QA-Bug-Reports#68]
**Describe the Bug**
Coah's attacking animation doesn't work properly after press Alt key and click left mouse button to attack

**To Reproduce**
1. Log into Dedicated Testing 9 server
2. Spawn in a Coah 
3. Set growth to 1.2
4. Press Alt key and click left mouse button to attack
5. Your attacking animation doesn't work properly

**Expected behavior**
I expected the Coah's attacking animation to continue properly

**Actual behavior**
Coah's attacking animation doesn't work properly after press Alt key and click left mouse button to attack

**Screenshots & Video**
https://youtu.be/Z2oFHCvmdAk

**Branch Version**
Tester branch

**Character Information**
1.2 growth Coahuilaceratops

**Additional Information**
Test Performance

**Comment by Predatoria** [comment]
Fixed it next patch

**Comment by 0fivu0** [comment]
Confirmed fixed on tester.
