### ISSUE TITLE
Item weight on pickup and drop different in UI

### ISSUE THREAD

**Issue by Zi-Mom** [BoBAdministration/QA-Bug-Reports#7]
**Describe the Bug**
Have tested with Meg, Coah, Pachy. When you pick up a fern/gore/flower/tree the Received weight is not reflected in the the healed weight on the UI notice. Received is smaller than the healed (Pick up lighter than drop)

**To Reproduce**
1. Logged onto O2(RS map)/WWD(AP map)/Dedicated 10
2. Spawned as a Pachy(O2)/Meg(WWD)/Coah(Dedicated 10) 
3. Tested by Picking up ferns and flowers as Pachy, Meg and coah
4. Tested by Picking up gore as a meg
5. All items had a higher weight shown when dropped than the weight shown from pick up

**Expected behavior**
I expected to see the weight numbers equal as the item I picked up should have gotten heavier on dropping it.

**Actual behavior**
Picked up items either are magically gaining weight while being held, or the UI is misreading the weight information so that it does not show it appropriately.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/88993347/129638129-45539d6f-432b-4ffd-ade1-648b18da083c.png)

**Branch Version**
Tester and Live

**Character Information**
Pachy F 1.0 - 2/3 speed, 2/3 combat (no inherit in stoic), 
Meg F 1.3 - 2/3 down some speed, 2/3 combat(+2 Inherit in Stoic)
Coah F 1.2 - No Talent

**Additional Information**
None at this time

**Comment by Predatoria** [comment]
This isn't a bug.  It's coded this way deliberately.
