### ISSUE TITLE
Pachy Empty food Hud icon

### ISSUE THREAD

**Issue by OverlordGrima** [BoBAdministration/QA-Bug-Reports#71]
**Describe the Bug**
Hatching as pachy gave an empty food hud icon despite having 70 food

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. became pachy egg
2. hacthed once i was able too
3. food hud is completely empty
4. stats say superb diet and 70% food
5. eating any food did not fill hud bar at all
**Expected behavior**
70% full food icon and would fill when eating food

**Actual behavior**
hatching as pachy does not fill up the food bars on the hud and it remains empty even after eating

**Screenshots & Video**
https://media.discordapp.net/attachments/879546586697437264/892508245686620222/unknown.png?width=908&height=511
https://media.discordapp.net/attachments/879546586697437264/892508283091443753/unknown.png?width=908&height=511

**Branch Version**
Tester 

**Character Information**
freshly hatched pachy from 2 fresh spawn pachies

**Additional Information**
n/a

**Comment by Vallyhalla** [comment]
This has been fixed!
