### ISSUE TITLE
Entering Mesh

### ISSUE THREAD

**Issue by kheprisun1** [BoBAdministration/QA-Bug-Reports#74]
**Describe the Bug**
A velo can fit through a crack in the mesh with their climbing ability and get under the Rival Shores map map.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 2
2. Spawned in a Velo in Desert
3. Set growth to 1.2
4. Head to coordinates listed in attachment (in a cave)
5. Attach to the rock below seam
6. Climb into seam

**Expected behavior**
Should not be able to traverse into the map mesh

**Actual behavior**
Enters the mesh when climbing (**does not work with jumping**)

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/89458161/135351116-a96047ef-fa31-43f5-a773-44f8af698901.png)

**Branch Version**
Live and Tester

**Character Information**
1.2 Velo

**Additional Information**
Map: **Rival Shores**

**Comment by Dinorunp** [comment]
still not fixed
