### ISSUE TITLE
Mesh eating/grabbing food through the ground

### ISSUE THREAD

**Issue by Lazulie14** [BoBAdministration/QA-Bug-Reports#75]
**Describe the Bug**
if something is under or above the ground a dino can eat through the mesh 

**To Reproduce**

1. Spawn a large gore
2. spawn as a ory
3. Dig a Ory hole near the surface 
4. then spawn as a velo
5. set growth to 1.2 and above
6. Place meat in hole or above a tunnel
5. you will notice that you are able to eat the gore through through the mesh

**Expected behavior**
Not being able to interact with gore through the mesh

**Actual behavior**
Instead you are able to eat through the mesh

**Screenshots & Video**
Video 1: https://www.youtube.com/watch?v=1Gj-cFtyyUM
Video 2: https://www.youtube.com/watch?v=dmO__jbMlPY

**Branch Version**
Live 

**Character Information**
Dinosaur growth and type. Include any other relevant character information such as talents, inherits, gender, and stats if necessary.

The velo's were above 1.2 and the acro above 1.1

**Additional Information**
the closer the Ory holes are to the gore the easier to eat through the mesh

**Comment by Vallyhalla** [comment]
Tried to replicate and it seems to be fixed!
