### ISSUE TITLE
Tropeo can take off during a grounded wing-beat.

### ISSUE THREAD

**Issue by paratea** [BoBAdministration/QA-Bug-Reports#76]
**Describe the Bug**
Tropeo can activate wing-beat then take-off while the animation is playing.
(Side note: tropeo can also activate wing-beat mid-landing.)

**To Reproduce**
1. Spawn in as Tropeo on any map.
2. Wing-beat.
3. Quickly take off before the wingbeat finished, these should be done near-immediately.
4. Tropeo takes-off while still in wingbeat animation. This is exacerbated by quick-takeoff.

**Expected behavior**
Tropeo finishes wingbeat animation, then takes off. 

**Actual behavior**
Tropeo can take off during wing-beat.

**Screenshots & Video**
https://www.youtube.com/watch?v=EpO4NHjKwJ4

**Branch Version**
Live & Tester

**Character Information**
Tropeo, any size.

**Additional Information**
N/A

**Comment by teatimejess** [comment]
Fixed pending testing

**Comment by Zelryn** [comment]
Confirmed Fixed on Tester branch.
