### ISSUE TITLE
Untextured rocks surrounding Shrines on Forest Island.

### ISSUE THREAD

**Issue by paratea** [BoBAdministration/QA-Bug-Reports#78]
**Describe the Bug**
Rocks surrounding shrines on Forest Island have no texture.

**To Reproduce**
1. Log onto any server with Forest Island
2. Enter Spectate
3. Go to shrine
4. Observe rocks.

**Expected behavior**
Rocks have rocky texture.

**Actual behavior**
Rocks have no texture.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/77513445/135940211-ed85e97c-520e-47e7-85f3-80a453fcb108.png)

**Branch Version**
Tester and Live.

**Character Information**
Any pawn.

**Additional Information**
Forest Island only.

**Comment by Predatoria** [comment]
Deleted rocks.  There were only 20 on the map and they were set correctly.  Not sure why this was happening
