### ISSUE TITLE
When Lurdu eats large seaweed, server experiences tiny bursts of lag/lag spikes.

### ISSUE THREAD

**Issue by kheprisun1** [BoBAdministration/QA-Bug-Reports#79]
**Describe the Bug**
When Lurdu eats, the entire server experiences tiny bursts of lag/lag spikes.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 2
2. Have 2 players
3. One player picks Lurdu, other player picks any other dino
4. Lurdu eats long seaweed

**Expected behavior**
Server will continue to act as normal, no lag spikes.

**Actual behavior**
Entire server experiences lag spikes,

**Screenshots & Video**
--

**Branch Version**
Tester and Live

**Character Information**
Lurdu, any size

**Additional Information**
Map: Ancestral Plains

**Comment by Vallyhalla** [comment]
This has been fixed.
