### ISSUE TITLE
Full-body bio mutation on Gecko Megalosaurus.

### ISSUE THREAD

**Issue by tinystarpaws** [BoBAdministration/QA-Bug-Reports#8]
**Describe the Bug**
The "Stripes" Markings layer on the Gecko Megalosaurus skin is able to mutate, and covers the whole body.

**To Reproduce**
1. Spawn in a Megalo with a randomized Gecko skin
2. MakeBrood with yourself until the undesired result pops up

**Expected behavior**
This layer should not be able to mutate.

**Actual behavior**
This layer does have a chance to mutate.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/38923098/129819110-bab90713-5898-46ee-a6f0-91835ff29cd0.png)
![image](https://user-images.githubusercontent.com/38923098/129819131-45ce8577-497f-45a0-ae17-fea653cafe1d.png)

**Branch Version**
Occurred on Live servers.

**Character Information**
Megalosaurus, Gecko skin.

**Additional Information**
N/A

**Comment by Soals** [comment]
Fixed this

**Comment by CeciliaSE** [comment]
Have not been able to replicate the specific bio layer. Ticket may be closed and considered fixed.
