### ISSUE TITLE
Ory Burrow Entrance & Carry icons persist when HUD is disabled.

### ISSUE THREAD

**Issue by paratea** [BoBAdministration/QA-Bug-Reports#80]
**Describe the Bug**
The icon for carrying an object and the burrow icon both persist when the HUD is disabled.

**To Reproduce**
1. Log onto any server with an Ory.
2. Create a burrow.
3. Ensure talents are put in up to at least one Burrow Master.
4. Dig until you find an object to pick up.
5. Pick up object.
6. Disable HUD

**Expected behavior**
All icons disappear with HUD disable.

**Actual behavior**
The two icons stay on your screen.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/77513445/135941437-787266df-bdeb-4d39-b70a-c1890c875f58.png)

**Branch Version**
Live (and Tester)

**Character Information**
Ory, any size as long as one Burrow Master point.

**Additional Information**
Need to be holding decorative object for carry icon to show.

**Comment by Predatoria** [comment]
The icon hides when you toggle player name tags.  It's not really a bug, but may be unintuitive.  I fixed the carry icon.

**Comment by SilverWing430** [comment]
Confirmed fixed on tester
