### ISSUE TITLE
Heavy plants not so heavy

### ISSUE THREAD

**Issue by kheprisun1** [BoBAdministration/QA-Bug-Reports#81]
**Describe the Bug**
Placing down max weight in plants and adding some more then picking it up exceeds previous max weight cap.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 6
2. Spawned in a Para
3. Set to 1.2
4. Pick up max amount of plants and set down
5. Pick up some more (not max amount) and set down in same pile
6. Hold to grab

**Expected behavior**
Should not exceed original weight cap

**Actual behavior**
Exceeds previous weight cap

**Screenshots & Video**
If applicable, add screenshots to help explain your problem, or attach a video/gif. You can do this by just pasting in your image(s)!
https://youtu.be/acE1RrQSSbc

**Branch Version**
Tester and Live

**Character Information**
1.2 Parasaur

**Additional Information**
--

**Comment by Vallyhalla** [comment]
Currently with how dropped foliage is on live and tester you can't pick up much anymore, so I'm marking this as fixed and closing!
