### ISSUE TITLE
Unable to pick up gore on next to glow/fat plants

### ISSUE THREAD

**Issue by kheprisun1** [BoBAdministration/QA-Bug-Reports#82]
**Describe the Bug**
If you place a gore on or next to a fat plant, you are unable to pick it back up.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Spawned Rex
2. Grew to 1.2
3. Place gore next to fat plant
4. Attempt to grab gore

**Expected behavior**
Gore is expected to be picked up again

**Actual behavior**
You are unable to grab the gore again

**Screenshots & Video**
If applicable, add screenshots to help explain your problem, or attach a video/gif. You can do this by just pasting in your image(s)!
--
**Branch Version**
Live

**Character Information**
Rex 1.2

**Additional Information**
Ancestral Plains

**Comment by Zi-Mom** [comment]
Unable to reproduce on Tester
