### ISSUE TITLE
"Unjam" bug

### ISSUE THREAD

**Issue by Katze-eng** [BoBAdministration/QA-Bug-Reports#83]
Describe the Bug:
Currently on the Live branch "Unjam" should reset the position of the player, but instead, due to a specific "tactic" it can broke some of your hitboxes

To Reproduce:
1. Spawn as an apato
2. Press ESC and move your mouse to the "Unjam" button
3. Close the ESC menu
4. Press RMB and immediately open the ESC menu and click "Unjam"
5. Wait until the panel "Attempting to unjam..." is almost gone
6. At the end of this panel press LMB (you will see how you would be able to walk while stomping) and at the end of the stomp press RMB, it will reset the stomp animation
7. Without pressing LMB your tail hits will deal the stomp damage, your front leg hitboxes and tail hitbox would be jammed
8. In this case, apato can deal some periodic damage, but not always

Expected behavior: 
Unjam should reset the player position/actions

Actual behavior:
Because of the 5 seconds timer, it could get bugged your attacks/hitboxes
This works for the next creatures:
Apato - tail deals the same dmg as a stomp (front legs and tail hitboxes)
Ichthy - a usual bite can get bugged with it's claws attack, making your attack hitbox bigger
Para - same as an apa, it could deal the stomp dmg with it's head hits
Ory - your sand attack can get bugged too, so your bites will get the same hitbox as a sand attack, and it could blind the enemies
It actually can work for the all dinos, but it's easier to do with the list I just described.

Screenshots & Video:
https://youtu.be/ubfay9kAZyw
00:25 - bugged the para attacks
01:28 - bugged ichthy
04:04 - bugged apa
04:48 - bugged para
05:17 - bugged para
05:43 - mega walked in to me and got damage, while I was laying down (it doesn't shot it yo you when it happens? but you can see blood on it's head when it walked in to me)
06:04 - I walked with my meg in to a bugged apato

**Comment by Vallyhalla** [comment]
Apa can no longer stomp, and we changed that you can't instantly hit unjam anymore. This has been fixed!
