### ISSUE TITLE
Patch of water on RS

### ISSUE THREAD

**Issue by Alyrius** [BoBAdministration/QA-Bug-Reports#85]
**Describe the Bug**
There seems to be a bugged patch of water on rs that lets you swim in the air.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. log onto RS server
2. Spawn a meg and tp to snowy Montain (Coords: X:-221381 Y:-15472 Z:18404)
3. Walk over the area in the video 
4. Swim?

**Expected behavior**
No free floating invisible water

**Actual behavior**
Free floating in invisible water

**Screenshots & Video**
https://youtu.be/JMyTdPqXp48

**Branch Version**
Live

**Character Information**
Coah at .5

**Additional Information**
Royal shores

**Comment by Predatoria** [comment]
This seems to already be fixed.  The place in the video is now under the terrain and the landscape has been flattened to be significantly higher than in the video.
