### ISSUE TITLE
Footprints not appearing on beaches

### ISSUE THREAD

**Issue by The-Grand-Tickler** [BoBAdministration/QA-Bug-Reports#86]
**Describe the Bug**
Footprints seem to work great on inland sand and mud, however walking on the sand on the beach near sea level most often does not produce any footprints

**To Reproduce**
1.  Logged into Dedicated Testing 1
2. Spawn as any creature besides Coah, Sai, and Lurdu
3. Teleport to either of these example coordinates: (52566 275513 2439) (-26460 5038 3400) or find a nearby beach
4. Walk towards the Ocean
5. Observe that you have footprints until you get closer to the water

**Expected behavior**
Any Sandy Texture would produce footprints

**Actual behavior**
Sandy texture inland always produces footprints, sandy texture next to the ocean most often does not.

**Screenshots & Video**
Footprints: ![image](https://user-images.githubusercontent.com/88917110/139453285-8e666217-85a1-47ac-a5b5-4b365d2378b9.png)
Walk forward towards sea level and footprints no longer spawn 
![image](https://user-images.githubusercontent.com/88917110/139453350-5e6edcff-06be-4726-b205-033326e0116d.png)
Footprints appear on sandy path: 
![image](https://user-images.githubusercontent.com/88917110/139453407-77e7d0d4-ad4b-481a-a25b-5dcb33453d30.png)
Footprints do not appear at the end of the path closer to the sea: 
![image](https://user-images.githubusercontent.com/88917110/139453470-83df6f4a-9653-4034-b845-ab81411b2fce.png)

**Branch Version**
Tester 

**Character Information**
Any creature besides Coah, Sai, or Lurdu as they do not have footprints set up yet.

**Additional Information**
Rival Shores

**Comment by Zi-Mom** [comment]
Confirmed
