### ISSUE TITLE
Refresh Rotten Meat Bug

### ISSUE THREAD

**Issue by Lazulie14** [BoBAdministration/QA-Bug-Reports#87]
**Describe the Bug**
if you leg a  rotten gore and you place it on the ground about a minute or so it'll turn fresh again

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. log on to live server
2. spawn as a small creature 
3. find rotten gore large enough
4. leg it 
5. then place it on the ground 
6 wait 1-2mins and the leg will refresh

**Expected behavior**
A legged piece of meat will stay bad

**Actual behavior**
A Legged piece of meat will turn fresh after 1-2 mins

**Screenshots & Video**
https://www.youtube.com/watch?v=71qtUCCjL3U

**Branch Version**
Live.

**Character Information**
Pref a small enough creature that will be able to leg a gore

**Additional Information**
may or may not look fresh  and actually be bad needs further testing

**Comment by Vallyhalla** [comment]
This has been fixed!
