### ISSUE TITLE
Fishing Glitch

### ISSUE THREAD

**Issue by MysteryKit66** [BoBAdministration/QA-Bug-Reports#9]
**Describe the Bug**
Darting trough a fish gives more food and satiate to a dino then that it would normally do with just biting at one.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. ex. Spawning as a Itchy
2. ex. search for 1 fish
3. ex. Dart towards it while holding E
4. ex. 1 Fish gives like 20+ food

**Expected behavior**
Darting trough a fish while holding E should only give the same food and sat as if you would normally bite/eat them.

**Actual behavior**
Darting trough a fish while holding E  gives the player more food then what it should have like 20+ more

**Screenshots & Video**
https://youtu.be/c1ROWwpFLD4 

**Branch Version**
Tester or Live.
Both versions
**Character Information**
Itchy 1.2 and 2.2 no scavenger points invested

**Additional Information**
Map type, weather, or any other context about the problem here.

**Comment by Predatoria** [comment]
Should be fixed next tester patch

**Comment by teatimejess** [comment]
Seems to be fixed fairly close, may need review. Marginal difference in food only. Dart: 5.538, Bite: 5.49 (at around 0.45 growth).

**Comment by Zi-Mom** [comment]
Bite fish = 3.5 food
Dart fish = 1.5 food
Dart and then Hold Use key fish = 3.5 food
