### ISSUE TITLE
Missing water in water cave

### ISSUE THREAD

**Issue by OverlordGrima** [BoBAdministration/QA-Bug-Reports#92]
**Describe the Bug**
found a watercave with weird texture that looks like water is missing

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 11
2. ex. Spawned in as tropeo
3. began exploring the map
4. Found water cave at X: 424723 Y: 345712 Z: -13103

**Expected behavior**
water texture to be seamless

**Actual behavior**
silly scissor like cut of water texture missing. size and shape changes depending on where you look from

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/89408428/141037582-8f8190e6-852c-4757-b7ed-01b77f836d80.png)

**Branch Version**
Tester 

**Character Information**
1.0 tropeo

**Additional Information**
Islatitania

**Comment by OverlordGrima** [comment]
found another spot, at other end of the cave 
![image](https://user-images.githubusercontent.com/89408428/141037828-17b797fd-b4d1-438d-96b9-513f7a0c8e62.png)

**Comment by Predatoria** [comment]
This is a bug with the water shader, which is created from the Oceanology plugin.  I don't know how to fix it.
