### ISSUE TITLE
Able to lift rocks on Titania

### ISSUE THREAD

**Issue by DragonSaviour** [BoBAdministration/QA-Bug-Reports#93]
**Describe the Bug**
You are able to pick up large rocks on Titania.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log into Dedicated Testing 12
2. Teleport to coordinates: X:153433 Y:505142 Z:-9687 (EDIT: found a different rock with the same problem after posting at: X:139655 Y:518810 Z:-10071)
3. You will notice a prompt to pick up the rock at these locations.
4. Picking up the rock will spawn a new rock. 

**Expected behavior**
The rock should not be able to be grabbed.

**Actual behavior**
You are able to grab the rock and create (hollow) duplicates.

**Screenshots & Video**
![duplicatingrock3](https://user-images.githubusercontent.com/89356026/141669262-cdfab76c-9edd-49dc-b2fd-1271628d0d25.png)
![duplicatingrock2](https://user-images.githubusercontent.com/89356026/141669261-9cbac28b-9346-44bd-b305-e55c26699edd.png)
![duplicatingrock](https://user-images.githubusercontent.com/89356026/141669256-91fc4ed6-b7a9-4dd5-ab72-e8ad9c70486c.png)
![duplicatingrock4](https://user-images.githubusercontent.com/89356026/141669577-35509118-2ad4-4a13-888c-4ad2c05c87e8.png)

**Branch Version**
Tester.

**Character Information**
Used Pachy to find this issue.

**Additional Information**
N/A

**Comment by Predatoria** [comment]
This should be fixed now

**Comment by DragonSaviour** [comment]
I'm no longer able to lift the rocks, but I still got a grab prompt on a couple of em:
![rockprompt](https://user-images.githubusercontent.com/89356026/143383756-c36cdd2e-e950-415d-b397-91ec883b059b.png)
. 
![rockprompt2](https://user-images.githubusercontent.com/89356026/143384158-2e6ac865-9019-49b1-99e6-221fc501c861.png)

Other than that minor issue I can confirm rock lifting is fixed!

**Comment by Predatoria** [comment]
Fixed the interaction prompt!

**Comment by DragonSaviour** [comment]
Checked just now and can confirm prompt issue is gone as well! Closing now! :D
