### ISSUE TITLE
Minor Megaraptor animation looping errors

### ISSUE THREAD

**Issue by theriversedge** [BoBAdministration/QA-Bug-Reports#94]
**Describe the Bug**
Some minor looping errors in the neck area for Megaraptor's idle 1, crouch idle, and stand to sit animations

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 1
2. Spawned as Megaraptor
3. Force grew to 1.0
4. Demonstrated the aforementioned animations

**Expected behavior**
All animations should loop smoothly/have smooth transitions

**Actual behavior**
The aforementioned animations seem to loop improperly in the neck area

**Screenshots & Video**
Idle 1 loop error:

https://user-images.githubusercontent.com/55609311/143978899-eb344890-8c79-4850-8d8a-52f7a279e2c3.mp4

Crouch idle loop error:

https://user-images.githubusercontent.com/55609311/143978943-cf17fca2-011d-4a71-a6ba-db83f0438c9c.mp4

Stand to sit loop error:

https://user-images.githubusercontent.com/55609311/143979062-b2fe6b88-797c-419e-b902-61437aa71282.mp4

**Branch Version**
Tester

**Character Information**
1.0 Megaraptor

**Additional Information**
N/A

**Comment by Predatoria** [comment]
Got some fixes from Wobbly
