### ISSUE TITLE
meg has hole in model

### ISSUE THREAD

**Issue by OverlordGrima** [BoBAdministration/QA-Bug-Reports#96]
**Describe the Bug**
was checking out testing when i went to spawn as meg and noticed blue under one of the legs. not too noticable unless camera is pointed towards it and backround is different color from skin

**To Reproduce**
1. Logged into Dedicated Testing 11
2. created new dino
3. selected meg
4. rotated camera and notice hole

**Expected behavior**
no holy meg

**Actual behavior**
meg had hole in right leg

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/89408428/144649686-232ea635-2ac1-42a5-af6a-b8419f9745f9.png)

**Branch Version**
Tester 

**Character Information**
Dinosaur growth and type. Include any other relevant character information such as talents, inherits, gender, and stats if necessary.

**Additional Information**
Map type, weather, or any other context about the problem here.

**Comment by OverlordGrima** [comment]
there also appears to be hole on the right fingers
![image](https://user-images.githubusercontent.com/89408428/144650098-79a19025-48db-4418-879e-3b5a379ca38c.png)

**Comment by Predatoria** [comment]
We don't plan to fix this.  We're just going to eventually remodel megalo.
