### ISSUE TITLE
underside seam busts open on Velo

### ISSUE THREAD

**Issue by OverlordGrima** [BoBAdministration/QA-Bug-Reports#97]
**Describe the Bug**
model sort of opens up on the neck and down

**To Reproduce**
1. Logged into Dragonstone
2. ran around as velo on velo island
3. got fat off spawn gore
**Expected behavior**
no seam splitting

**Actual behavior**
Velo seam split open like a gutted fish

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/89408428/144688818-e31cde6b-3158-465e-9731-5aa2c9e0c1d9.png)

**Branch Version**
Live.

**Character Information**
1.23 male velo, Fat. 

**Additional Information**
noticed before its there on baby velo, must test if its while fat or just at any point

**Comment by Predatoria** [comment]
We won't fix this.  We will eventually remodel velo.
